### ISSUE TITLE
Replacing DB mistakenly marks artifacts as deleted

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1002]
* Upload "hyperbloom_fun"
* Upload "van"
* notice that Raiden and Yelan are missing a couple artifacts (30 artifact total were deleted, which is the size of the "hyperbloom_fun" db)
* I would expect that these artifacts should stay, since they weren't actually deleted
[Hyperbloom_fun_2023-02-06_06-25-02.txt](https://github.com/frzyc/genshin-optimizer/files/10777585/Hyperbloom_fun_2023-02-06_06-25-02.txt)
[Van_2023-02-18_04-31-58.txt](https://github.com/frzyc/genshin-optimizer/files/10777587/Van_2023-02-18_04-31-58.txt)

**Comment by frzyc** [comment]
???
<img width="882" alt="image" src="https://user-images.githubusercontent.com/1754901/221456427-e25ab639-6cdc-48b8-8608-9354f7a4b062.png">
Are the artifacts here mutually exclusive? did you enable or disable "Delete items not in import"?

**Comment by nguyentvan7** [comment]
Yes they are mutually exclusive, and need to enable "Delete items not in import"
