### ISSUE TITLE
Graph result number not matching build preview

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1021]
Noticed on Thoma but suspect its more widespread.

![image](https://user-images.githubusercontent.com/101696552/220825127-4cbce785-3609-4725-b962-4456d8008805.png)
Graph target says shield dmg absorption is 13.7k

![image](https://user-images.githubusercontent.com/101696552/220825191-c6339e66-9179-484b-83b4-47fc9287eee1.png)
But it's showing as 17k in the result

[Stain_2023-02-23_05-02-10.txt](https://github.com/frzyc/genshin-optimizer/files/10810405/Stain_2023-02-23_05-02-10.txt)

**Comment by StainAE86** [comment]
its effecting the build constraints as well. so if I set a build constraint of 17k shield absorption the currently equipped build (which meets the requirements) wont show

**Comment by frzyc** [comment]
fixed in `9.4.3`
