### ISSUE TITLE
New idea of change charater equipment prioritization

### ISSUE THREAD

**Issue by Rodari9** [frzyc/genshin-optimizer#1025]
![GO](https://user-images.githubusercontent.com/89182605/220881555-ebc67f93-2b72-4957-a2fa-3ead044708cf.gif)

**Comment by nguyentvan7** [comment]
What would be the exact benefit of being able to drag and drop a character on the list? It doesn't change any of the functionality if they are on a different place on the list

**Comment by Rodari9** [comment]
> What would be the exact benefit of being able to drag and drop a character on the list? It doesn't change any of the functionality if they are on a different place on the list

In the old version of GO(about 2-3 days ago) you could change the prioritization of using artifacts and i think that will be good idea in new version of interface

**Comment by nguyentvan7** [comment]
This list is now per-character so it wouldn't make sense to have the order affect other characters anymore. Frzyc discussed why we made this change in the discord if youd like to read the reasoning

https://discord.com/channels/785153694478893126/785176548428087306/1078155958892638300
