### ISSUE TITLE
Move (or remove) "Allow Partial Builds" button

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1029]
![image](https://user-images.githubusercontent.com/101696552/221348125-57d9b2fb-c708-49c7-91df-f2f7f3a6e3a5.png)

I'm sure you've left this here on purpose just to trigger my OCDs and I can't take it anymore.

Put it at the bottom instead of in the middle of all these blue buttons.

![pepeagony](https://user-images.githubusercontent.com/101696552/221348162-030a5478-f80d-4728-bcf9-ddff6ed5bd6b.gif)

**Comment by frzyc** [comment]
It's top down: artifact settings, then one with character select.
