### ISSUE TITLE
Allow users to curate a "default" allow/disallow list

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1030]
Many users want to make it so certain number of their fav or most used characters never have their artifacts considered by others during the build process no matter what condition or team they are played in.

Instead of forcing the user to setup the disallow list for every single other character every time a new character is added let them configure and "save" a default state which will appear as soon as you toggle on "use equipped" as per the #1027 suggestion.

And then could introduce a "reset" button on the chara select popup which would "reset" the selection to your pre-configured default.

![image](https://user-images.githubusercontent.com/101696552/221348591-a2368c9b-82a1-44b9-9ea0-6f632f0e0301.png)

**Comment by nguyentvan7** [comment]
Probably won't be considered. We plan to make the default custom-list have everything enabled, including new/future characters. We also plan to add a 3-state toggle so you can quickly swap between none allowed, custom list, and all allowed
