### ISSUE TITLE
Now unable to quickly allow a character to use equipped and then return them to their previous setting

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1033]
In the prio list feature you could quickly add a character or move an existing one to the top of the list for testing purposes.
Then when you were done you could either delete that single character or move them back to their orginal position via the text box input.

Now this is no longer an easy process. Say for example I have the following equipped status setup on Rosaria:
![image](https://user-images.githubusercontent.com/101696552/221350797-14cabad0-c775-453e-be21-446caa76a1eb.png)

I can easily click "add all to allow list" to achieve the first part of the goal. However setting this state up again is now a much more difficult process since the rest of the list has been wiped and no longer being "held" at a lower prio state or as a visual reference to slot the character back into their previous prio queue.

Issue #1030 would help this to a degree. But there is no guarantee that the "default" state the user has configured will be the state they had, or wanted this particular character to be in.

Currently I would have to memorize this equipped list and manually recreate it after doing the testing I wanted to do.
Another option would be creating a second copy of this database to run tests in which I can then just delete after so the "main" database is left untouched. Eitherway neither options are ideal and feel like a downgrade on the functionality the prio list had previously.

Issue #401 may be a solution if you could create another "instance" of the character for testing a different team or conditional state in so you don't have to destroy your current "loadout" settings. But there still may be times you want to quickly see what the "best" build option your character has compared to their limited selection option is without completely wiping the equipped allow/disallow list.

**Comment by nguyentvan7** [comment]
What about turning Exclude Artifacts and Allow Equipped Artifacts back into checkboxes, then add a cog to the right side like the old art set config?

Then users can config Exclude and/or Allow Equipped and easily switch them on and off at will for whatever reason they might want.

This would also standardize all the buttons to look similar again and remove the big ugly cyan button for art set config, basically fixing #1029 and #1028 at the same time

**Comment by nguyentvan7** [comment]
![image](https://user-images.githubusercontent.com/36019388/221372103-af90b9b1-06ba-4ccb-89e6-dc3fb6c514c5.png)
Ignore the art set config button being larger, i just threw this together

**Comment by frzyc** [comment]
> ![image](https://user-images.githubusercontent.com/36019388/221372103-af90b9b1-06ba-4ccb-89e6-dc3fb6c514c5.png) Ignore the art set config button being larger, i just threw this together. And would need to change the string back to "Use Excluded Artifacts"

Extra tibit:
- When "exclude artifacts" is "off", and you choose an artifact to exclude in build result, it should set it to "on"
- When "allow equipped artifacts" is "all", and you choose to unallow a character, it should set it to "custom

**Comment by StainAE86** [comment]
> Extra tibit:
> 
> * When "exclude artifacts" is "off", and you choose an artifact to exclude in build result, it should set it to "on"
> * When "allow equipped artifacts" is "all", and you choose to unallow a character, it should set it to "custom

Yes that makes sense. Because the moment you exclude or unallow from a blank/default slate the assumption is you want to use the custom list.
