### ISSUE TITLE
Fields padding is not correct

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1036]
![image](https://user-images.githubusercontent.com/36019388/221375342-7001d81d-de53-4dc3-9184-adf3fb82404a.png)

**Comment by frzyc** [comment]
probably padding for icons that doesnt exist...

**Comment by nguyentvan7** [comment]
StatIcon in StatIcon.tsx is returning `null` for these keys, but the jsx still exists since it hasn't been called as a function yet or something
![image](https://user-images.githubusercontent.com/36019388/221772891-c5af9c42-b734-4aa2-a4d3-2b2776dcb76e.png)

idk what to look up to resolve this, do you know @frzyc, feels like it should be a simple fix
