### ISSUE TITLE
Yoimiya C6 not calculated properly

### ISSUE THREAD

**Issue by BreadCatOW** [frzyc/genshin-optimizer#1055]
naganohara meteor swarm cannot proc twice on n1/n4, rather the total multiplier from those shots are taken and then multiplied by 60%. 

with t10 normal and 13 skill it would be 
63.6% * 2 * 170.6% * 60% in 1 shot rather than 63.6% * 170.6% * 60% in 2 separate shots. the same is true for n4 except the normal attack multiplier is higher

**Comment by nguyentvan7** [comment]
Not listed in kqm tcl, but listed in the kqm graph. I'll update it soon https://keqingmains.com/yoimiya/#Constellations
