### ISSUE TITLE
Setup Github actions

### ISSUE THREAD

**Issue by eeeqeee** [frzyc/genshin-optimizer#1060]
Automatically check:
- [x] ESlint
- [ ] TSC
  - [x] Libs
  - [ ] App
- [x] Tests
- [x] Prettier

Deploy:
- [ ] Auto builds for each pr (needs separate subdomain)
- [ ] Nightly build for master branch
- [x] 1 click deploy for new versions

**Comment by nguyentvan7** [comment]
We would also need to set up prettier. Which also means embracing multi-line imports which i hate, but am willing to live with
