### ISSUE TITLE
Allow for fast way to bulk exclude filtered artifacts per character

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1076]
https://discord.com/channels/785153694478893126/1084490038219382784

Now that excluded are per character rather than global it has removed the feature of bulk management for including/excluding artifacts.
For example you could filter for all Feathers and bulk exclude them. Then include just 1 of them to effectively force the Optimizer to generate the best build around that Feather.

I suggest putting the bulk management buttons; Exclude, Include, Lock, Unlock on the "Select artifact to add to this character's exclusion list" popup window for more power to the user:

![image](https://user-images.githubusercontent.com/101696552/224612371-85eb8f06-4dbb-4b56-af11-a441ea23c40c.png)

![image](https://user-images.githubusercontent.com/101696552/224613228-3b24d596-c2d4-44c6-a0ef-21342ce1c0b2.png)

**Comment by CordonZeus22** [comment]
I can work on this
