### ISSUE TITLE
Add "Burst Active" toggle for Raiden's elemental skill.

### ISSUE THREAD

**Issue by BreadCatOW** [frzyc/genshin-optimizer#1078]
Raiden's E is affected by her C2, but only while the burst is active, if the burst is not active then her E does not gain DEF ignore.

**Comment by nguyentvan7** [comment]
https://library.keqingmains.com/evidence/characters/electro/raiden-shogun#c2-steelbreaker yea looks like it needs to apply to any damage raiden does during the duration. thanks!
