### ISSUE TITLE
Deepwood Memories can stack in optimize

### ISSUE THREAD

**Issue by littlef0x** [frzyc/genshin-optimizer#1079]
For a team including two characters using Deepwood Memories, if the effect of the artifact in Team Buffs tab and Optimize tab are both checked, they will stack and result in -60% Enemy Dendro RES, which is not in consistent with its real behavior.

For example, with only Team Buffs one checked, Dendro RES -40%:
![图片](https://user-images.githubusercontent.com/32670075/224973761-03cace4b-0989-4c01-aa5d-e443b1b81f54.png)

With both checked, Dendro RES -70%, which is incorrect:
![图片](https://user-images.githubusercontent.com/32670075/224973947-59ca41c3-9731-4c79-8cbb-4fe2b22320b8.png)

**Comment by StainAE86** [comment]
Known issue for all non-stacking buffs #361

It's a larger issue to fix than first seems and is waiting on a system change in the back end of the code.
For now just don't enable the conditional on one of the characters.
