### ISSUE TITLE
"Use Equipped" count showing "-1" on Traveller 

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1080]
![image](https://user-images.githubusercontent.com/101696552/224979758-bc6f6da2-ee47-47e1-a523-9960e15d4272.png)

**Comment by frzyc** [comment]
Also, the UI for the equip location selection should be "LocationKey" based, and not "CharacterKey". This will resolve having multiple travelers that show up in this UI:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/1754901/229304431-5833b888-4323-495d-a819-1f82a5cee2ab.png">
