### ISSUE TITLE
Adding an artifact to the "Exclude" list enables using artifacts from the exclude list

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1088]
When you add (or remove) an artifact manually via the exclude artifact popup the list gets enabled causing the builder to include what you've just specifically setup to exclude.

![image](https://user-images.githubusercontent.com/101696552/226099843-7bdf174e-4cd4-4556-83d6-e3ea6cce638a.png)

![image](https://user-images.githubusercontent.com/101696552/226099876-57835eef-59d9-4881-bed4-191d23367fff.png)

**Comment by nguyentvan7** [comment]
This was meant to be similar to how when you toggle a character in the allow list, it will auto switch to using the custom list. I guess it shouldn't do that for excluded artis tho

**Comment by frzyc** [comment]
>  causing the builder to include what you've just specifically setup to exclude.
Not 100% sure what this means.

My 2cents is that if someone adds an artifact to the exclude list, that would imply that the exclude list feature should be "enabled" to exclude this artifact. 
I am not sure about a UX flow where a user adds an artifact o the exclude list, and wouldnt want that exclusion to be active right after.

**Comment by StainAE86** [comment]
> if someone adds an artifact to the exclude list, that would imply that the exclude list feature should be "enabled" to exclude this artifact.

![image](https://user-images.githubusercontent.com/101696552/233813346-1b3fb1e4-141e-47b4-ba51-fbcc0ed0f55a.png)

Think about that again

**Comment by frzyc** [comment]
I did, and I put those thoughts into a coherent comment. 
I believe its currently your turn to do that now. 
You can start with
1. what is the current behaviour/workflow, and why it isn't "working"
2. what is your imagined UX flow and why it would be better.

**Comment by StainAE86** [comment]
Currently enabling the "**USE** Equipped Artifacts" checkbox means any artifacts that are on the Excluded List get INCLUDED by the builder.

You add an artifact to the Exclude List specifically so it doesn't get considered by the builder.
But currently as soon as you do that the "**USE** Equipped Artifacts" checkbox gets automatically enabled.

Meaning you're not actually excluding the artifact you just added to the Exclude List.
