### ISSUE TITLE
Add sorting by artifact RV in Character page

### ISSUE THREAD

**Issue by littlef0x** [frzyc/genshin-optimizer#1089]
It would be useful if one wants to find whose artifact is not good enough and decide which one to farm.

BTW, I'm thinking about another concept, something like a parameter to measure the degree of 'graduation' for artifact substats, because RV is not always enough for the purpose. For example, useful substats for Kokomi include only HP, HP%, and ER, and thus the RV is relatively low even if every roll results in one of them. This parameter may be defined as 
$$\frac{\text{current RV}}{\text{theoretical maximum RV}}$$
For the example of Kokomi above, the theoretical maximum RV is 3800%, while it's 4500% for some other characters. And if this parameter is added, it would be better to use this parameter for sorting in character page.

**Comment by StainAE86** [comment]
frzyc has previously said he doesn't want to add character sorting by RV:
https://github.com/frzyc/genshin-optimizer/issues/317#issuecomment-1140353156

You're welcome to try to convince him further. But will probably have to come up with a good argument and concept for it.

**Comment by littlef0x** [comment]
Oh, sorry, I didn't see that issue.

In fact I also think RV filter isn't a perfect choice since it doesn't make sense sometimes, although it may be easier to realize. A 2500% Kokomi is fairly good, while a 2500% Hu Tao is just so so. That's why I come up with that idea (I don't know what's the corresponding concept in EN community, let me call it DOG (**degree of graduation**) for the time being).

I'm thinking about it because as old players, my friends and I are always irresolute when choosing which artifact to farm, since most of our characters are fairly good. And thus I think such a concept may be helpful. You can just farm for the one with the lowest DOG. Also, it may help players to evaluate the artifact of their characters in a more direct way. Compared with RV, DOG is a more overall parameter and is more comparable between different characters, and thus I think it's more proper to show in charactercard.

Thinking further, the above DOG concept is not absolutely accurate when choosing artifact to farm, because the possibility of obtaining useful substats is not the same for different character. For example, you have Xiangling and Kokomi with 80% DOG for both. But from the angle of probability, it's easier to obtain enhancement if you farm for Xiangling. The most accurate concept for that is **average Resin cost**, i.e., how much Resin in average will be used to get artifacts with such RV. But I'm afraid it's too hardcore and not many players understand it.

They are not very common concepts and I don't know whether it's hard to realize. So that's just a personal suggestion. It will be appreciated if anyone want to further discuss it or realize it.

**Comment by frzyc** [comment]
@littlef0x 
I think using RV to track "which artifact to farm next" has a lot of fallacy, as you stated above. I can list a few more, fundamental issues:

- RV is a metric for substat, and does not consider mainstat
- RV does not consider artifact sets
- RV does not correlate slots.
- If you have the "right main stats" then your "effective total RV" actually may goes down.

All these flaws applies to your `DOG` concept(I do love the name). I understand `RV/max RV` can be a measurement for "artifact growth"(to an artifact in isolation), but the numbers have less meaning when you apply it to the context of a character.

If we go back to the drawing board with a feature that will help with "which artifact to farm next?", shouldn't this feature at least consider the availability of set+slot+mainstat? I am not sure what kind of feature this will be, but I would at least want it to be considerate of how many of "on set good main stat" artifacts I have in my inventory. If you want a feature like this, I would advice starting from here instead.

**Comment by littlef0x** [comment]
Thanks for your reply.

> All these flaws applies to your DOG concept

I'd like to clarify that the DOG concept above only cares about substats. That's because for most DPSs and some supports, correct artifact set and mainstats are prior to all substats, while for others, substats doesn't matter at all. So only makes sense under the premise of correct (similar if not the same, since some characters can choose more than one artifact set) artifact set and mainstats.

Meanwhile, DOG should be considered only if all the 5 pieces are equipped. From this aspect, I think DOG is more useful than RV, because RV can only be used for vertical comparison (i.e., compare between the current and original artifact of the same character), but DOG can also be used for horizontal comparison (i.e., compare between different character).

> shouldn't this feature at least consider the availability of set+slot+mainstat?

Yes, I have to admit that this definition isn't perfect because the same RV/DOG doesn't mean the same value if the mainstats are different. Also, the values of 2+2 and 4-pc are not the same. There are more accurate concept, e.g., average resin cost or rank among a huge number of players. But we should find a balance between accuracy and understandability. I don't think this DOG concept can completely solve the problem, but it makes sense to evaluate the substat of artifact. More thoughts are welcome since I have not found a satisfying balance point between accuracy and understandability.

**Comment by frzyc** [comment]
Feel free to submit another feature request once you can think of a better design.
