### ISSUE TITLE
GO seems to be ignoring Noelle DEF->ATK conversion when using burst as a target

### ISSUE THREAD

**Issue by Shassk** [frzyc/genshin-optimizer#1090]
When I've tried to optimize my Noelle build after getting her to C6 I get very strange builds with 2NO/2 Archaic Petra showing total around 1300 ATK in formulas instead of ~3500 ATK (which is what my 1000 ATK 2000 DEF C6 Noelle has rn after using her burst) - and I see no obvious option in the GUI to enable her DEF->ATK conversion when I select burst as a target. What should I do? I've tried to select both "Skill DMG" and "Burst DMG" as targets but got the same result. And there's no obvious option for self-infused NAs either.

**Comment by Sinesthesia** [comment]
Talents tab? Did you activate her C6? Or turn on her burst state? https://youtu.be/hiRjngMgHfQ

**Comment by Shassk** [comment]
Wow, that's... so incredibly unintuitive. The entire point of optimizing tab is to set conditions so why one of condition switches is located in an entirely different place?

Thanks tho, it did the trick.

**Comment by Sinesthesia** [comment]
Talent conditionals are in the talents tab. You had to go to the talents tab to level the talents anyway so 🤷

**Comment by Shassk** [comment]
>You had to go to the talents tab to level the talents anyway so

Not when you import data from Inventory Kamera - all that data including talent lvls is already there.

**Comment by Sinesthesia** [comment]
GO can't assume everyone uses Kamera to import.

**Comment by Shassk** [comment]
OK makes sense now

**Comment by StainAE86** [comment]
You have to consider that what if you wanted to optimize for Noelle's normal attacks? You must have a way to "turn off" the condition that the burst talent puts you in. Which is why even if you're activating _FOR_ the burst, you need to tell GO that the resulting condition has been met.
