### ISSUE TITLE
Can't set some Character's Constellation Level

### ISSUE THREAD

**Issue by claw68** [frzyc/genshin-optimizer#11]
![image](https://user-images.githubusercontent.com/4363686/110756590-5dbf2000-8285-11eb-999c-c3a60cf9b3a4.png)

This also the case with these characters:
- Chongyun
- Diona
- Jean
- Kaeya
- Klee
- Lisa
- Qiqi
- Razor
- Sucrose
- Tartaglia
- Traveler
- Xiangling
- Xinyan
- Zhongli

**Comment by frzyc** [comment]
Yes. Unfortunately, those characters do not have a completed character sheet with talents. Once a character sheet is completed, constellations will be able to be toggled.
Here is our progress: [https://trello.com/c/s6c9vPRP/52-character-talent-constellation-calculations](url)
If you wanna get updated when a character's sheets get added, join our discord and get a role: [https://discord.gg/CXUbQXyfUs](url)
Thanks for using GO!
