### ISSUE TITLE
Buffs that cannot be nested in the game are nested in the optimizer.

### ISSUE THREAD

**Issue by Lisedrika** [frzyc/genshin-optimizer#1107]
If there are multiple buffs of type "Millennial Movement", the same stat buffs do not nest.

Please check the attached screenshot.
The 20% attack buff that Kazuha gives and the 20% attack buff that Sara gives are nested at the same time.
This results in damage calculation errors in the actual game.

In a situation like a screenshot, only one of the attack power buffs applies.
Therefore, the amount of attack buffs will have to be 40%.
Other buffs except for attack power buffs are not the same, so they all apply normally. (e.g., elemental mastery)
We need a special buff filtering is required for like this.

Thank you.

![image](https://user-images.githubusercontent.com/9856673/227772190-d9c81c21-b164-4fb8-aa5f-2a4b4fcf108e.png)

**Comment by StainAE86** [comment]
Known bug. #361
