### ISSUE TITLE
Abnormal terms in POEditor

### ISSUE THREAD

**Issue by littlef0x** [frzyc/genshin-optimizer#1109]
Here's what POEditor looks like now:
![图片](https://user-images.githubusercontent.com/32670075/228558659-e334d44d-14ab-4002-839e-cd1b07118e41.png)

They seems to be name of variables but not phrases that should be translated. I've no idea what happened, but they may come from `libs/localization/assets/locales/en/artifact.json`.

**Comment by PolomoPT** [comment]
Fixed.
