### ISSUE TITLE
Duplicate detection UI

### ISSUE THREAD

**Issue by Mars4it** [frzyc/genshin-optimizer#1110]
I'm not sure how to ask questions since the wiki page doesn't allow me to ask how to do things.

Is there a button or way to detect and delete duplicate artifacts? I used the ArtiScan thing but it made duplicates and almost all my artifacts were duplicated (ㄒoㄒ)

Thank you! And have a great day :)

**Comment by frzyc** [comment]
I think we should have a system that shows duplicates within the system, and let user decide on what to do with them (delete/update).
