### ISSUE TITLE
Allow reordering characters inside Equipped Artifact Configuration list

### ISSUE THREAD

**Issue by Cynplytholowazy** [frzyc/genshin-optimizer#1113]
Need some way to reorder the list so I don't have to look for characters 1 by 1

![image](https://user-images.githubusercontent.com/31384149/229287870-86cc3380-ae02-458b-9648-285de85331e2.png)

I am aware of https://github.com/frzyc/genshin-optimizer/pull/1068 but drag clicking characters doesn't fundamentally resolve the issue that people want to rank their characters' artifact priority, and this worsens exponentially if you have 20+ characters you want to build and order in terms of priority

(as far as I'm aware it's a regression from https://github.com/frzyc/genshin-optimizer/pull/944)

**Comment by StainAE86** [comment]
If you understand how the current sorting system works it shouldnt be hard to locate your characters.

Firstly they're sorted by how many artifacts they currently have equipped.
So anyone with 5 artifacts will be sorted before those with only 4, and soforth.

After that theyre just sorted alphabetically by name.

The redesign of the use equipped system was to get away from applying a rigid priority list system to optimization and make users think more about who can take what, and under what circumstance. As such there is no need to create a custom "order" of the displayed characters in this list.

If you are having troubles quickly visually finding characters you can utilize the weapon and element based filtering at the top or the search box.

**Comment by Cynplytholowazy** [comment]
It's impossible to expect people to look for 20 different characters to disable when you are building so many of them. I get some people would swap artifacts between characters but this system redesign makes it way too time-consuming for people who don't want to swap artifacts and would want to stick artifacts onto certain characters and never have to swap again.

Please seriously reconsider this. I don't think this redesign helps sorting characters effectively, even though I can understand what the sorting system works.

**Comment by StainAE86** [comment]
Instead of pre-emptively going thru every one of your characters to setup a custom exclude/include list you could just leave all your low priority characters to 'not use equipped' and your high prio characters to always use equipped.

Then when an undesirable result occures you can just click the artifact in the build result to remove that character from the list and regenerate the builds.

No need to setup a full exclusion list if those artifacts were never going to be considered anyway.

![image](https://user-images.githubusercontent.com/101696552/229327435-53ee2558-e157-41c7-bf2a-848edde697ac.png)

**Comment by Cynplytholowazy** [comment]
Problem is all artifacts are considered until they are equipped. When you are building say the 15th character and beyond too many undesirable results come up and it's still the same amount of effort to manually disable. Besides, when importing database all characters have artifacts equipped. Enabling the "Not use equipped" would have excluded potentially better artifacts from lower priority characters that could have been used in higher priority characters (say swapping from around 20th to 10th).

A full exclusion list is still very much useful for prioritizing characters, as well as saving much time for trying to set up individual exclude list or ruling out undesired entries.

**Comment by nguyentvan7** [comment]
If you're planning to rebuild your whole roster like this, it sounds better to just mass unequip artifacts in the Artifacts page. The whole point of the removal of a strict list is for the user to be able to see and act on these artifacts that get picked for multiple characters. If you optimize in a straight list, you will never see these conflicts

**Comment by kazerniel** [comment]
+1 vote for this new system being a pain in the arse :/ The priority order menu was so much easier to update. Back then it was a single click for each rank change, now I have to open and edit each character one by one.

Could we maybe have an option to bring it back? As a sort of "simple mode"?
