### ISSUE TITLE
Most URLs on main page point to wrong page

### ISSUE THREAD

**Issue by Leanny** [frzyc/genshin-optimizer#1116]
Examples:
* The footer contains the text "Genshin Optimizer Version: [9.6.3](https://github.com//releases)" with the version pointing to the wrong URL
* Nearly all quick links dont point to the correct destination as well

Seems like [env vars](https://github.com/frzyc/genshin-optimizer/blob/master/apps/frontend/.env) are not set correctly

**Comment by frzyc** [comment]
Looks like an errand deployment. It should be resolved now.
