### ISSUE TITLE
Pathing to theorycrafting tab causes GO to crash on Nilou

### ISSUE THREAD

**Issue by mechalynx** [frzyc/genshin-optimizer#1143]
Pathing to theorycrafting while on Nilou causes GO to crash with "Unexpected Error". This is recent and did not start after any modifications on my part (changes to the character, artifacts etc. as far as I can remember). The other tabs seem to work fine. It doesn't happen with any other characters as far as I've tested (though I was under this impression earlier) and it doesn't happen to other characters that are missing some or all of their artifacts. The error text is this:

```
Message: can't access property "flower", Kd[e] is undefined
Name: TypeError
Stack: wf@https://frzyc.github.io/genshin-optimizer/main.a4935c6a5f42da64.js:125:7590658
h@https://frzyc.github.io/genshin-optimizer/main.a4935c6a5f42da64.js:125:270408
qs@https://frzyc.github.io/genshin-optimizer/330.03b54f95052c1e03.js:1:132716
ki@https://frzyc.github.io/genshin-optimizer/main.a4935c6a5f42da64.js:125:7674541
wr@https://frzyc.github.io/genshin-optimizer/main.a4935c6a5f42da64.js:125:7731523
pl@https://frzyc.github.io/genshin-optimizer/main.a4935c6a5f42da64.js:125:7720507
Ql@https://frzyc.github.io/genshin-optimizer/main.a4935c6a5f42da64.js:125:7720435
Cl@https://frzyc.github.io/genshin-optimizer/main.a4935c6a5f42da64.js:125:7720296
rl@https://frzyc.github.io/genshin-optimizer/main.a4935c6a5f42da64.js:125:7717439
Yo@https://frzyc.github.io/genshin-optimizer/main.a4935c6a5f42da64.js:125:7658382
al/<@https://frzyc.github.io/genshin-optimizer/main.a4935c6a5f42da64.js:125:7715040

```

This is my database file (the one that was active). My other databases do not have Nilou.

[main-copy_2023-04-17_15-47-34.txt](https://github.com/frzyc/genshin-optimizer/files/11252695/main-copy_2023-04-17_15-47-34.txt)

**Comment by PolomoPT** [comment]
![image](https://user-images.githubusercontent.com/121315943/232837159-fa2f1a6b-cf38-4f13-b261-59a95c4b4caf.png)
TC Tab artifact set has the old name, which got changed with #1126. 
This issue can no longer be encountered, so if you just use the altered DB:

**Comment by mechalynx** [comment]
Thankyou, it worked 👍
