### ISSUE TITLE
// in "Rainbow Builds" title

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1154]
![image](https://user-images.githubusercontent.com/101696552/233827662-f81c3c2c-12b0-46f7-ad35-788ac737deb1.png)
![image](https://user-images.githubusercontent.com/101696552/233827780-4596991a-4bb4-4c8e-bc22-d3af1c0aa862.png)

**Comment by vapopescu** [comment]
Also in the instuctions
![image](https://user-images.githubusercontent.com/14800198/233947825-83325d07-168a-4e5a-8957-6cd4058eb56d.png)
