### ISSUE TITLE
Baizhu C2 healing is probably incorrect

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1181]
The 20% multiplier is only applied to the percentage value and not the flat value of the heal. That is probably wrong, tho I guess it would be best for someone to verify

**Comment by littlef0x** [comment]
I can confirm that the 20% applies to both values.

E healing:
![图片](https://github.com/frzyc/genshin-optimizer/assets/32670075/21e3d464-06d2-4892-b074-94fe5a5d7c5e)

C2 healing:
![图片](https://github.com/frzyc/genshin-optimizer/assets/32670075/1b21df27-6843-4c03-8f5d-3f6914ca02d1)
