### ISSUE TITLE
Abnormal strings in artifact set configuration

### ISSUE THREAD

**Issue by littlef0x** [frzyc/genshin-optimizer#1192]
See Crimson Witch of Flames (artifact selection page in character optimization):
![图片](https://github.com/frzyc/genshin-optimizer/assets/32670075/bacf8c27-88b7-4969-9623-3d761f77c2b6)
![图片](https://github.com/frzyc/genshin-optimizer/assets/32670075/f3f7cd63-eba0-4e00-b30e-41207090c6ae)

There seems no problem with English language. So I assume it's an issue with translation.

**Comment by nguyentvan7** [comment]
<img width="209" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/36019388/34b306f0-0727-436f-b419-cd4818697414">
works fine for me. Try refreshing, or checking f12 -> console to see if the crimsonwitch translation json was blocked for some reason

**Comment by PolomoPT** [comment]
the translation wouldn't come from `artifact_CrimsonWitch.json`, but rather the pipeline... I feel like an issue like that would mainly if occur if GO is being run locally.

**Comment by littlef0x** [comment]
Thanks for your reply. I tried just now but could not reproduce this bug, lol (my computer has been restarted and the database has been changed since then, so it's not exactly the same environment now). Maybe it was a local issue. I'll let you know if it occurs again.
