### ISSUE TITLE
Multi-Optimisation

### ISSUE THREAD

**Issue by InvertedCreeper** [frzyc/genshin-optimizer#1208]
Hi there, I can't seem to be able to use the multi-optimisation feature. When I try to use it my desired stats just simply aren't there. What can I do to fix this? Am I using it correctly??

**Comment by D1firehail** [comment]
> When I try to use it my desired stats just simply aren't there.
The UI for multi-optimization is intentionally limited to prevent users from making nonsensical targets out of a lack of understanding. What specifically are you trying to do?

**Comment by InvertedCreeper** [comment]
I'm trying to get the maximum attack and em for Tighnari

**Comment by D1firehail** [comment]
And for what purpose?

**Comment by InvertedCreeper** [comment]
I want a balanced build

**Comment by D1firehail** [comment]
Good thing it didn't let you, you're working with a big misunderstanding of GO as a tool, how the damage formula of the game works, or both. 

You don't care about attack or EM. You care about the resulting damage. It's rare for a "basic stat" like ATK, EM, HP or crit to be relevant as an optimization target (either on its own or as a multi-optimization target). 

What you should do is either find a multi-opt target someone else has made or make your own, where the amount of each source (non-reaction clusteerbloom arrow, spread clusterbloom arrow, non-reaction burst, spread burst, maybe bloom etc) correspond to what they actually would be in the scenario you care about. Maybe that scenario is one rotation, maybe it's one rotation with reactions and one without, maybe it's something else.

Here's a video guide on the basics on the Multi-optimization target feature https://www.youtube.com/watch?v=j6Y1dZwb1sY&list=PLcVsEMZO5IVFQdeh8zteZwiNchObfQ684

**Comment by D1firehail** [comment]
What info do you mean?

**Comment by InvertedCreeper** [comment]
What it would be in the scenario

**Comment by D1firehail** [comment]
Mostly a combination of game knowledge and knowing what it is you want to do with the build

**Comment by Sinesthesia** [comment]
There are many various guides online for many characters but you still need to know what you're doing in the game to get better results. There is no singular magic button because it's all very vague and situational. To get something that is close enough you will need to find or build a multi that fits _your_ situation.

**Comment by D1firehail** [comment]
You still need a decent amount of game knowledge to tell if a target is a close enough match to what you're trying to do. There's no guarantee anyone has made and/or published a multi-target for any particular goal/scenario, or if they have that the target is actually realistic, but as a starting point for finding pre-existing ones:

Some Mains communities have resources for their characters.
The GO discord has a channel for community-made targets.
KQM has a pretty large collection of targets in [this document.](https://docs.google.com/document/d/12hrPJ3MrAF7t03gyiiVtV5uI_rUKlVlbEwl9Lf2esIQ/edit?pli=1#heading=h.hl6ovmw8fzjs)
