### ISSUE TITLE
Add ability to create an artifact from the artifact select screen on a character

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1252]
Being able to create artifacts on a character's overview page the way you can do it with weapons already. Especially useful when I find don't actually have the artifact and don't care about their stats but just want to quickly create a set for a 4TOTM or 4DW holder for example

![image](https://media.discordapp.net/attachments/1124254397132713984/1125011955799826560/image.png)

**Comment by arquelion** [comment]
Now that this UI has pagination, should the new artifact button still go in that empty space by the artifact filters or should I place it between the page selector and the artifacts grid? The new item button is located below the pagination/sort option stuff in the weapon swap UI as well as the the artifact/weap/char pages
