### ISSUE TITLE
Modules cannot be imported by `vite` and `webpack` simultaneously

### ISSUE THREAD

**Issue by lantua** [frzyc/genshin-optimizer#1264]
Currently, the `webpack` and `vite` modules directly import the source code. Therefore, whenever a module `A` of either type imports module `B`, the source code of `B` must conform to the module `A` configuration.

This poses two problems.
1. If module `A` configuration is more restricted than module `B`, then the compilation may fail, and
1. If module `B` queries an env variable, it needs to use the method compatible with module `A`.

For the first problem, we can ensure that all `libs` modules are more restricted than `apps` modules, which is currently the case (at the time of writing).

The second problem is trickier because the `webpack` uses `process.env['NODE_ENV']` to access runtime env, while `vite` uses `import.meta.env.*`. The two methods are incompatible, so any module imported by both `vite` and `webpack` modules cannot query the env variable. Conversely, any module intended to do so will be locked to either `vite` or `webpack`.

**Comment by nguyentvan7** [comment]
https://discord.com/channels/785153694478893126/819643218446254100/1171934532899971172

We should add a config that consumer can set on the calc object that specifies logging level or if its in development mode, etc. This will allow us to be framework agnostic
