### ISSUE TITLE
Allow pinning any build from the calculated build list

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1283]
It would be nice to pin any build that is calculated so you can easily compare builds with different setups.

For example, when optimizing a character A that is taking some artifacts from character B, you could first optimize for A without taking from B, then pin that build. Then optimize for A while allowing to take from B and then compare the top build here with the pinned build from earlier.

Currently I just take screenshots or write down numbers, but this would be more convenient

Something even cooler would be keeping the "context" of the build, for example, any conditionals or weapon changes, so you could more easily compare builds that differ in things other than artifacts

**Comment by frzyc** [comment]
obsolete now with Team/loadout feature
