### ISSUE TITLE
Deprioritize the weapon page somehow

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1296]
The weapon page is largely not needed, and creates confusion for new users who think they need to import all of their weapons before optimizing. The better flow for a user is to add their artifacts, which creates their characters. Then they can open the character page and change the weapon there.

In addition, you cannot change conditionals in the weapon page, making it possible for users to set their weapon there, and not see the weapon conditionals in the overview tab. We should consider removing or deprioritizing this page so users don't think it's a part of the core workflow

**Comment by StainAE86** [comment]
Could look into reworking the weapon page when weapon optimization becomes a thing :)

**Comment by frzyc** [comment]
Will be obsolete when weapon optimization is implemented.
