### ISSUE TITLE
New Optimizer Tab Detected triggers issue

### ISSUE THREAD

**Issue by fdv** [frzyc/genshin-optimizer#1306]
Reproduced on both 

- Brave v1.59.120
- Safari 16.5 (18615.2.9.11.4)

How to reproduce:

- Browse GO
- Do things
- Close tab / use tab to browse somewhere else
- Come back to GO, from initial or new tab
- New Optimizer Tab Detected

Won't go until I quit the browser and come back.

Also: 

- Browse GO on Safari / Brave
- Do things
- Close tab / use tab to browse somewhere else
- Open GO on the other browser
- New Optimizer Tab Detected

Won't go until I quit both browsers and come back.

**Comment by nguyentvan7** [comment]
Do you have any extensions installed? Can you reproduce in an incognito window?

**Comment by fdv** [comment]
Good catch. Though I had disabled all my extensions but there was one left. The issue comes from ProWritingAid, a spelling and grammar checker. As soon as I disable it, things are working again.

Thank you for the heads up.

**Comment by frzyc** [comment]
@nguyentvan7 This is not the 1st time this happened. Maybe we can create a new work task where we narrow down the trigger for tab detection (currently checks for any external db changes, but maybe should narrow it down to external db changes in entrys that GO uses)
