### ISSUE TITLE
I only have 1 tab open?

### ISSUE THREAD

**Issue by Endez1a** [frzyc/genshin-optimizer#1308]
![Screenshot 2023-10-21 121154](https://github.com/frzyc/genshin-optimizer/assets/95069700/f68d6970-097e-4f66-81ca-f168ee2cef00)

**Comment by nguyentvan7** [comment]
Do you have any extensions? Some extensions seem to cause this issue

**Comment by Endez1a** [comment]
i do have some extensions but i paused them all and nothing changed so i dont think they're the problem

**Comment by fdv** [comment]
I had the exact same issue a few days ago, culprit was Pro Writing Aid extension.

Can you give us your browser version, and try to reproduce in anonymous mode?

**Comment by Endez1a** [comment]
OHHHH PRO WRITING AID- I HAVE THAT-
