### ISSUE TITLE
Add a quick-add "Blessing of the Abyssal Moon" modifier to "Enemy Config + Bonus Stats" page

### ISSUE THREAD

**Issue by ScorelessPine** [frzyc/genshin-optimizer#1316]
As the title states, it would be nice if there were a button in the Enemy Config + Bonus Stats page that automatically adds the modifiers from the current Blessing of the Abyssal Moon, for example the current Coalescing Moon buffs alter Normal and Charged Attack Crit Rate, so for the duration of this Abyssal Moon, the button would add the modifiers "Normal Att. CRIT Rate Bonus" and "Charged Att. CRIT Rate Bonus" defaulting to the max stacks available for this moon of 30% (6% per stack, max 5 stacks). 

Another example would have the previous Abyssal Moon's buff having the button adding a modifier of elemental damage bonus with a default of 20% (I'm not sure if that's what Common Damage Bonus is used for, but perhaps that would be the right one to use in this case).

Potential downside is that this would result in constant necessary maintenance to make sure the current Blessing of the Abyssal Moon's buff is accurate on the 1st/15th of the month. It would probably be hard if not impossible to fully automate, since choosing the correct buff to apply would probably require a person to read and parse the information.

**Comment by frzyc** [comment]
I think you've hit the nail on the head of why we don't support these "quick-add" feature. We have very limited time, and I would advocate to spend dev time in more self-sustainable features. Thanks for the suggestion, but I don't think we will be implementing this in any capacity.
