### ISSUE TITLE
Talent level is not clamped when updating character ascension

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1440]
https://discord.com/channels/785153694478893126/1195110729917939773
![image](https://github.com/frzyc/genshin-optimizer/assets/36019388/6e1f6c5f-7685-4cba-b03a-fa9da2490612)

**Comment by notV3NOM** [comment]
@nguyentvan7 Please review https://github.com/frzyc/genshin-optimizer/pull/1454
