### ISSUE TITLE
1 star weapons show NaN as a secondary stat

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1441]
![image](https://github.com/frzyc/genshin-optimizer/assets/36019388/b15f1a51-44f7-4777-b2bd-69798929b6ad)
https://discord.com/channels/785153694478893126/1145686734990999593

**Comment by notV3NOM** [comment]
@nguyentvan7  Please review https://github.com/frzyc/genshin-optimizer/pull/1452
