### ISSUE TITLE
Yoimiya's Firework Flare-Up normal atk. dmg doesn't change when Vaporize or Melt is toggled

### ISSUE THREAD

**Issue by takiminada** [frzyc/genshin-optimizer#1479]
As title says. The damage number doesn't change when toggling Vape or Melt. Nothing changes this, teammates, buffs or artifact sets/requirements.

**Comment by nguyentvan7** [comment]
You need to enable her infusion on the Talents tab. Optimizer does not assume her infusion is enabled by default
