### ISSUE TITLE
Make Constellation toggle more button-like

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#1503]
![image](https://github.com/frzyc/genshin-optimizer/assets/1754901/28da6dc7-c800-4002-8b56-1845dc4900fb)
The condensed constellation toggle does respond to mouseover, but are not very button-like. 
Could experiment with wrapping in outlined button or something.

**Comment by AnukratiMehta** [comment]
@frzyc I'd like to work on this. Please assign.
