### ISSUE TITLE
Deleting a DB doesnt work the first time

### ISSUE THREAD

**Issue by eeeqeee** [frzyc/genshin-optimizer#1520]
> also theres a bug where a character wont delete from the db. can recreate in a fresh db like so:
create a character
create a team
create a tc loadout
swap to the tc loadout
go to the settings page and delete the db

> that character wont get deleted

https://discord.com/channels/785153694478893126/1200154094476734556/1210550752272195645

**Comment by frzyc** [comment]
No longer reproduceable.
