### ISSUE TITLE
"Sands of Eon" Artifacts Display HP Substat Instead of HP%

### ISSUE THREAD

**Issue by Bag-senpai** [frzyc/genshin-optimizer#1528]
![image](https://github.com/frzyc/genshin-optimizer/assets/90940695/750b9e92-a01b-47c1-9d56-9c9fd99c5ae0)
Title is self-explanatory, which can also be the reason why scanner can't read or verify the image containing the said substat.

**Comment by StainAE86** [comment]
It is impossible to have HP% as a substat when HP% is the main stat.
