### ISSUE TITLE
Team Page sorting

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#1532]
Allow sorting on the team page by "recently edited" and "name (Alphabetical)

Add a way to favorite teams, which is the main way to "group" teams

**Comment by StainAE86** [comment]
Mock up idea:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/7ba1e9ea-9f30-4de3-84d5-c35f57b7833e)

**Comment by StainAE86** [comment]
Could also do some interesting filtering with the Elements:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/1dcedeb9-f8f2-45f9-b64e-d4585244b400)

Leave them all on for teams of any composition.
Or select the elements to display those team types, eg; if you want to see a Hu Tao, double hydro with Zhongli team you would only turn on Pyro, Hydro and Geo. And that would also show a Yoimiya, Xingqiu, Yunjin, Zhongli team

**Comment by HassnHamada** [comment]
I think this filter would be too general. Another approach would be to filter based on character(s).

So if someone chooses Furina, they will get any team with Furina in it.
If they choose Furina and Xiao, they will get any team with both Furina and Xiao in it.

As for the implementation, I imagine it will lock something like the "Artefact Sets" drop-down menu in the artefacts page.

**Comment by nguyentvan7** [comment]
Yep I believe the plan is to add a character filter in exactly the manner you described

**Comment by frzyc** [comment]
> Could also do some interesting filtering with the Elements: ![image](https://private-user-images.githubusercontent.com/101696552/307596143-1dcedeb9-f8f2-45f9-b64e-d4585244b400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4OTA0OTMsIm5iZiI6MTcwODg5MDE5MywicGF0aCI6Ii8xMDE2OTY1NTIvMzA3NTk2MTQzLTFkY2VkZWI5LWY4ZjItNDVmOS1iNjRlLWQ0NTg1MjQ0YjQwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQxOTQzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGYyYWU0OGM3MDE0ZmVkMjZkOTIxNzY5NjY2YTllMTFlNmNlZGI1ZjM4NmRlOTE5ZWNjOTQyZGQ1NDYwNWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c7PzFNXtAU3Oz1mb-132aNRZMxr6UvvsJ_wMQEw46O4)
> 
> Leave them all on for teams of any composition. Or select the elements to display those team types, eg; if you want to see a Hu Tao, double hydro with Zhongli team you would only turn on Pyro, Hydro and Geo. And that would also show a Yoimiya, Xingqiu, Yunjin, Zhongli team

This seems to be a suggestion more appropriate for https://github.com/frzyc/genshin-optimizer/issues/1526. But on the outset I don't think it is very initituive to group teams by elements, because it can be ambiguious whether that means resonance or character element.

**Comment by StainAE86** [comment]
> because it can be ambiguious whether that means resonance or character element.

Isn't that the same thing in this case?
