### ISSUE TITLE
UI update issue when toggling damage

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1538]
https://discord.com/channels/785153694478893126/1200154094476734556/1211158474092711956

Build generated for Pyro damage:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/e38e4fc0-7503-460a-8125-e602eb3daf0b)

Toggle to Vape damage and values are very wrong:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/bde3ca31-f327-4036-b644-a35f40f66957)

Leave tab and return, values now updated correctly:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/39d829b9-2a8f-4b5a-bc2c-fd339c63a00c)

**Comment by frzyc** [comment]
This is likely an issue where one of the `useTeamData` hook isnt being triggered when the `TeamCharacter.reaction` is being toggled. needs investigation
