### ISSUE TITLE
Clear previous query from searchbox when adding subsequent characters

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1541]
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/c44eac92-4e86-427a-a0e0-921772292a29)

**Comment by HassnHamada** [comment]
I need some clarification on this.

From my understanding, the query textbox should be cleared after someone adds a character.

What about the case where someone starts typing, then closes the window or clicks out of its border -may be unintentionally-. Should the query textbox also be cleared?

**Comment by nguyentvan7** [comment]
Yea I'd say just clear it every time it's opened, it'll be simplest

**Comment by frzyc** [comment]
A easy way to implement this would be to set the modal to `keepMounted=false` https://mui.com/material-ui/api/modal/

**Comment by HassnHamada** [comment]
I saw your comment too late. I just reset them manually when the window closes. I'll check your solution now.
