### ISSUE TITLE
Indication of how many team members are applying buffs

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1542]
Would be nice to have a indicator to the right of the team buffs tab showing how many of the team mates are providing an active buff. could be a orange [0] if there are no team mates / or the present team mates dont have their conditionals turned on. and then [3/4] if one of the team mates isnt providing any buffs at all. or [4] if all team mates are providing some kind of buff

![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/a096be52-70d8-40c4-a12f-39ad23ea0c8d)

**Comment by frzyc** [comment]
Needs more thoughts here, the number here is very context dependent, and I am not sure if this number shows too little information, or the color is trying to do too much. Ultimately you want an indicator to show how many teammembers are applying buffs, but I am not sure if this solution is the way to do it.

**Comment by frzyc** [comment]
Should no longer be necessary now there is a general team overview via https://github.com/frzyc/genshin-optimizer/pull/1632
