### ISSUE TITLE
Allow exporting/importing and clearing the bonus stats independent of the team/loadout

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1543]
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/7b38b9c1-63d8-4a32-9f14-422efca3edfd)

Usecase; instead of recreating them manually, or duplicating a team and then changing characters inside it to keep the "abyss or "event" buffs youve configured; create them once and then copy/export and paste/import them into another team, or share your buff settings for a limited time event to another user so they can apply it to their team.

**Comment by frzyc** [comment]
I don't believe this(exim of bonus stats) is easier than just entering a few numbers, this just creates clutter in the UI for a niche usecase, and makes the code here much more complicated to maintain.
