### ISSUE TITLE
Split "Enemy Config" and "Bonus Stats"

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1545]
Suggest having the "Bonus Stats" apply to the inidividual Loadout rather than the entire Team.
The "Enemy Config" can apply to the entire Team, and propergate down to all Loadouts within the Team since this is a "world" setting, rather than a "situational" setting. 

That way you can account for the following situation: 
You have an Ayaka freeze team that you use for both Overworld/domains and Abyss.
So you want to create 2 loadouts for that same team; "Overworld" and "Abyss",
The "Abyss" loadout you want to have the crit buffs in the Bonus Stats (CR+8 CD+15).

But with the current implentation these buffs are saved to the Team, not the Loadout.
So you'll have to add and remove them every time you edit your Overworld and Abyss loadouts.

**Comment by StainAE86** [comment]
Relavent to #1525

**Comment by frzyc** [comment]
Bonus stats is applied to the individual loadout, and the enemy is applied to the entire team. This is how it is implemented in Team loadout right now.
<img width="928" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/1754901/bd3bcf6d-0542-46ca-845d-b39e072bbd2b">

**Comment by StainAE86** [comment]
I suggest you test this. Because this is not how it works in the current Beta. If you change the bonus stats in one Loadout, it changes it in all Loadouts with that Team.

**Comment by frzyc** [comment]
Hmm, then it might be a bug
