### ISSUE TITLE
Add relic viewer UI

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1549]
- [x] Add `RelicCard` in `libs/sr/ui`, it just needs to display the stats of the Relic
  - Van did this already
- [ ] Add `RelicInventory` component in `libs/sr/ui` that renders all Relics in DB using `RelicCard` in a Grid
- [ ] Add some pagination to above (look at GO code for inspiration)
- [ ] Figure out a place to put this (Van will decide/help with this)
  - [ ] For testing, we can just put it on the main page

**Comment by EuEric** [comment]
Hello 🙋‍♂️👋 could you assign this task to me?

**Comment by ClintonEmok** [comment]
Hello could you assign this to me instead. I took over from my friend.
