### ISSUE TITLE
Add light cone viewer UI

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1551]
- [ ] Add `LightConeCard` in `libs/sr/ui`, can take inspiration from `RelicCard`, it just needs to display the stats of the lightcone
  - Van might need to help here for calc-related stuff
- [ ] Add `LightConeInventory` component in `libs/sr/ui` that renders all light cones in DB using `LightConeCard` in a Grid
- [ ] Add some pagination to above (look at GO code for inspiration)
- [ ] Figure out a place to put this (Van will decide/help with this)
  - [ ] For testing, we can just put it on the main page

**Comment by ruxache** [comment]
heyy, can i be assigned to this issue?

**Comment by EuEric** [comment]
Hey, can I be assigned this instead, my friend took the task that was assigned to me, so we switched a bit
