### ISSUE TITLE
Conditionals and Optimization settings aren't being saved per Loadout

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1561]
As per title. They're being applied globally to the Team. Example:

Setup a Loadout for "Cryo" Kaeya, with his C1 active, Cryo Goblet, 140% ER and only 4PC Blizzard Strayer:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/af149775-fc69-4ad4-bfcc-5d6feb39e1a3)
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/c8baa567-c8f2-4d71-9c4e-15484e51ac08)
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/47a5bb80-8b3b-41a9-ae00-784c2ef5a9a1)

If you then create a second loadout for "Physical", turning off C1, Changing to Phys Goblet, removing the Constraint and enabling more artifact sets:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/5d15a337-868e-419a-b53b-009bc64a9038)
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/4f0535b1-4ed5-49da-be29-07d8827216af)
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/4e9f7be8-4952-4638-b5c5-423d96c2ad17)

And then swap back to your "Cryo" loadout, all the settings retain the changes you last made to suit the "Physical" loadout because they're following the global "Team" setting, rather than the "Loadout":
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/ca7d2551-7b2b-448c-9c1b-b90f4a2b4aad)
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/e736642b-01bc-4e68-b681-519b95f2f061)

It is only the artifacts that are being saved to the loadout.

Likely the same bug as this:
https://github.com/frzyc/genshin-optimizer/issues/1545#issuecomment-1963092351

**Comment by frzyc** [comment]
Yes, that is part of the design. Please read the [design doc](https://docs.google.com/document/d/1jv1Of3adFnJuJajgfYZCmBz3_ff06xSnFOhbzh4eym8/edit). 
<img width="863" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/1754901/528d340a-d08c-410e-8c29-ee40ad05700c">
If you have a different context for a character, create a new team with a new loadout.
