### ISSUE TITLE
Artifact Filter UI redesign

### ISSUE THREAD

**Issue by ineedanamepls** [frzyc/genshin-optimizer#1569]
Reorganizing the UI including a few optimizations like:
- Depending on what someone selects in the slot toggle group we could restrict the options in the main stat drop down menu.
- Fixing the issue in https://github.com/frzyc/genshin-optimizer/issues/995
- Anything along the way 🫡

![Artifact Filter Alternative](https://github.com/frzyc/genshin-optimizer/assets/79713598/45f9b2ff-b157-4ee4-a8a4-4996fb4e4bf9)

I will work on this slowly, if someone wants to see this change sooner feel free to get it before me. For any questions just pop a comment.

**Comment by StainAE86** [comment]
If you're redesigning the filters theres some ideas in here #1205

**Comment by frzyc** [comment]
> If you're redesigning the filters theres some ideas in here #1205

We should narrow scope for this issue to only the UI redesign, and no system changes as all the suggestions in #1205.
