### ISSUE TITLE
"Add Team" button within the Edit Character popup does not appear if no teams exist for a character yet

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1579]
Only team configured:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/715c65a1-df04-4cc5-922d-d211a0d22cde)

Kazuha is a member of that team so within his popup it shows, along with the "Add Team" button.
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/eb45bfbc-e843-4b76-95a1-77ddba14caa1)

Since Yae doesn't have a team yet, the button does not appear:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/bba20ffd-76b6-48b6-84a8-06fd6a4eb834)

**Comment by frzyc** [comment]
Hey @kasantos2, since this relates to your PR https://github.com/frzyc/genshin-optimizer/pull/1568, do you mind taking a look?
