### ISSUE TITLE
Bug with team swapping logic

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1580]
Attached simple test database.

To reproduce follow these steps:
1) Click Sara within the Raiden Team
This opens the Raiden Team with Sara as the selected character (working as expected)
2) Click EDIT to open Sara's popup (character editor)
3) Click Sara within the Sara Team (in the teamcard)
This opens the Sara Team, but Raiden is the selected character (unexpected result)
4) Click EDIT to open Raiden's popup (character editor)
5) Click Raiden within the Sara Team (in the teamcard)
The re-opens the Sara Team, but Sara is the selected character (unexpected result)

[Database_2_2024-02-29_08-10-30.json](https://github.com/frzyc/genshin-optimizer/files/14444861/Database_2_2024-02-29_08-10-30.json)

**Comment by frzyc** [comment]
@HassnHamada Since you did the teamcard interaction in https://github.com/frzyc/genshin-optimizer/pull/1567, can you take a look?

**Comment by HassnHamada** [comment]
OK 👍
