### ISSUE TITLE
Modify behavior when creating a New Team from the character editor

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1583]
Currently if you click "Add Team" from within the character editor you are presented with this:

![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/e9c541e7-b8fd-40bb-914f-e038e94738f2)

Default name is "Team Name" and it skips the character selector popup.
As you can no longer add team mates via the Team Buffs tab this now requires an additional page to navigate to complete the workflow of creating a team and getting an optimization result.

I suggest doing the following:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/935a89ad-7c7d-423a-9806-817833f232f5)

After clicking "Add Team" it creates the new team but forcefully opens the Team Settings popup so you can start adding additional team members straight away.
And the default Team Name is: "Character Name" Team

**Comment by frzyc** [comment]
Here is the firm requirements:
- When creating a new team from the character editor, allow the `navigation` to pass a prop to open the team settings popup.
- No changes to default Team Name(will be addressed by something else)
