### ISSUE TITLE
Add an indicator to an artifact in an optimized build if it is the same as the current build

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1593]
![image](https://github.com/frzyc/genshin-optimizer/assets/36019388/5269dfb2-442e-4b5b-9714-fa5b93d1edc2)
This currently only shows where the artifact is equipped. We could add an outline or a small Chip to indicate it is the same as the current Build

**Comment by nguyentvan7** [comment]
![image](https://github.com/frzyc/genshin-optimizer/assets/36019388/7964792c-bea2-47cc-9d56-98ef5a069bbe)
It would also be nice to add an indicator here, below the location

**Comment by frzyc** [comment]
Resolved by https://github.com/frzyc/genshin-optimizer/pull/1657
