### ISSUE TITLE
selected build description info icon not hoverable

### ISSUE THREAD

**Issue by Godlander** [frzyc/genshin-optimizer#1598]
the icon is not hoverable on the active build

![image](https://github.com/frzyc/genshin-optimizer/assets/16228717/8c22a5f8-5606-47ef-b8d6-0414a786321d)

on an inactive build, it is hoverable and shows the description

![image](https://github.com/frzyc/genshin-optimizer/assets/16228717/3d44b00b-0016-4c21-9122-647c21c04a77)

**Comment by frzyc** [comment]
Fixed after converting the element to a button.
