### ISSUE TITLE
Albedo -- Split Scaling

### ISSUE THREAD

**Issue by lathertonj** [frzyc/genshin-optimizer#16]
Since Albedo's damage comes from DEF for his skill and ATK for his burst, someone might want to sort artifact sets by some weighted combination of the two. I wonder if this [calculator](https://docs.google.com/spreadsheets/d/1Do2gjZ7dqjFMsYnND-tVqfV0I3ofWayhI5bm6BbGIgE/edit#gid=0) might be of inspiration? (Linked from [this guide](https://keqingmains.com/full-albedo-guide/).)

**Comment by frzyc** [comment]
I am not sure why ultimately you would want to sort artifacts like this, since the main use-case for you to find optimal artifacts for a character is through the build system. I would not want to implement/support a complicated filter like this, if its not useful once albedo is added. I would advice you to be patient, the albedo page is already under works.

**Comment by lathertonj** [comment]
Sorry for the misunderstanding. My intention was to discuss the "sorting" aspect of the build system. Currently, for a character like Xiao, it's straightforward to sort artifacts by what maximizes, say, his plunge damage, because that's where the majority of his damage comes from. But, for a character like Albedo, his damage will be maximized by considering how many times his skill will hit an enemy in a given cycle, plus how many times his burst will go off. For different team compositions, these might be different amounts -- for example, in a quickswap team, you might want 5*skill + burst, but in a Xiao team, you might want 10*skill + burst because Albedo will not be using his burst off cooldown. And, you can't just sort by the skill or the burst by themselves, because one scales with ATK and the other scales with DEF.

I understand the Albedo page is in progress! I was only trying to provide a suggestion that might help with it. I'm also happy to look at your source code if that helps.
