### ISSUE TITLE
Deleting the associated loadout of a solo character team leaves an empty team

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1604]
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/a89ac776-b092-44b9-809a-339589aa5137)

Same thing happens if you create a new team, but then close the "Team Settings" popup.

Perhaps add a message here saying "Please add an Active character to this team":
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/d8f4196a-78b4-410e-84ee-13ebf6259af1)

Or since the team is only holding enemy data at this point - perhaps the default option should be to delete an empty team automatically?

**Comment by frzyc** [comment]
I think it is fine to have empty teams, I am not really inclined to automatically delete the team, since the user might have entered name/description that they don't want to lose
