### ISSUE TITLE
Disable individual artifact swapping in `CompareArtifactModal`

### ISSUE THREAD

**Issue by arquelion** [frzyc/genshin-optimizer#1616]
Since an optimal build for a set of criteria is defined by a combination of weapon and a specific set of artifacts, it doesn't make a whole lot of sense to cherry-pick individual artifacts from the generated builds over saving/equipping the whole build. Artifact swapping in this UI should be disabled.
![image](https://github.com/frzyc/genshin-optimizer/assets/47800040/549aa7a9-6c60-4c2c-ab7f-aa537935be7b)

The rest of the UI is still useful for artifact inclusion/exclusion and management (i.e. generated build uses an artifact that the user no longer has) as well as comparing artifact differences between a generated build and a currently inactive build and should otherwise remain intact. However, equipping functionality should be handled entirely by the "Equip Build" button.

**Comment by frzyc** [comment]
@arquelion do you mind splitting out item 2 as a separate issue? then your PR #1618 can resolve this issue.

**Comment by arquelion** [comment]
Done
