### ISSUE TITLE
Change migration naming structure

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1617]
Suggestion to change this:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/03ff4d20-a09e-4b5f-b7ce-b46de282744d)

To this:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/82b3f807-6652-4ca3-9d0e-82188597cfee)

**Comment by frzyc** [comment]
I think this is a good idea, but the issue is that the migration happens on the database side, which has no access to the translation or character name system. I think it would be prohibitively difficult to pipe that data in, just for this one case of migration.

**Comment by nguyentvan7** [comment]
It doesn't look like you need any translation here. Just use the CharacterKey instead of the full name and its the same effect

**Comment by nguyentvan7** [comment]
Stain's ask was:
"Loadout Name" -> "<Character> Team Loadout"
"Migrated from <Character>" -> "<Character> Team"

**Comment by frzyc** [comment]
I guess we can use the character key then.
