### ISSUE TITLE
Improve team page UI

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1642]
Currently very busy at the top of the page making it hard to visually tell the difference between buttons.

Removing the long blue bar to edit the team composition/name and replacing it with a config/cog button and utilizing this place to provide "team" resonance information as well looks neat:

Can do the same with the Loadout name too, just to break up so much of the light blue.
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/40536268-2cef-4ed6-9e75-b7143569bdf5)

Similar to: https://github.com/frzyc/genshin-optimizer/issues/1606#issuecomment-1975021661

And: https://discord.com/channels/785153694478893126/1197612863557222450/1215531679779651605

**Comment by StainAE86** [comment]
In an attempt to tidy this top section of the page the following issues were also raised:

#1644 
#1645 
#1646

**Comment by frzyc** [comment]
My opinion is that the primary concern seems to be how overwhelming the cyan color the buttons are. A easier solution could be to convert the buttons to a "outlined" button to reduce the presence of color from "filled" buttons

**Comment by StainAE86** [comment]
My concern with that is it would require a full UI theme overhaul which probably isnt scoped for the same release as the teams feature.

And also making the buttons less overwhelming might actually backfire and make it harder to determine the difference between a "button" and a "title" or "description"
