### ISSUE TITLE
Add element context to team card

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1643]
I realised that there is no element context to this UI. Other than the user knowing which element each character is.

Could also add the ability to enter the team configuration directly from this card so users can edit the name and description without first entering the team itself (this will be a huge QOL on first migration when people have 60+ teams they'll have to manage/name/edit)

And then it would allow quickly modifying the team composition too.

![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/f89d51f3-463b-432d-a8a2-1d199c422290)

**Comment by frzyc** [comment]
I don't think this is important enough to put into this UI, I'd even argue that the bottom 3 buttons should be moved to the team UI, character card should be here to show the team, and not to have all these extra features.
