### ISSUE TITLE
Allow clicking the title space of team card

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1647]
Suggest being able to click the "Yellow" area here to take you to the Overview Tab of the "on field"/"active" character.

But if you click the "Green" area (ie; a specific character picture) it takes you directly to the Optimize Tab of that character.
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/2b2bbc68-ceca-4c3a-a11f-b39e50287f50)

**Comment by frzyc** [comment]
To narrow down scope:
Allow clicking of the team name in the Team card to access team UI.
