### ISSUE TITLE
Add character limit to Team/Loadout/Build names

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1648]
Could be a hard limit, or a soft limit that simply truncates the name with "..." at dynamic point where the UI wraps depending on the user's device. To prevent this:

![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/8826a790-3f9d-4100-af3a-a38e72df0c85)

![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/e1d74dad-8ab1-4927-997d-ade950563690)

![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/bb0946d0-0739-45da-a4f0-ae78f1d9f20c)

**Comment by nhanaa** [comment]
Hi, can I take this issue? @StainAE86 @frzyc

**Comment by frzyc** [comment]
Sounds good. I'd say something like 300 characters for titles, and showing maybe first 100 character before truncating.
