### ISSUE TITLE
Update Team Card Character Hover

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1649]
Currently the "Export" and "Duplicate" function is best kept within the context of the team/character/loadout, rather than here.
It provides limited use in this UI.

Suggest instead adding the "Settings" icon (like suggested in #1643) to allow users to rename their Team or even edit anything from this potential feature instead: #1644

![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/9df5f835-7e4c-4bc4-b8e3-2f252f8a3c66)

And add context to how many builds exist for each of those characters within that team, since this information is arguably more useful in this "overall" view of all the teams on a user's account.

It also provides more "empty space" to click if this feature is added: #1647

**Comment by frzyc** [comment]
To narrow down scope:
 - Currently, the hovering on the team card, the character card shows character + equipped build
 - change the hover on the team card for characters to show loadout info:
   - loadout name, # of builds
   - general character info like current behaviour
   - active build
