### ISSUE TITLE
Allow editing Loadout Name and Description from a Character page

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1684]
![image](https://github.com/frzyc/genshin-optimizer/assets/36019388/9dcc4a4e-7898-457f-b877-8eb9aef6ccf8)
Adding an edit button next to the duplicate/delete buttons here would allow users to rename their loadouts (especially auto generated ones). The view of the teams helps to provide context as to what a loadout name should be

**Comment by frzyc** [comment]
Need to think about perhaps adding a full loadout editor here, so a popup showing more relevant loadout information without cluttering the char editor UI here. This should provide more information to the user on the context of the loadout as well. 

- name/desc editor
- manage btns (dup, remove)
- opt target
- bonus stats
- builds (accordion)
- teams (add new team btn)
