### ISSUE TITLE
Not easy to figure out how to delete a team

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1687]
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/96dcbfde-ef21-409c-8931-710d41d30383)

Suggest adding delete icon here, and within the teams page.

It feels very hidden being under Team Settings. Takes many clicks to find it.
This has led to many users deleting the "Loadout" by mistake and losing their Multi-Targets and Opt settings.

**Comment by frzyc** [comment]
This team UI doesn't show enough information to allow user to safely delete a team, and the addition of this information would clutter up this UI. 

Since the addition of an additional delete button will also be in the same space as the Loadout deletion button, a user will have to make an extra effort to parse which delete button does what.

**Comment by StainAE86** [comment]
I just have to say both these reasons are not valid in my opinion.

1) deleting a team is not a very destructive action. All that is lost is the name/description and enemy data.
So talking about "safely" deleting a team doesn't hold any weight to this arguement.

2) only having 1 delete button on a UI that is already confusing as it makes it HARDER to figure out what the purpose is.
Users are already struggling to figure out what a "Loadout" is and what a "Team" contains. Users are wanting to delete unrequired "Teams", but because the function to delete a "Team" is nested so deep within pages/popups they can't find it.

If there were mutiple delete buttons on this screen it would actually increase understanding rather than them making a potentially incorrect (and very destructive) assumption about the purpose of the only delete button they see.
