### ISSUE TITLE
Team Setting Character click nav

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1688]
Suggest making these clickable and open the Teams Setting popup:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/3db066a7-6342-45c4-bc7b-a9f40e84bb82)

And making the character cards be clickable that will close the popup and load that characters's tab
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/830f885e-71a2-4419-bb3e-b1d19374cfc5)

**Comment by nguyentvan7** [comment]
We can do the 2nd one. not the first one anymore, since team settings is already in that row
