### ISSUE TITLE
Browser does not scroll up when navigating to a new page

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1690]
Situation: I'm scrolled half way down my Characters page. Opened the character Overview, scrolled down to see the Loadouts.
Then clicked Ganyu to open that Team on Ganyu's tab:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/f0e9ac36-e5a8-48eb-93a6-14ada92187db)

And it opens Ganyu's tab towards the bottom of her page:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/96b2a1bf-5046-4e05-a52f-1eb5b08f9b38)

Meaning I now have to scroll back to the top to access the Team/Loadout/Build settings, etc.

**Comment by nguyentvan7** [comment]
Seems fixed
