### ISSUE TITLE
Add AND filtering to teams page

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1691]
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/14e5aac4-cd5c-4fef-b7bd-887b896ddb25)

Currently the filtering is OR based. I think it would also be helpful to be able to narrow teams down by members.

EG: toggle between showing all teams with Xiangling AND Bennett / all teams with Xiangling OR Bennett

**Comment by frzyc** [comment]
Resolved in https://github.com/frzyc/genshin-optimizer/pull/1740
