### ISSUE TITLE
Assume main stat now compares against unleveled equipped artifacts

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1704]
https://discord.com/channels/785153694478893126/1217433268014813215

The current equipped main stat level is used into of the assume main stat level, leading to what you see here, a 15% increase by changing from the set im on to the set im on but with better leveled artifacts
![image](https://github.com/frzyc/genshin-optimizer/assets/36019388/ec6ba4ac-e9fe-4fa2-b1b0-135d925f7be7)

db in discord message

**Comment by frzyc** [comment]
This is intended behaviour, It is a massive undertaking to increase the assumed level of the compared build(which can be both real and TC build). This shows the actual comparison of increasing main stat as a generated result in optimizer.
