### ISSUE TITLE
Open "Loadout Settings" for current character by clicking their tab

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1714]
Suggestion to make clicking the current character's tab also open the Loadout Settings:

![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/4b4ca126-2a06-4e7f-88ae-9afaa59ffe17)

**Comment by frzyc** [comment]
Why would this be needed? this would open up a popup if a user just want to swap to a different character. Sounds more like an annoyance.

**Comment by StainAE86** [comment]
No you misunderstand. It would only open the popup if you're on the current character.
If you're already on Hu Tao -> clicking Hu Tao opens her Loadout settings.
If you're on Hu Tao -> clicking Xiangling swaps to Xiangling

**Comment by frzyc** [comment]
Still no. A navigation element is just an navigation element, it shouldn't be opening popups. Its taking away from the role of the button right next to it.
