### ISSUE TITLE
Compare to requires 2 clicks

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1717]
Steps to reproduce:

Have multiple builds.
1) Click "Compare" checkbox
2) Click the dropdown(up?) and select a build to compare against
3) Click the dropdown to select another build: **dropdown does not open**
4) Click the dropdown a 2nd time: it will now open

![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/504f30b2-6eee-450e-a595-57759ae12c67)

**Comment by frzyc** [comment]
No longer reproduceable after some code refactoring from https://github.com/frzyc/genshin-optimizer/pull/1724.
