### ISSUE TITLE
Remove (i) info icon when no description is present

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1718]
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/eeed0a63-e834-47d8-b819-4b91e349c758)
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/b50a0fd5-a960-41bd-9d43-892f7a43d37b)

**Comment by nguyentvan7** [comment]
Resolved in #1748
