### ISSUE TITLE
Remove fav icon within teams card

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1720]
Since it can't be clicked to toggle, and you have no ability to sort by fav character in this context;
showing the fav icon here only adds additional noise to team card.
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/46b567c0-df90-4ce2-81cb-d9fa93f9f23d)

**Comment by frzyc** [comment]
The Card is almost 100% clickable, there is already too many points of interaction on this UI. I would not want to add another one.

**Comment by StainAE86** [comment]
I would suggest not showing the fav icon at all then. If you can't toggle it there's no reason to show it.
It provides no use in this context since you cant sort by fav characters on this screen.

**Comment by HassnHamada** [comment]
I'll take this.

Unrelated to this issue but maybe later add to ability to mark favorite teams.
