### ISSUE TITLE
Reduce Description input size

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#1728]
Suggested as part of https://github.com/frzyc/genshin-optimizer/issues/1721:
 - for loadout/team/build editor,
 - Reduce the vertical height of description input, (to 1 or 2 lines)
 - allow input size to be resized.

**Comment by HassnHamada** [comment]
I'll take this

**Comment by HassnHamada** [comment]
By 'allow input size to be resized' do you mean to shrink the text font size when it overflows the description box size or expand the description box itself

**Comment by frzyc** [comment]
expand the description box itself

**Comment by frzyc** [comment]
You can probably do CSS `resize: vertical;`, or I'm not sure if there is a MUI way to do it

**Comment by HassnHamada** [comment]
I just checked MUI [TextField](https://mui.com/material-ui/api/text-field/) have `minRows` so I can just replace `rows={4}` with `minRows={2}` this will make it expand infinitely
