### ISSUE TITLE
Clicking the character icon within a team takes you to their Opt Tab

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1732]
Suggestion would be to click the title bar to take you to the Overview Tab of the "On Field" character,
but clicking any of the character icons will takes you to Opt Tab to increase the flow of the UI.

![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/76fa4d3e-e909-4f41-9d5a-cb3059c1bbd5)

This would assist in the flow outlined in #1731

**Comment by frzyc** [comment]
No, That's confusing and just makes the behaviour inconsistent. also, if the character has a tc build active, it doesn't have a optimization tab. I am not sure what issue you are trying to address with this, but this is not the way to go.
