### ISSUE TITLE
Show teambuffs per character in the team setting UI

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#1755]
Problem statement:
As we make more distinctions between teambuffs in terms of the target(s) that receives the buff (on-field, full team, full team without src, specific element), a singular teambuff UI is not sufficient. 

The current Team buff UI actually reflects the current character in team UI's teambuffs, but since there is no indicator that is what's happening, its not intuitive. 

Suggestion:
In the team setting UI, duplicate the teambuff UI across all teammates. 
<img width="1322" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/1754901/85732707-a41b-471b-bd41-2401743f8c06">

Questions to resolve:
- Maybe we can move the resonance UI out of the 1st column, so we can have a "4-column" layout instead of 5.

**Comment by StainAE86** [comment]
My question would be - does the overview of the resulting team buff stats even need to be here?
Because all that information is already present under the conditionals.

![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/9ed92f96-ac88-4f78-9876-292711853fdd)

**Comment by frzyc** [comment]
> My question would be - does the overview of the resulting team buff stats even need to be here? Because all that information is already present under the conditionals.
> 
> ![image](https://private-user-images.githubusercontent.com/101696552/313384598-9ed92f96-ac88-4f78-9876-292711853fdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzQyMDUsIm5iZiI6MTcxMDU3MzkwNSwicGF0aCI6Ii8xMDE2OTY1NTIvMzEzMzg0NTk4LTllZDkyZjk2LWFjODgtNGY3OC05ODc2LTI5MjcxMTg1M2ZkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQwNzI1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzkyNTgxZWQ1ODYzZmE2NWIyZjhiMDgxNGJjNzcyYmQ2MjgzNmQxYzA1ZTQzYTE0N2ZlMTgxOTk4NjI3NmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vhAq2n74RsL-076z9LUFCH6OsxRkqonUUJG_hhijeug)

I would argue yes, in the premise of this issue, i stated that it is difficult for the end user to know which teammates are being buffed. A buff showing that its contributing 10%atk to the team doesnt show which characters the buff its being applied to. (And we don't have the system to show it), so the resulting teambuffs can't be represented in a single UI.

**Comment by StainAE86** [comment]
I don't think this is the UI to show which character in the team is receiving which buff.
I think it's more important to show which characters are the SOURCE of which buff.

Then an overview of which buffs a character gets from the team (which can be different if theyre the active/onfield or not) can appear on their overview tab. Where the buffs they are receiving from their weapon and artifacts also appear.

**Comment by frzyc** [comment]
You are not incorrect here, the intention of this issue is the creation of an UI that shows the resulting teambuffs on a character, whether it shows in this UI or not is somewhat secondary. (I do like the idea of toggling the UI and the buff updates on each character, its an instant feedback for users)

**Comment by StainAE86** [comment]
The problem with allowing the user to toggle the buffs on this UI is it's not communicated well enough that by changing the buffs here they're actually changing that characters own talent buffs too. Which is very different behavior to what it used to be.

**Comment by frzyc** [comment]
> it's not communicated well enough that by changing the buffs here they're actually changing that characters own talent buffs too.

I can agree with you on this. We will await more discussion via @nguyentvan7

**Comment by frzyc** [comment]
Conclusion: Will add UI to address gap for short-term as described in issue, discussion on a final destination to a teambuff overview UI will be a separate issue.
