### ISSUE TITLE
Interaction between equipped art list, use from teammates' builds & currently equipped

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1770]
https://discord.com/channels/785153694478893126/795544823804198922/1218895908687843569

[General_2024-03-17_12-27-19.json](https://github.com/frzyc/genshin-optimizer/files/14627383/General_2024-03-17_12-27-19.json)

The user is confused because when optimizing Aloy they've disallowed artifacts from Rosaria - and thinking that the Sands is being suggested for Aloy because they enabled "Use from Teammates' builds"

However that sands is the "currently equipped" artifact for Aloy already, thus the Optimizer is seeing it as free regardless.

Not sure how this situation can be communicated?

**Comment by frzyc** [comment]
Probably addressed by #3 in https://github.com/frzyc/genshin-optimizer/issues/1625
> when the "use teamate's active build" toggle is enabled, if a generated build has an artifact on an active build in the team, should an warning
