### ISSUE TITLE
Potential bug with scan imports

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1771]
https://discord.com/channels/785153694478893126/785176548428087306/1218908043115495554

I have no way of verifying this. But two users have said after uploading a new scan over their existing db it "resets everything"

**Comment by frzyc** [comment]
... gonna need better reproduction steps than hearsay

**Comment by frzyc** [comment]
Since there are no firm reproduction steps, and the few scans I've done doesn't seem to cause any issues, will await for this issue to popup with more details.
