### ISSUE TITLE
Changing the conditionals on a weapon, changes it on all copies of that weapon

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1775]
For example I have a R1 WGS on Diluc with the Conditional Active:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/bda5871b-1e0b-4ac7-a479-0d9b64346e71)

I have a 2nd R2 WGS:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/430604da-1b03-42ef-8129-aee1566e39c5)

I create a new build for Diluc and swap to the R2 WGS for that build:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/fddf039e-64f6-46a5-86b4-4374e6b4d701)

The conditional is already active:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/a18941c1-a180-4a2d-abf3-f9384dba89b7)

If I disable the conditional on the R2 version:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/82f80a5f-a02a-48a4-bbce-6131df3d5654)

It also disables the conditional on the R1 copy of the weapon that Diluc has equipped:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/a5ba3802-8ce8-4c5c-a67a-32d12b0f5f73)

**Comment by frzyc** [comment]
Nope, conditionals are not stored on the weapon (for good reason). there is no way to support this without a system rewrite, and this is such a niche usecase to even consider putting that effort in.

**Comment by StainAE86** [comment]
Also I don't see how this is any more niche than coming Fav Sword vs Iron Sting. It's just different stat's from the weapon, why should it matter if it's the same weapon or not.

You can't even add or remove the buff via Bonus Stats to cancel out or simulation the weapon's conditional because Bonus Stats are saved within the Loadout, not the Build.
