### ISSUE TITLE
Hutao pyro infusion not working

### ISSUE THREAD

**Issue by awacs** [frzyc/genshin-optimizer#1776]
![image](https://github.com/frzyc/genshin-optimizer/assets/3054128/993e099e-913b-4391-b26c-fd1e0fb18690)

This is after enabling E state

**Comment by nguyentvan7** [comment]
I don't get it, she has infusion in the screenshot

**Comment by StainAE86** [comment]
It's possible they mean the pyro infusion from bennet c6 is missing before the dropdown selector has been removed.

**Comment by frzyc** [comment]
Since there are no clarification, there doesn't seem to be any substance to this issue.
