### ISSUE TITLE
Indication for number of loadouts a Character has

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1781]
The Team's page shows the contents of a team (characters)
The Loadouts section of the Character Editor shows the contents of the Loadouts (Builds, TC, MT)

Should the Character page show how many loadouts each character has?

**Comment by frzyc** [comment]
Not sure how relevant this information is, since they can just click on the character to see detailed loadouts, seeing the number of loadouts doesn't seem like a useful information to show in the characters view.
