### ISSUE TITLE
Add # of teams to loadout header

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1815]
![image](https://github.com/frzyc/genshin-optimizer/assets/36019388/9efb065e-a3be-4c2b-a7ed-650c5cb851a2)
https://discord.com/channels/785153694478893126/1220608435175948318

**Comment by frzyc** [comment]
Seems redundant to keep a tally of teams that user can already see. Does not seem like its worth the time to implement & maintain.
