### ISSUE TITLE
Silly Optimizer Teams Search Function Bug

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1841]
https://discord.com/channels/785153694478893126/1221761787888795648

Searching for characters by their real names doesn't work in the Teams tab, but it works in the Characters tab.

Turning off Silly Optimizer fixes this, but you can basically only search for whatever their name is "showing up" rather than being able to search through both names like the Characters tab.

**Comment by HassnHamada** [comment]
I'll take this 👍
