### ISSUE TITLE
Add TC Build import/export

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1849]
This already exists when exporting/importing teams. But a way to import/export these builds without a whole team would be nice.

This would also enable cheaper Enka/Akasha integration, where those services can just export the stats in our agreed upon format, and users can import into GO for build comparison on more than just raw stat numbers

**Comment by frzyc** [comment]
I am not sure If i want to allow the exporting of TC builds, an export of just the TC build doesnt have the context of the character around it. External imports from enka/akasha is interesting, but that requires a whole new infrastructure. Until that infrastructure is built, I don't think its worth pursuing adding a new export format for this usecase.
