### ISSUE TITLE
I got an error message, after that when i want to optimize, i get 0 results

### ISSUE THREAD

**Issue by Midcall** [frzyc/genshin-optimizer#1859]
Hello,

sadly i cant remember the error message. But when i try to optimize a build, i get 0 results. It looks like it doesnt check the artefacts any more because the search is done after half a second, usually it needs longer. I tried to load an older database, but it itsnt working there too. 

Any ideas ?

**Comment by nguyentvan7** [comment]
Probably percentage based build constraints not working properly ATM
#1858

**Comment by Midcall** [comment]
I just checked, it does find artefacts again after switching from some % value to a fix one.
