### ISSUE TITLE
Transfer artifacts between plateforms

### ISSUE THREAD

**Issue by hayosarid** [frzyc/genshin-optimizer#19]
Hey , it would be cool if we could transfer artifacts between platforms . I added all my artifacts on pc but i can't really access my informations on phone or other pcs.
It's great work and keep up really great foe the community.

**Comment by dhisonp** [comment]
Was about to post a suggestion to incorporate some kind of account binding, like Google or Facebook to save user artifact data (similar to the one in Genshin Interactive Map). I'll try to implement it on my fork later when I get the chance!

**Comment by frzyc** [comment]
We have a trello task for this, [https://trello.com/c/WSTtago8/53-database-dump](url)
and some instructions on our discord server if you want to do it now. https://discord.gg/CXUbQXyfUs
