### ISSUE TITLE
Add sortable tables to Archive page

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#1978]
Might conflict with the lazy loading/infinite scroll nature of archive page

Need to implement https://mui.com/material-ui/react-table/#sorting-amp-selecting

**Comment by StainAE86** [comment]
Would this be for character base stats (when added), weapon main stat and weapon secondary stat?

**Comment by frzyc** [comment]
Yes to all of the above.

**Comment by HassnHamada** [comment]
I'll work on this
