### ISSUE TITLE
Allow filtering by secondary stat in archive 

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1997]
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/2beeb65c-1902-4d5c-9069-eb130a15feca)

**Comment by chengxi600** [comment]
can i work on this?

**Comment by CordonZeus22** [comment]
I have just started to work on this, can you let me work on it ?

**Comment by chengxi600** [comment]
ok sure

**Comment by CordonZeus22** [comment]
Thank you!
