### ISSUE TITLE
Allow search field to search 2/4-piece field for artifacts in archive

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1998]
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/895045f1-3dc5-49d6-adb4-c632b1c11389)

**Comment by chengxi600** [comment]
@frzyc i can work on this

**Comment by frzyc** [comment]
@chengxi600 Sure, I've assigned this to you. ping me if you need help, ping me on discord in #go-development if you want to start a discussion.
