### ISSUE TITLE
Add way to copy builds between loadouts

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#2002]
There exists a situation where on support characters you can have multiple loadouts created that have different conditionals based on which team they are supporting, such as anemo/vv users. But their actual artifacts or tc builds do not change - only conditionals.

You can easily duplicate a full loadout + all builds within that loadout and modify that to suit, but if you create new builds / tc builds AFTER you've setup your seperate loadouts, there is currently no easy way to copy build data between loadouts.

It's awkward and slow; but you can at least export multi-targets and import them into other loadouts.

![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/105c6976-ef3b-4e46-a453-dcb2990153b2)

**Comment by StainAE86** [comment]
Van already brought up it being good to export/import just the tc builds: #1849

**Comment by frzyc** [comment]
Can be fulfilled by https://github.com/frzyc/genshin-optimizer/issues/2035
