### ISSUE TITLE
Error in the Screenshot parsing

### ISSUE THREAD

**Issue by LukasHuth** [frzyc/genshin-optimizer#2029]
I started to upload all my artifacts and noticed, that all artifacts with $HP >= 1000$ failed to get parsed. The bug is reproduceable by selecting the "Artifacts" tab, then clicking on "Add New Artifact" and after that pasting an artifact with $HP >= 1000$ (like the images linked below). I also linked a screenshot, of the parsing failing. I suspect a problem with the `,` in the parsing process.

## Example artifact images
![image](https://github.com/frzyc/genshin-optimizer/assets/60547284/69363fda-0161-4be4-88f8-2e69306630df)
![image](https://github.com/frzyc/genshin-optimizer/assets/60547284/c0070b0c-5547-495b-bd2e-f3b60c68c7e1)
![image](https://github.com/frzyc/genshin-optimizer/assets/60547284/b0ad0c6d-ff5a-4f0e-bd3c-4e12d47bc3a1)

## Example of the parsing failing
![image](https://github.com/frzyc/genshin-optimizer/assets/60547284/ac7caeac-84fe-4f12-9b5f-2fbd9a285145)

**Comment by frzyc** [comment]
Interesting. The parsing logic should consider commas. Will need investigation.
https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/art-scanner/src/lib/parse.ts#L95 (`parseSubstats`)
