### ISSUE TITLE
Use TextField for artifact substat input

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2039]
<img width="481" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/1754901/9d67e6c8-9062-4d7f-a00c-62758cce55ed">

The "colored input" is sort of out dated. Probably need to redesign this:
- use [TextField](https://mui.com/material-ui/react-text-field/) instead of the colored "button input"
- Fix the width somehow so the text fields line up vertically
- Maybe use [TextFieldLazy](https://github.com/frzyc/genshin-optimizer/blob/master/libs/common/ui/src/components/TextFieldLazy.tsx)?

**Comment by chengxi600** [comment]
I can take a look into this.

**Comment by chengxi600** [comment]
ah ok, ill come back to this after NumberInputLazy is merged
