### ISSUE TITLE
Reaction Element misaligned

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2043]
In the Talent tab, the (i) icon is offset.
![image](https://github.com/frzyc/genshin-optimizer/assets/1754901/af79893a-399d-44bd-b417-e6ad6ce92e2f)
Probably need a "align-items: center" somewhere...

**Comment by bluezettabyte** [comment]
I believe this issue can be closed. I checked the Talent tab, but I don't find the issue appearing either in dev or on the website. 

![image](https://github.com/frzyc/genshin-optimizer/assets/37258523/0118265d-e87b-4cb1-bba9-fdba2a10919e)
