### ISSUE TITLE
Convert Button-like Inputs to TextField in TC tab (main stats)

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2046]
<img width="389" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/1754901/4b9c3a98-d500-48a5-9287-b388af19bdbf">

Convert the inputs here to [TextField](https://mui.com/material-ui/react-text-field/)

Probably replace the background color to border color?

**Comment by artloren** [comment]
I can take a look at this

**Comment by frzyc** [comment]
@artloren I've assigned the issue to you, I've also merged in a number specific lazy input: https://github.com/frzyc/genshin-optimizer/pull/2128, I would advice using this for standardization.
