### ISSUE TITLE
Convert Level input to TextField

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2047]
![image](https://github.com/frzyc/genshin-optimizer/assets/1754901/2171f3ea-ab2e-48ce-bc72-dd99762b0d01)
[LevelSelect Component](https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/ui/src/components/LevelSelect.tsx) is still using the "button-like" inputs.
The button-like input should be a [TextField](https://mui.com/material-ui/react-text-field/) (preferrably a TextFieldLazy)
Not sure what a "prettier" way to structure this, since the `/20` here is a button (to toggle between ascension)

**Comment by Davidthecode** [comment]
hey @frzyc  i could work on this

**Comment by frzyc** [comment]
Thanks, feel free to ping me if you have any questions

**Comment by ajlee1976** [comment]
Heya @frzyc Looks like the other person dropped the assignment on this, I can pick it up and have a look

**Comment by niktekusho** [comment]
Is this closed by #2123 ? 😉

**Comment by frzyc** [comment]
You are right, it was not correctly referenced in the original PR to close this.
