### ISSUE TITLE
GO-ads needs less white background

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2048]
Current iteration of GO-ads are just black text on white background, which is really ugly. 
![image](https://github.com/frzyc/genshin-optimizer/assets/1754901/97df71e4-d796-47a8-a9d7-459c29172669)

We don't want them to look too GO-like, since we still need to make them distinctively ad-like. 
There must be a middle-ground we can do?
- dark-theme ads? White text on black blackground? (won't work for the drake meme ad, but works for text ads)

**Comment by nguyentvan7** [comment]
Fixed in #2103
