### ISSUE TITLE
Preserve previous character tab when going to team settings 

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#2058]
If you go to a team and select character A then their optimize tab
Then go to team settings to adjust something
Then click back to character A
You end up back in their overview tab. It would be nice if we could save the previous tab and redirect back to it automatically when clicking the character again
Yes the back button exists, but it still has some stigma due to server side operations, and it's further away than the character tab

**Comment by frzyc** [comment]
I'm just gonna say no to this right now, it may be "saving" a click for the end user, but considering it took like 4 PRs to get routing for this area to work correctly, adding in this side-effect is not worth the effort. 
Also, the back button does exist, people should use it, and I don't have to code anything potentially annoying to get it to work, cause I already got it to work over all that code churn in this area previously.
