### ISSUE TITLE
Arlecchino has no default pyro infusion on Normal Attack (Multi-Optimization Target Config)

### ISSUE THREAD

**Issue by fluffyfirefly** [frzyc/genshin-optimizer#2071]
Multi-Optimization Target Configs for Arlecchino do not work properly if you don't add a manual pyro infusion (infusionAura":"pyro","). Arlecchino just doesn't seem to have a Pyro Infusion on Normal Attack/ Charged Attack or Plunging Attack.

Target Arlecchino:
![image](https://github.com/frzyc/genshin-optimizer/assets/69301522/b5759746-9b41-44eb-ae9f-4f8511929d59)

Comparison Target Yoimia:
![image](https://github.com/frzyc/genshin-optimizer/assets/69301522/db0ab366-965a-4850-945a-b85f33828654)

As seen in the screenshots above, Arlecchino's attacks are physical by default, while Yoimia's are pyro.
I believe Arlecchino should be Pyro by default too.

Vape Arlecchino without Bennet Pyro Infusion:
{"name":"Arle Vape Any Weapon","description":"Solo Arlecchino, BoL set to 105% in talents",
"targets":[
{"weight":1,"path":["skill","finalDmg"],"hitMode":"avgHit","bonusStats":{}},
{"weight":1,"path":["skill","spikeDmg"],"hitMode":"avgHit","bonusStats":{}},
{"weight":1,"path":["skill","sigilDmg"],"hitMode":"avgHit","bonusStats":{}},
{"weight":1,"path":["charged","dmg"],"hitMode":"avgHit","reaction":"vaporize","bonusStats":{"all_dmg_":25.5,"atk":1203,"pyro_dmg_":55,"charged_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","0"],"hitMode":"avgHit","reaction":"vaporize","bonusStats":{"all_dmg_":29,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","1"],"hitMode":"avgHit","bonusStats":{"all_dmg_":29,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","2"],"hitMode":"avgHit","bonusStats":{"all_dmg_":32.5,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","0"],"hitMode":"avgHit","reaction":"vaporize","bonusStats":{"all_dmg_":32.5,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","1"],"hitMode":"avgHit","bonusStats":{"all_dmg_":36,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","2"],"hitMode":"avgHit","bonusStats":{"all_dmg_":36,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","0"],"hitMode":"avgHit","reaction":"vaporize","bonusStats":{"all_dmg_":39.5,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","1"],"hitMode":"avgHit","bonusStats":{"all_dmg_":39.5,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","2"],"hitMode":"avgHit","bonusStats":{"all_dmg_":43,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","0"],"hitMode":"avgHit","reaction":"vaporize","bonusStats":{"all_dmg_":43,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","1"],"hitMode":"avgHit","bonusStats":{"all_dmg_":46.5,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","2"],"hitMode":"avgHit","bonusStats":{"all_dmg_":46.5,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","0"],"hitMode":"avgHit","reaction":"vaporize","bonusStats":{"all_dmg_":50,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","1"],"hitMode":"avgHit","bonusStats":{"all_dmg_":50,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","2"],"hitMode":"avgHit","bonusStats":{"all_dmg_":50,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}}
]}

Vape Arlecchino with workaround Bennet Pyro Infusion:
{"name":"Arle Vape Any Weapon","description":"Solo Arlecchino, BoL set to 105% in talents",
"targets":[
{"weight":1,"path":["skill","finalDmg"],"hitMode":"avgHit","bonusStats":{}},
{"weight":1,"path":["skill","spikeDmg"],"hitMode":"avgHit","bonusStats":{}},
{"weight":1,"path":["skill","sigilDmg"],"hitMode":"avgHit","bonusStats":{}},
{"weight":1,"path":["charged","dmg"],"hitMode":"avgHit","reaction":"vaporize","infusionAura":"pyro","bonusStats":{"all_dmg_":25.5,"atk":1203,"pyro_dmg_":55,"charged_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","0"],"hitMode":"avgHit","reaction":"vaporize","infusionAura":"pyro","bonusStats":{"all_dmg_":29,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","1"],"hitMode":"avgHit","infusionAura":"pyro","bonusStats":{"all_dmg_":29,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","2"],"hitMode":"avgHit","infusionAura":"pyro","bonusStats":{"all_dmg_":32.5,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","0"],"hitMode":"avgHit","reaction":"vaporize","infusionAura":"pyro","bonusStats":{"all_dmg_":32.5,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","1"],"hitMode":"avgHit","infusionAura":"pyro","bonusStats":{"all_dmg_":36,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","2"],"hitMode":"avgHit","infusionAura":"pyro","bonusStats":{"all_dmg_":36,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","0"],"hitMode":"avgHit","reaction":"vaporize","infusionAura":"pyro","bonusStats":{"all_dmg_":39.5,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","1"],"hitMode":"avgHit","infusionAura":"pyro","bonusStats":{"all_dmg_":39.5,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","2"],"hitMode":"avgHit","infusionAura":"pyro","bonusStats":{"all_dmg_":43,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","0"],"hitMode":"avgHit","reaction":"vaporize","infusionAura":"pyro","bonusStats":{"all_dmg_":43,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","1"],"hitMode":"avgHit","infusionAura":"pyro","bonusStats":{"all_dmg_":46.5,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","2"],"hitMode":"avgHit","infusionAura":"pyro","bonusStats":{"all_dmg_":46.5,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","0"],"hitMode":"avgHit","reaction":"vaporize","infusionAura":"pyro","bonusStats":{"all_dmg_":50,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","1"],"hitMode":"avgHit","infusionAura":"pyro","bonusStats":{"all_dmg_":50,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}},
{"weight":1,"path":["normal","2"],"hitMode":"avgHit","infusionAura":"pyro","bonusStats":{"all_dmg_":50,"atk":1203,"pyro_dmg_":55,"normal_dmg_":16,"pyro_enemyRes_":-40,"atk_":65}}
]}

My Database:
[Database_2024-05-05_15-44-27.json](https://github.com/frzyc/genshin-optimizer/files/15213561/Database_2024-05-05_15-44-27.json)

**Comment by nguyentvan7** [comment]
You need to set a bond of life >=30% in her talents page

**Comment by fluffyfirefly** [comment]
Thank you very much, my bad.
