### ISSUE TITLE
database lastedit not updating when changing loadout/team

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2072]
When the loadouts are changed/updated, it doesn't change the lastEdit time listed under the database.

_Originally posted by @maoadrian12 in https://github.com/frzyc/genshin-optimizer/issues/2070#issuecomment-2094870934_

Issue like originates from https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/db/src/Database/ArtCharDatabase.ts#L86, where database needs to `followAny` changes to `teams`, `builds`, `teamChars`

**Comment by CordonZeus22** [comment]
Any changes to DataManagers or DataEntries should change the lastEdit or only the one you listed ?

**Comment by frzyc** [comment]
other than dbmeta(where last edit is stored), that may cause an infinite loop
