### ISSUE TITLE
Artifact Upgrader Filters

### ISSUE THREAD

**Issue by mamikonyanN** [frzyc/genshin-optimizer#2096]
After using upgrader for a day, I thing it may be usefull to filter out some upgrade suggestions by fields like "min prob. upgrade" and "min avarage increase" and place it only in that tab.
For example: 
Not suggest an artifacts with roll probability lesser than 75%
Or not suggest an artifact with lesser average increase than 2.5%
![image](https://github.com/frzyc/genshin-optimizer/assets/41971993/fa24d956-d8fd-43ea-b691-64cf13aa2ab2)

**Comment by frzyc** [comment]
Not sure if adding this filter makes sense, lower rated artifacts are hidden by pagination, so adding min filters will add extra UI and code complexity without any benefit that I can see. Is there a reason why you would want this filter?

**Comment by mamikonyanN** [comment]
Not really any reason, except seeing less artifacts can help me choose faster and think less 👍. And seeing no suggestions can mean, that there are nothing worth leveling to gain 0.1% power, it feels fulfilling, idk
But I see what you mean now, it's nothing functional

P.S. sorry for my English, it's not my first language and I'm struggling

**Comment by frzyc** [comment]
Thanks for your feedback! I am sure adding the filters will confuse new users as well. I don't think its worth the effort to add filters here.
