### ISSUE TITLE
Having an invalid build constraint will crash the Artifact Upgrader tab

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#2109]
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/ae67b144-5a7d-4e1b-8e63-b4b9280f1ca1)

[message.json](https://github.com/frzyc/genshin-optimizer/files/15285886/message.json)

Go to Neuvi -> Artifact Upgrader -> Crash

**Comment by clevernt** [comment]
The issue is being able to choose a team buff as a build constraint
![image](https://github.com/frzyc/genshin-optimizer/assets/61787059/3e8892ac-c60f-4dd1-a7d0-02f542e1a3dd)
Doing so in the Optimize tab then opening Artifact Upgrader causes the crash
