### ISSUE TITLE
Archive page needs to have browser history friendly routing

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2125]
Currently navigating from any page into the archive page disallow going back in history, likely due to the `/archive`->`/archive/artifact` path. routing to `/archive` and then to a tab should replace history, instead of adding onto it.

**Comment by chengxi600** [comment]
@frzyc would this be okay having /archive also point to the artifact tab? This fixes the history issue I think but would make the /archive/artifacts path redundant. Not sure if this is good practice.

**Comment by frzyc** [comment]
> @frzyc would this be okay having /archive also point to the artifact tab? This fixes the history issue I think but would make the /archive/artifacts path redundant. Not sure if this is good practice.

I think this is the only solution, having an empty page is probably more harmful.
