### ISSUE TITLE
Add a delete button in teams card

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2132]
Since the addition of a more contextual deletion modal in https://github.com/frzyc/genshin-optimizer/pull/2122, it may make sense to add it to the overview card
<img width="405" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/1754901/1dbf4877-f61f-4fa8-acbe-6c77f0763224">

**Comment by chengxi600** [comment]
Can I take this issue?
