### ISSUE TITLE
Edit Loadout name/desc by clicking on loadout title

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2135]
Similar to https://github.com/frzyc/genshin-optimizer/issues/2134

<img width="941" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/1754901/c9b19969-e0ae-4713-9421-c19611b6a21f">

**Comment by bluezettabyte** [comment]
I can start working on this issue once I'm able to resolve #2134

**Comment by frzyc** [comment]
@bluezettabyte sorry for the late reply, I was on vacation for the past 2 weeks. 
I think I want to resolve both #2134 and this issue at the same time, to have parity of behaviour across team/loadout UI.
I have approved #2164 pending a PR resolving this issue.
