### ISSUE TITLE
Tone down Home page Quick Links

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2140]
<img width="518" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/1754901/43f73813-4b08-4eca-b810-23143dd52bef">

Since its occupying above-the-fold realestate, it is perhaps too colorful, the implementation of using buttons also makes it take up too much space. For an element that funnels users away from the site, it could be toned down, in both color and size.

May be a good idea to implement it using [Links](https://mui.com/material-ui/react-link/)

**Comment by josh-the-dev** [comment]
Have an idea for this. Think Links as you mentioned (with icons) would be a really clear implementation. Think the colours are a bit  much as well and a bit overwhelming.
Also maybe dividing into categories. Either way might take this away if no-one else is. 👍
