### ISSUE TITLE
Add a way to simulate different constellation levels in a build

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#2144]
It would be nice to quickly compare build results by just swapping a characters build (e.g. a c0 vs c2 build) without having to go to the character page and edit the constellation, then remember to change it back etc

Same could be applied for talent level but that at least has a bonus stat workaround and is less common/impactful

**Comment by frzyc** [comment]
we could add constellation delta as a separate stat, through they would not be different in character builds (same loadout). It really depends on how much duct taping you want to get this to work (with the understanding that if two builds have different constellations, we'd have no way to show them in the result stats). I'm not sure if all of this work is justified by simply "it would be nice". Will have to look at user feedback to see more specific usecases.

**Comment by nguyentvan7** [comment]
Implemented in #2154
