### ISSUE TITLE
Add db import info for team/loadout/build

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2145]
![image](https://github.com/frzyc/genshin-optimizer/assets/1754901/0a5fb085-a3be-4322-a7da-c992cac9a439)
Currently only shows art/weapon/char

For importing GO data on another GO data for team/loadout, I believe the current logic is the import data overwrite the existing data. I think I am fine with that, deduping would be unnecessarily complicated, the UI should just reflect this.

**Comment by CordonZeus22** [comment]
I will work on it

**Comment by CordonZeus22** [comment]
Actually, importing teams doesn't remove existing teams not in import. Even with the `Delete items not in import` option. Same for loadout. Is this behavior intended ?

**Comment by nguyentvan7** [comment]
Seems so https://discord.com/channels/785153694478893126/1218906581593231540, tho i still feel like its weird that teams are not deleted with that setting enabled

**Comment by CordonZeus22** [comment]
This thread has been marked as not a bug. So, this behavior shouldn't be changed ?

**Comment by nguyentvan7** [comment]
Leaving @frzyc to give final say

**Comment by frzyc** [comment]
> For importing GO data on another GO data for team/loadout, I believe the current logic is the import data overwrite the existing data. I think I am fine with that, deduping would be unnecessarily complicated, the UI should just reflect this.

Yeah i do not think its worth any developer's time to dedup/merge team/loadouts. The ask for this issue is basically just add a tally as a visual for users, and not to add any complex logic to db

**Comment by CordonZeus22** [comment]
There is already a dedup/merge for team and loadouts I think

**Comment by CordonZeus22** [comment]
If no dedup/merge should be done, what will be written on the card ?

**Comment by frzyc** [comment]
Yes, and TC builds

**Comment by CordonZeus22** [comment]
How the total amout of loadouts can be computed ?

**Comment by frzyc** [comment]
yeah loadouts are called `teamChars`(due to legacy naming) so it would be `database.teamChars.values.length`

**Comment by CordonZeus22** [comment]
Thanks
