### ISSUE TITLE
convert artifact level button to textfield on theorycraft page (substats)

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2158]
![image](https://github.com/frzyc/genshin-optimizer/assets/1754901/0c94224c-a930-4d87-bc3c-226b3a55ed0c)

Related to https://github.com/frzyc/genshin-optimizer/issues/2046

Update the custom inputs to `NumberInputLazy`

**Comment by artloren** [comment]
I can take a look!
