### ISSUE TITLE
Elemental SKill Lvl

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#2196]
![image](https://github.com/frzyc/genshin-optimizer/assets/36019388/9bb6c28c-292d-4eb0-8e25-bee64da788bb)

**Comment by frzyc** [comment]
https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/keymap/src/KeyMap.ts

**Comment by frzyc** [comment]
Can also change to `Lv.` as in game.

**Comment by OHSOHYEON00** [comment]
Hi, Can I take this issue?  @frzyc @nguyentvan7  As I understand the changes are typos.
