### ISSUE TITLE
"X" in weaponcard in weapon page should be removed

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2256]
![image](https://github.com/frzyc/genshin-optimizer/assets/1754901/b7511a78-efa7-4f5f-9fdb-39270996e2df)
Either make it so that clicking the X in the location dropdown unequip, or remove the X altogether (whichever is the easiest)

**Comment by nguyentvan7** [comment]
You can't unequip a weapon, so the X should be removed. it used to be but has come back for whatever reason
