### ISSUE TITLE
Bold the selected header tab text

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2263]
I think the text is supposed to be bolded as well
design doc:
![image](https://github.com/frzyc/genshin-optimizer/assets/36019388/78d6c5cf-5016-4038-971f-b0625c6c4ae9)

site:
![image](https://github.com/frzyc/genshin-optimizer/assets/36019388/359ce8f9-536c-4f1a-9f4d-8eb11b87e746)

_Originally posted by @nguyentvan7 in https://github.com/frzyc/genshin-optimizer/pull/2261#discussion_r1650201695_

Please read the original discussion. The solution may seem straight forward but execution can be a tad tricky. 
- Need to bold selected header tab
- Figure out a way so that when swapping between bolded and unbolded text within the header tabs, there is no layout shift, due to the text being slightly different size switching between bolded and unbolded.

**Comment by claireoe** [comment]
@frzyc can I assist with this issue?

**Comment by claireoe** [comment]
@frzyc just want to confirm the task is for the headers on the '/archive' page ?

**Comment by frzyc** [comment]
> @frzyc just want to confirm the task is for the headers on the '/archive' page ? The header values are already in bold. Should i just make the font colour match the underline indicator 'blue'?

I dont think "archive" is mentioned in this issue anywhere. this issue is referring to the site header, like the main site navigation on the top.

**Comment by claireoe** [comment]
Okay, I couldn't see the text on the heading 
<img width="931" alt="Screenshot 2024-06-27 113757" src="https://github.com/frzyc/genshin-optimizer/assets/142216709/8d73e1f6-855a-4c91-8430-cee83c8670bb">
 but can see it on a larger screen.

**Comment by claireoe** [comment]
@frzyc created a pull request https://github.com/frzyc/genshin-optimizer/pull/2277

**Comment by claireoe** [comment]
@frzyc created a pull request with the requirements fulfilled  https://github.com/frzyc/genshin-optimizer/pull/2279

**Comment by frzyc** [comment]
Completed.
