### ISSUE TITLE
Add i18n to Relic Editor

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2288]
Mainly the UI elements, not the generated values like stats, slot, location, set names, for english translations only.
<img width="1024" alt="image" src="https://github.com/frzyc/genshin-optimizer/assets/1754901/a427bc14-6ea7-41ac-800a-ac3cf8ddb5a8">

**Comment by tiffanynwyeung** [comment]
Technically #2423 addressed this by adding nearly all translations to Relic Editor (only missing the no-relics modal popup information, and currently that's not in SRO, will be added in the future). Closing for now.
