### ISSUE TITLE
Upopt missing a tab title

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#2294]
https://github.com/frzyc/genshin-optimizer/blob/6b745f69f7c41b92de93380a97fe6b0b2f349ddb/libs/gi/localization/assets/locales/en/ui.json#L4

Need one for `upopt`, with entry "Artifact Upgrader"

**Comment by k-parihar** [comment]
Hi @nguyentvan7 
Added `upopt` and opened a PR. Please Review.

**Comment by nguyentvan7** [comment]
Fixed in #2295
