### ISSUE TITLE
Kokomi Burst's initial Damage scales with ATK instead Max HP

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#230]
![image](https://user-images.githubusercontent.com/1754901/163354682-8a37031c-6360-4365-b4ab-a8c055c0f115.png)

**Comment by frzyc** [comment]
![image](https://user-images.githubusercontent.com/1754901/163363649-f41fa4ff-79a5-425b-b9a9-c3136eaef134.png)

**Comment by nguyentvan7** [comment]
![image](https://user-images.githubusercontent.com/36019388/163660421-88f87ad3-f55d-4551-adf0-ad93ca95a8d6.png)
Should also fix her charged attack text
