### ISSUE TITLE
Decrease opacity of common build pieces in swap menu

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2336]
Something for later probably, but it would be cool if in this interface
![image](https://github.com/user-attachments/assets/389d3bf6-f3a5-47cb-aa4e-4b920752e0e1)

Artifacts that were the same had lower opacity, or some other way to de-emphasize them, and emphasize the actual change
![image](https://github.com/user-attachments/assets/188709b3-36df-49f6-93d2-cb4c8985d5ce)

_Originally posted by @nguyentvan7 in https://github.com/frzyc/genshin-optimizer/issues/2331#issuecomment-2248302871_

**Comment by dyzhuu** [comment]
I can pick up this issue
