### ISSUE TITLE
Disallow Deepwood Memories set bonus stacking

### ISSUE THREAD

**Issue by Fizzy158** [frzyc/genshin-optimizer#2358]
I have 2 characters with this artifact set on in a team. It says that I would get -60% Dendro Res Shred when in fact you cannot do that in game (at least to my knowledge)
![image](https://github.com/user-attachments/assets/ee9c26a5-a615-45fb-b61a-1069f43cda52)

**Comment by nguyentvan7** [comment]
Dupe of #361
