### ISSUE TITLE
[Bug] Wrong formulas RES for Max Sea-Dyed Foam DMG

### ISSUE THREAD

**Issue by Dranixx** [frzyc/genshin-optimizer#238]
The formulas for RES here should be **1-(RES/2)** with RES at -20%, missing the parenthesis.

And also OHC is independent of enemy def. (from keqing main https://library.keqingmains.com/equipment/artifacts#ocean-hued-clam)
So there is no DEF multiplier in the DMG formulas.

![res](https://puu.sh/IV2I3/c931e7510e.png)

**Comment by nguyentvan7** [comment]
The parentheses don't change the operator precedence, but I added them to the displayed formula for clarity anyways

**Comment by frzyc** [comment]
I dont see any reason to add parentheses, BEDMAS is grade 2 knowledge.

**Comment by Dranixx** [comment]
I mean adding parenthesis because in this case it should be it's 1-(**-20%**/2) = 1+10% = 1.1

**Comment by nguyentvan7** [comment]
![image](https://user-images.githubusercontent.com/36019388/163726800-e6ce3172-a5bf-4f14-af14-ae5d9622174d.png)
![image](https://user-images.githubusercontent.com/36019388/163726809-5e18cf44-c2c2-40af-9cff-b7b8f52a116d.png)
With or without the parentheses, the order of operations is the same, and so is the final outcome

**Comment by Dranixx** [comment]
Yes, as you say for better formulas display.
