### ISSUE TITLE
Allow talent level 11+ (Tartaglia passive talent)

### ISSUE THREAD

**Issue by dhisonp** [frzyc/genshin-optimizer#24]
Noticed that the talent levels are 10 at max. I'd like to try Talent Lv11 since I sometimes bring Tartaglia with me on my Xiao teams. I'll try to implement it on my fork when I get the chance!

Edit: I noticed there's a Team tab WiP. Let me know if this specific issue is planned to be implemented on the Team tab instead!

**Comment by frzyc** [comment]
We will either add it for team update or with Tartaglia, depending.
