### ISSUE TITLE
Rearrange character page stats

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#240]
Now that the UI is moving to a 4 column layout change the character base/advanced/bonus stats into 3 seperate column UI elements and order to mimic the in-game stats page.

![image](https://user-images.githubusercontent.com/101696552/163698919-9d88a44e-c58d-46aa-a929-99513ce0a3d9.png)
![image](https://user-images.githubusercontent.com/101696552/163698972-c55c94d5-824d-4a9c-ac1a-018d9a364299.png)

**Comment by StainAE86** [comment]
A secondary to this - would be a good time to reintroduce editing only the "Base" (precalculation) part of the stats that many people have been asking for.

**Comment by StainAE86** [comment]
With the removal of the stats from the Overview tab and into the Detailed Stats popup this is less of an issue.
But it would still benefit from copying the order from in-game.

**Comment by frzyc** [comment]
Probably be harder to copy from in-game, now there are more dynamic order of the detailed stats on the site.
