### ISSUE TITLE
Aloy's passive that grants 16% ATK% to herself does not work now.

### ISSUE THREAD

**Issue by JohnnyToumieh** [frzyc/genshin-optimizer#2407]
Sorry to do this again but the fix didn't fix it but made it worse xD instead of getting 8% ATK%, she now gets 0% ATK%.
<img width="593" alt="image" src="https://github.com/user-attachments/assets/1f498f63-61d3-4ec1-8cac-1c2994bc6958">

**Comment by JohnnyToumieh** [comment]
This is the previous issue post: https://github.com/frzyc/genshin-optimizer/issues/2382

**Comment by nguyentvan7** [comment]
When Aloy receives the Coil effect from [Frozen Wilds](https://genshin-impact.fandom.com/wiki/Frozen_Wilds), her ATK is increased by 16%, while nearby party members' ATK is increased by 8%. This effect lasts 10s.

This looks working as intended. Aloy should be receiving a 16% buff, and her teammates should be receiving an 8% buff

**Comment by JohnnyToumieh** [comment]
I have the coil effect activated but the 16% ATK% buff isn't showing in her received buffs screen? Sorry I don't understand

**Comment by JohnnyToumieh** [comment]
Nevermind sorry i forgot that buffs given to oneself doesn't show on the received buffs screen

**Comment by nguyentvan7** [comment]
The screenshot you posted is showing the catalyst teammates received buffs (which is 8% from aloy)

If you open the aloy stat page, it should show the 16% atk in her total atk calc
