### ISSUE TITLE
Prayers Artifact Sets Not Working

### ISSUE THREAD

**Issue by Bleu3** [frzyc/genshin-optimizer#2437]
Resetting the page, restarting my device, and even opening on a new device doesn't help. These artifact sets won't load when clicked on, making it impossible to edit. No other sets do this.

![Destiny](https://github.com/user-attachments/assets/a17fb781-6be0-4d78-985b-41b0d713a78f)
![Illumination](https://github.com/user-attachments/assets/7e5a4042-a32c-4c2a-baa3-7fe47ee27095)
![Wisdom](https://github.com/user-attachments/assets/bafc3789-11c5-495a-85e8-8d939d23f43f)
![Springtime](https://github.com/user-attachments/assets/5669ee1c-4c71-436a-8b5a-d40908186bc2)

**Comment by frzyc** [comment]
Likely an issue in https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/ui/src/components/artifact/editor/index.tsx
