### ISSUE TITLE
Incorrect Elemental Resistance calculation when VV shred is configured through team buffs

### ISSUE THREAD

**Issue by PedroCardouzo** [frzyc/genshin-optimizer#244]
When configuring a team that consisted of Ganyu and Venti, when adding the VV Shred of Venti in the team buffs section the formula is incorrect leading to a 1.25 multiplier instead of the default 1.15.
![image](https://user-images.githubusercontent.com/30964001/163725432-53ce414e-2c61-4a7f-a0a9-73e9d17d80c5.png)
In particular
( 100% - ( -10% + Enemy Cryo DMG RES (Venti) -40% ) / 2 ) = ( 100% - ( -50% ) / 2 ) = 125%
should be
( 100% - ( 10% + Enemy Cryo DMG RES (Venti) -40% ) / 2 ) =  ( 100% - ( -30% ) / 2 ) = 115%
I changed my sheet calcs to consider 1.25 res mult and the damage matched up with GO, so I think this is indeed the issue.

**Comment by nguyentvan7** [comment]
It looks like you set Enemy Cryo RES to be -10% in the enemy editor (which is where the -10% is coming from). Or maybe I'm misunderstanding the issue here

**Comment by PedroCardouzo** [comment]
Nope, I'm just dumb... I think I didn't save or had another window when I reset it so It didnt carry, my bad lol.
I was focusing on other stuff so this detail just flew over my head.
