### ISSUE TITLE
Red text is now harder to read on the dark background

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#248]
![image](https://user-images.githubusercontent.com/101696552/163737072-2a7eb34d-e57e-4f1d-a94c-ca8fa0f425b8.png)

![image](https://user-images.githubusercontent.com/101696552/163806281-b5bd4561-2e3e-4b69-9a54-be56e113be8c.png)

**Comment by StainAE86** [comment]
Artifact inspection popup on the build tab is wider than the artifact display

![image](https://user-images.githubusercontent.com/101696552/163737729-7b67619a-c94a-4d10-a73d-e8d21b50ade6.png)

**Comment by kazerniel** [comment]
![image](https://user-images.githubusercontent.com/5689996/163738005-7af832f1-e617-4e9a-80a1-be538d8ac3ab.png)
Build page: In Firefox the artifact image obscures the mainstat value.

**Comment by nguyentvan7** [comment]
> ![image](https://user-images.githubusercontent.com/5689996/163738005-7af832f1-e617-4e9a-80a1-be538d8ac3ab.png) Build page: In Firefox the artifact image obscures the mainstat value.

If you do a hard refresh, it should be fixed in 8.2.1. Was fixed/published like literally 1 minute ago

**Comment by kazerniel** [comment]
> If you do a hard refresh, it should be fixed in 8.2.1. Was fixed/published like literally 1 minute ago

Thanks, that helped :)

**Comment by StainAE86** [comment]
- On both the build preview and character tab the weapon icon does not extend to the bottom of the gradient area.
Could the gradient area be adjusted to suit the height of the artifacts to make the display more uniform?

![image](https://user-images.githubusercontent.com/101696552/163742860-542536d3-7d96-42bf-9294-7d3ae73a8eed.png)

**Comment by StainAE86** [comment]
- Lock button for Aritfact and Weapons are now "behind" the picture so cannot be toggled.

![image](https://user-images.githubusercontent.com/101696552/163755779-6bfbf67b-30bb-4687-a729-78f1e2155428.png)

**Comment by kazerniel** [comment]
I usually use this tool for figuring out colour contrast: https://www.sbwfc.co.kr/color-contrast-checker/

The pyro colour on the character page seems to be #BF2A18 over #2A364D background, which doesn't pass any of the WCAG standards.

Of the damage colours only cryo and physical pass the laxer AA standard, while geo and anemo pass the stricter AAA too. So hydro, pyro and electro are most in need of tweaking.
