### ISSUE TITLE
[Bug] Hovering on weapon/artifact image for first time after a refresh causes screen flicker

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#249]
![chrome_UyYwuuI8YT](https://user-images.githubusercontent.com/36019388/163737765-f0c3a5d3-5ec5-482d-92a6-94dc9a6cf82a.gif)

I couldn't tell what was causing this exactly. Maybe its related to `usePromise`? Although setting `true` for `useOld` param doesn't fix the flickering either

**Comment by frzyc** [comment]
seems to be a consequence of using the tooltip? not sure how to trace such an error... intriguing...

**Comment by nguyentvan7** [comment]
It seems to happen with any tooltip that uses a translated value. So `weaponSheet.name` or `weaponSheet.description`, etc. Using anything else from the weaponSheet doesn't trigger the flicker. Not sure if there is a bug in the translation stuff you made, or just how it works

**Comment by nguyentvan7** [comment]
https://stackoverflow.com/questions/68455594/page-flickers-when-lazy-loading-translations-with-i18next-http-backend possibly related?

**Comment by nguyentvan7** [comment]
So the issue (which was also manifesting as a console render error stating that "anchorEl prop provided to the component is invalid") is that `sheet.name` of various sorts use `<Translate/>`. Which uses `i18next` which will lazyload the translation files. So when the tooltip gets rendered for the first time, the translation isn't loaded. Then the translation loads, then the render occurs again, invalidating the previous element there (causing the anchorEl error), and causing a page flicker.

I fixed it by wrapping those tooltips in `Suspense` w/ `Skeleton` to fill out the space. It's not perfect, since I obviously cannot know the length of the box before the translations are loaded, so the boxes are slightly off-center depending on the final translation length.
I'm also not sure if this should be handled in the `Translate` component, or by the calling code. Looks like `Translate` already has `Suspense` usage, but not if the `textObj` is a `string`.

**Comment by nguyentvan7** [comment]
Fixed in 8.2.2, forgot to link the issue
