### ISSUE TITLE
Multi-Optimisation for EM+ER Kazuha

### ISSUE THREAD

**Issue by aznnico** [frzyc/genshin-optimizer#2512]
I would like to optimize for EM + ER for kazuha leaderboard: https://akasha.cv/leaderboards/1000004702/

I saw this issue: https://github.com/frzyc/genshin-optimizer/issues/1208, but it doesn't solve my problem. I can select basic stat EM and then manually look for the highest ER, but I would like to optimize based on EM + ER. How would I accomplish this?

**Comment by frzyc** [comment]
sounds like you have a working solution with existing features. I will not be spending any of my valuable limited time adding a feature for people to optimize for a leaderboard that has dubious mathematic value.
