### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2524]
![image](https://github.com/user-attachments/assets/aeb52dfe-6083-46ce-8628-2da0409d27f5)

**Comment by monwarqx1250** [comment]
Can you please provide the URL for this? I'm unable to find it

**Comment by frzyc** [comment]
https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/localization/assets/locales/en/page_team.json#L69
