### ISSUE TITLE
Add hit mode toggle buttons back above the build preview

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#253]
- In the **_Great UI Update of 2022_** the hit mode / infusion buttons got moved to the top of the page to be consistent with the entire character page. However it was useful to have them directly above the build preview so you could toggle between avg / non / crit to see how your dmg changed compared to your current build.

Many times even though your avg dmg is increased, your non-crit and crit-hits may decrease and that might not be acceptable in certain circumstances.

- Have them with the clear / new / compare buttons or maybe within each individual build preview for those who generate more than 1 build at a time?

![image](https://user-images.githubusercontent.com/101696552/163779494-4e5d6df5-df93-4b07-905b-7f188c2761f9.png)

**Comment by StainAE86** [comment]
Here's another idea for this one. Change the Hit Mode options to drop downs to save space and put them in every build preview next to "equip artifacts" for people who generate 2+ so they don't have to keep scrolling back to the top to change hitmodes to compare damage.

I suspect having the setting global would be the best option - rather than unique per build preview.

![image](https://user-images.githubusercontent.com/101696552/164608352-db93a5ce-0750-4722-87f8-17faf867f6b6.png)

**Comment by nguyentvan7** [comment]
I still want to make this a floating bar, but can close for now
