### ISSUE TITLE
Can't Ctrl+V in editors in artifact upgrader

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2537]
https://github.com/user-attachments/assets/8458d0ea-ef2c-4c98-ac6a-7712c1a13f7a

Likely because the artifact editor(`allowUpload`) is capturing the paste event: https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/ui/src/components/artifact/editor/index.tsx#L404

**Comment by AiZm8** [comment]
I'd like to work on this issue
