### ISSUE TITLE
Auto remove ``` from start and end of pasted multiconfigs

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#2558]
For mobile users

https://discord.com/channels/785153694478893126/1311837962744369263

**Comment by Kirk-KD** [comment]
Would a more suitable approach be to trim everything outside the first and last curly brackets? I imagine messages like [this one](https://discord.com/channels/785153694478893126/1232741336692555877/1283472031865639035) would be quite annoying for mobile users too. Also should this be implemented for other JSON import forms?

**Comment by nguyentvan7** [comment]
Yea a gold standard would be some 'json extractor' util function, then it will be easily portable to all other json forms like db, multi-opt, team, etc

**Comment by Kirk-KD** [comment]
PR https://github.com/frzyc/genshin-optimizer/pull/2560

It's working now, but one concern I have is it currently doesn't notify the user that this feature exists. Should there be a permanent text in the form telling the user that the JSON will be automatically extracted from the input, or should the text only be displayed when this feature is in effect? Something saying like "You can paste the entire discord message, the relevant data will be extracted automatically".

**Comment by frzyc** [comment]
I don't think the user needs to be informed, since it doesnt change the "data" part of the data.

**Comment by nguyentvan7** [comment]
Won't an indicator at least help users not feel like they need to meticulously text select the config, and can instead Copy Text straight from discord?

**Comment by frzyc** [comment]
Its extra dev work + translation + UI bloat for non-actionable information for user.

**Comment by Kirk-KD** [comment]
I was worrying about the translation for such a small addition of information but I agree with nguyentvan7, there's definitely gonna be a lot of users manually editing their copy/paste since they don't know about this feature.

But this aside, should I implement this feature at other JSON importing forms? Like team import, database update etc.. If not I will mark the pr as ready for review.

**Comment by frzyc** [comment]
could carry it over to other forms, either in your current PR or create new PR.

**Comment by Kirk-KD** [comment]
This can be closed now right?

**Comment by nguyentvan7** [comment]
yurp fixed in #2560
