### ISSUE TITLE
Artifact parser fail to detect substat in specific situations

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2565]
More information in forum post: https://discord.com/channels/785153694478893126/1310819087101984768
![image](https://github.com/user-attachments/assets/fc9ebae3-4740-4039-a383-f1cffe9ea125)
![image](https://github.com/user-attachments/assets/00a55a6f-fb5c-4f99-bf7e-0b3a13382fdc)
Both images seem to be unable to parse the `DEF+21`.
From the local reproduction/debug, it looks like the substat region is correctly detected. This is likely an issue of parsing the result from the OCR output.

**Comment by legndery** [comment]
As my first code contribution, I would like to work on it. Let me know if anyone has picked it up or not.

**Comment by legndery** [comment]
The issue is for certain substats tesseract is returning `#` instead of `+`.  For example in the above images the DEF+21 is being returned as `DEF#21`
