### ISSUE TITLE
Element filter colour contrast makes them difficult to discern now text is gone.

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#260]
![image](https://user-images.githubusercontent.com/101696552/163801694-986fb22a-b342-47c8-81f1-bcce946f8a80.png)

**Comment by nguyentvan7** [comment]
![unknown](https://user-images.githubusercontent.com/36019388/164872684-5d3bc01f-1622-487c-a26b-7126ab71db8a.png)
My eyes (any many others) would also appreciate some more contrast for these buttons (any many others)
Changing the inactive (`secondary`) color to a dark blue that matches the background works nicely. Not AA contrast, but still much better. Would still need to think of something different for the active button color

**Comment by nguyentvan7** [comment]
Fixed with #348
