### ISSUE TITLE
Allow clicking on teammates on the build tab to swap to their build tab

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#264]
- This is more of a QoL change as it will allow faster optimization of each team member rather then opening the character selector each time.

![image](https://user-images.githubusercontent.com/101696552/163802700-8f61114d-4066-4f32-879b-af15e211685f.png)

**Comment by frzyc** [comment]
intuitively, this should go to the teambuffs tab, no?

**Comment by StainAE86** [comment]
> intuitively, this should go to the teambuffs tab, no?

Seems like a wasted redirect if it went to the teambuffs tab as it's already high enough on the page you could just click the teambuffs tab without any extra scrolling etc.

I think working like the teambuffs page already does is also intuitive - allowing you to change to the character you click on.
eg: clicking Mona changes over to Mona's page.
![image](https://user-images.githubusercontent.com/101696552/164866266-717066a7-676d-49ef-9077-129b80369618.png)

As a bonus - you could also allow clicking the weapon icon on the build tab to bring up the weapon edit/swap popup so you don't have to return to the equipment tab when doing quick weapon dmg calc comprasions.
