### ISSUE TITLE
Even at full width Yae's talents wrap when 'compare' is turned on

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#270]
![image](https://user-images.githubusercontent.com/101696552/163804229-c069e0c1-b193-477e-95d9-6333d4e589f8.png)

**Comment by StainAE86** [comment]
Since it might not be possible to stop text wrapping completely - can the comparison numbers be forced to stay on one line like so:

![image](https://user-images.githubusercontent.com/101696552/164408983-cdb5bd9e-8c19-490d-90cd-d2f7a9e9ff1f.png)

**Comment by frzyc** [comment]
@nguyentvan7 can you post some SS of the results of your fix?

**Comment by nguyentvan7** [comment]
See #425
