### ISSUE TITLE
Energy Recharge minimum filter cuts off text box well before columns re-arrange from 4 to 2

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#274]
This is "290" not "2"

![image](https://user-images.githubusercontent.com/101696552/163805044-df3b459b-2cbf-4602-b08c-aa34b07b2e0a.png)

**Comment by nguyentvan7** [comment]
Reopening because this is still an issue, and I will close it again soon, since I have a better fix for this now

**Comment by nguyentvan7** [comment]
jk just realized this is for the transition from 4 to 2 columns
