### ISSUE TITLE
Red text flickering when mousing over Character card

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#286]
Likely similar to, if not the same issue as #248 and #249

![CPT2204191613-757x693](https://user-images.githubusercontent.com/101696552/163937823-f8c6cbf2-1877-492f-b796-15680f62a44b.gif)

**Comment by StainAE86** [comment]
On closer inspection it's not just Red text. It's all elemental colour text but it's significantly more noticeable with red.

**Comment by frzyc** [comment]
Ive yet to be able to reproduce this. is there some sort of Nvidia filtering over your screen?

**Comment by StainAE86** [comment]
> Ive yet to be able to reproduce this. is there some sort of Nvidia filtering over your screen?

No nVidia filters. Does it in Edge/Incognito as well so isn't any Chrome extensions.
Tried hardware rendering on and off.

**Comment by nguyentvan7** [comment]
Can you still reproduce? I used to be able to, but can't anymore. Perhaps we can close this
