### ISSUE TITLE
Certain window width can result in ArtifactCardNano cutting off substats

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#290]
![image](https://user-images.githubusercontent.com/36019388/164361146-f69bd09e-4cb4-47ac-a07d-67ae4084fff1.png)

**Comment by StainAE86** [comment]
This should be able to be resolved by rearranging to 4x2 and then 3x2 sooner?
The final change from 3x2 to 2x3 doesn't seem to cut much, if any off.
