### ISSUE TITLE
[Feature Suggestion] Artifact editing improvements or autorolling. "Assume artifacts rolled xxxx"

### ISSUE THREAD

**Issue by coworo** [frzyc/genshin-optimizer#296]
There is a "Assume at least Lv x" option already but it would be so good if it also had an "autoroll" feature where it did good rolls for the character (eg hp for hu tao, def for gorou etc), so its easier to see which artifacts i should spend on. It doesnt even have to optimize or choose automatically, just "Assume artifacts rolled xxxx" below "Assume at least Lv x" in build screen would be gold too. Editing them one by one gets pretty confusing and tedious.

**Comment by frzyc** [comment]
The focus is GO is to offer an unopinionated way to provide tangible improvements to your account. This feature does not fall under this design consideration.
