### ISSUE TITLE
Genshin Optimizer index page has broken link to old build page

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#302]
Also poor @nguyentvan7 needs a credit. (but this whole page is outdated while the UI is in flux)

![image](https://user-images.githubusercontent.com/101696552/164816905-d934e83f-badb-42d5-9099-619d029bc7c8.png)

**Comment by frzyc** [comment]
Yeah all the old images in here as well. Lets use this issue to update the whole home page.

**Comment by frzyc** [comment]
This will probably be addressed with a general update of this homepage.
