### ISSUE TITLE
At certain widths character head breaks out of the gradient, mainstat gets chopped off and misaligned to background

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#305]
![image](https://user-images.githubusercontent.com/101696552/164886881-354afb2e-6c38-4df1-8c25-2fe365acb2f0.png)

**Comment by frzyc** [comment]
urgh this layout will never work for the full range of widths

**Comment by frzyc** [comment]
Will be addressed with work on #327
