### ISSUE TITLE
Allow clicking weapon in build preview to bring up edit popup 

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#306]
I'm not sure what your end goal is for the weapon in the build preview when it comes to possible future weapon optimization.
But it'd be nice to click the mini card on the build preview to bring up the weapon edit popup so conditionals could be toggled.
Widsith is an example where you'd want to quickly toggle between the buff options.

![image](https://user-images.githubusercontent.com/101696552/164892271-7e119ced-4298-443f-93d6-d598c976ee3b.png)

**Comment by frzyc** [comment]
if we ever do weapon optimization, this will show both old & new weapon. we could have the weapon editor show up for now...

**Comment by StainAE86** [comment]
> if we ever do weapon optimization, this will show both old & new weapon. we could have the weapon editor show up for now...

Might be unwise to let people get used to that now and then take it away from them later then.

Is it possible to elegently work the weapon conditionals into the build preview text thats under the mini cards?

![image](https://user-images.githubusercontent.com/101696552/164893308-42a918fc-6182-40a1-989d-b53dc4dec61f.png)

And to pre-empt the next request - you can no longer toggle 4-set conditionals in the build preview either.

![image](https://user-images.githubusercontent.com/101696552/164893365-d95d61ab-8047-4e39-a5f1-912a2358a1af.png)

**Comment by StainAE86** [comment]
![image](https://user-images.githubusercontent.com/101696552/206876692-be5a7ed4-1a7f-4ee5-89b0-b261ffd75058.png)

**Comment by frzyc** [comment]
I don't think its a good idea to "modify" the result. A generated build has context, in the conditions that the users configured to generate that result. Changing the result(changing the conditions after the builder) destroys the context. just copy the build to TC page and modify the weapon there.
