### ISSUE TITLE
Suggestion: Remove Tools page

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#308]
At a guess very few users actually use anything on the Tools page.
If some people do infact use the Server time or Resin counter there could be an enablable option under the Settings page to have a floating box that takes up some of the blank space on the website.

These box(es) would remain in the bottom corner while you change pages/tabs and scroll.
If you don't want them, can just disable them under the Settings page (would be off by default)

![image](https://user-images.githubusercontent.com/101696552/164952212-9896a17b-4cbb-41bc-aaf6-59c314e40cd8.png)

(I would compress these more for actual implementation. Just a quick n dirty edit)

**Comment by nguyentvan7** [comment]
This only works on a fully maximized screen. How should it be handled on smaller screens/mobile?

**Comment by StainAE86** [comment]
I would imagine the floating boxes would be **significantly** smaller so they could be usable on more display/resolution sizes.
On highly zoomed displays or mobile enabling them would just overlap a portion of the main UI.

The fact they would be optional and default off should be enough of a fix for those people who don't like that.

Also since other inventory management sites like seelie.me already offer server time and resin trackers I don't really envisage this currently being used much on GO.

Maybe this could be one of the first Polls on a newly created GO twitter account? _Does anyone use the resin tracker within GO?_

**Comment by frzyc** [comment]
Added linking of tools to home page in [`8.10.0` ](https://github.com/frzyc/genshin-optimizer/releases/tag/8.10.10)
