### ISSUE TITLE
Add theorycrafting mode to allow users to create different combinations of fake or standardized artifact sets

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#311]
Some users used to create 'fake' artifacts with useless substats to theorycraft artifact set effects and work out which artifact set they should farm for a particular character.

It used to be very easy to just edit the artifacts while they were equipped to the character they were testing to change over to and check different sets. Now you need to create 5 artifacts of each type and equip them individually or unequip, edit, re-equip making the processs tedious.

Instead of just re-enabling editing of equipped artifacts (which still could be done in the meantime?) How about making a new TC tab (enabled from under the Settings page) within the character page that allows users to set different 2pc/4pc sets and give them a certain number of allocatable rolls to allow simulating artifact set or baseline substats so users can TC standard or ideal builds for different characters in certain teams/playstyles.

I would imagine setting a artifact/substat combination under this TC tab would give you the option to compare directly to  another simulated build, to your current equipped build or to any newly generated (but not yet equipped) build.

**Comment by frzyc** [comment]
I was planning to make a theory crafting mode where you can "build" a character based not on artifacts, but number of rolls allocations. In theory you can pair this with set effects, so this will probably fall under that...

**Comment by StainAE86** [comment]
Here is a mock up of what I'm thinking.

- The Theory Crafting tab would have elements of the Equipment tab and the Artifact editor.
- You would be able to "Copy from" your current build to pre-fill all the details to then edit them. Or just create from scratch.
- You then have a toggle to compare your theory crafted build to your currently equipped build, a secondary theory crafted build or just turn the comparison off so you just see the resulting damage numbers for the theory crafted build.
- You can select a weapon, level and refinement then toggle passives. These weapons don't pull from your inventory. So anything you change/add doesn't effect your own personal inventory.
- You can select artifact sets, either 2pc or 4pc and toggle conditionals (if applicable).
- You can then select each artifact slot main stat and level. The level selector would be colour coded using the site standard for +0, +4, +8, +12, +16 and +20. The combined levels will dictate the minimum and maximum number of rolls and overall roll value of the build as a total.
- Finally you select the sub stats and amount of rolls for the build as a total. Much like you currently do when manually entering a single artifact.

Below that you have a secondary theory crafted build. Again you can chose to copy from your current equipped, or copy from above to quickly pre-fill so you can make minor changes for comparison purposes.

![image](https://user-images.githubusercontent.com/101696552/164964553-dc71002a-76fd-4107-a670-918470d19983.png)

Another useful thing would be to add the ability to compare to your theory crafted build directly from the Build tab's generated build preview:

![image](https://user-images.githubusercontent.com/101696552/164965371-fb147359-1fc2-4ebc-a341-17b865950e9e.png)

**Comment by StainAE86** [comment]
An additional idea. The TC tab could have an Import/Export feature that creates a .json of just the TC build.
This could allow KQM and other guide makers to provide their "standard build" as a file users can upload to GO and compare to their account.

**Comment by StainAE86** [comment]
Following on from the above comment - 

Some users have suggested GO could have the option to "pre-fill" the [KQM Standard](https://docs.google.com/document/d/1_UpwP0VziHehZVwdsD74wYuWD9pdSAknNVzs30U4vFE/edit) for Artifact rolls into this "TC tab".

However after looking into the [KQM Standard](https://docs.google.com/document/d/1_UpwP0VziHehZVwdsD74wYuWD9pdSAknNVzs30U4vFE/edit) I don't believe it's compatible as it's up to the theory crafter/guide writer to decide where they assign their 20 allocatable substats - which will of course be different for every character and playstyle.

The other difficulty is the [KQM Standard](https://docs.google.com/document/d/1_UpwP0VziHehZVwdsD74wYuWD9pdSAknNVzs30U4vFE/edit) assumes an average roll which is not natively achievable in GO.
The best GO can do is set 1x low and 1x high roll per substat which gives a comparable number.

![image](https://user-images.githubusercontent.com/101696552/164998167-287254ad-4c96-41f6-8487-59b0b1c1949c.png)
![image](https://user-images.githubusercontent.com/101696552/164998651-4151aa7e-8518-4df2-a6b9-bf69c348d47f.png)

As always GO shouldn't tell people how to play or build characters - only provide them the means to make that choice for themselves.

That's why it's important that the Import/Export of any "TC build" created using this TC Tab is independent of the user's main database. This would allow people to create, share and compare theory crafted character build data against their own account.

In the end the user may find that they already have a comparable build that's different to the suggested one in a guide they read/watched which saves them weeks/months worth of resin farming an artifact set they didn't actually need.

**Comment by StainAE86** [comment]
![image](https://user-images.githubusercontent.com/101696552/177109973-6392dc55-5096-4956-ab19-69251927ef5f.png)
![image](https://user-images.githubusercontent.com/101696552/177110471-5bb766c7-b3da-4e64-bad9-8bd0c3f2714d.png)
![image](https://user-images.githubusercontent.com/101696552/177110146-42ea9b8c-f56c-4fdf-a38f-1159db6e4f35.png)
