### ISSUE TITLE
Allow exclusion of specific 4-sets

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#323]
Allow users to exclude 4 set effects from builder (for shim) and remove 2-set effect selector

Currently in Genshin, 2-set effects are generally raw basic stats. The selection for 2-set effects should be left to the builder.

Need to provide a UI for user to exclude 4-set effects.

This basically provides UI/DB work for #320

**Comment by nguyentvan7** [comment]
Released in 8.8.0
