### ISSUE TITLE
Build delta display card

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#327]
The idea is to add another card in this row:
![image](https://user-images.githubusercontent.com/1754901/165729520-03586161-aa70-42c0-9cce-a2e37923960b.png)
It will show the stat delta of the artifacts, in `icon+delta` format. red is negative, green is positive.

**Comment by StainAE86** [comment]
![image](https://user-images.githubusercontent.com/101696552/165730061-641bfa0b-160c-4f28-9ac0-f36ffb82f6d2.png)

Similar to how the game does it?

**Comment by frzyc** [comment]
The general stat deltas are already shown, which is more informative than seeing deltas of flat and percent stats
