### ISSUE TITLE
Navigating via the bottom links resets the build tab to the top of the page

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#328]
![CPT2204282207-1544x1201](https://user-images.githubusercontent.com/101696552/165748995-fafb714f-2e15-4108-8fbf-6ac358c7c14d.gif)

**Comment by StainAE86** [comment]
After the 8.2.7 patch the Equipment tab now also resets to the top of the page everytime you return to it.

**Comment by frzyc** [comment]
I wonder if its because the placeholders when you switch are not the right size, so its temporarily making the screen "short", effectively scrolling you to the top.

**Comment by frzyc** [comment]
There isnt a easy way to fix this. the tabpages are either physically shorter during transitions, or unloaded. The build tab are taller, but harder to fix the height, since it lazy loads the builds, which makes it very hard to retain scroll information.
