### ISSUE TITLE
Suggestion: Make "Build" tab button and "Generate" button orange/yellow

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#330]
While the purpose of putting the "Build" page into the Character page as a tab was to force users to go through the correct flow of setting up a character it can be a little hard to find for a new user who is still learning the site.

By changing the colour of the "Build" tab button it would draw attention to it so they realise it's an important (if not the most important) tab.
![image](https://user-images.githubusercontent.com/101696552/166080864-1528f2dd-b3f1-43b0-b76c-2e05a042ec1e.png)

Also - now the new Build page is much more compact it can be difficult to locate the "Generate" button. Especially when it blends in with all the other green buttons. I suggest making it orange at all times (like when you have a high number of possible builds)
![image](https://user-images.githubusercontent.com/101696552/166080715-bc9482b4-4539-4919-af14-8c15111e1152.png)

These are changes that could be folded in with #319

**Comment by StainAE86** [comment]
Here too for consistency?

![image](https://user-images.githubusercontent.com/101696552/166084689-8b645e03-4fb7-4aca-be7d-ecf60442b748.png)

**Comment by frzyc** [comment]
The issue is that we are associating colors with a user, so "yellow" is "Warning", and "green" is "everything is A-ok". If the end goal is to get the generate button to be more noticeable, then I don't think changing the color makes it more noticeable, but rather make it confusing ("should i click on this button that has the warning color, but nothing i set indicate an warning?")

I would much rather get the build button to be more noticeable either via layout, or UX flow changes.

**Comment by StainAE86** [comment]
> so "yellow" is "Warning"

???
![image](https://user-images.githubusercontent.com/101696552/166133522-d12c3d42-7161-4a48-8b90-6638ee2d4135.png)

But as #334 changed the button text to "Generate Builds" most of the problem is alleviated. So this issue can probably be closed.

**Comment by frzyc** [comment]
> > so "yellow" is "Warning"
> 
> ??? ![image](https://user-images.githubusercontent.com/101696552/166133522-d12c3d42-7161-4a48-8b90-6638ee2d4135.png)
> 
> But as #334 changed the button text to "Generate Builds" most of the problem is alleviated. So this issue can probably be closed.

This was originally yellow because when the mainstats are assumed to be higher, the number would be yellow. but this conflicts with the color scheme...
