### ISSUE TITLE
Site filters are unintuitive

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#332]
The artifact page suffers the most, but it also extends to weapons and characters.

Part of the issue is the fact its difficult to discern what is "on" and what is "off" other than toggling them and seeing the result.
As mentioned in #319 the "off" state should be light grey rather than blue.

I suggest: All multi-select filters "default" state is changed to blue (to indicate they in a valid state, but can still be interacted with) and in this state show everything, rather than exclude everything.

When you select a single filter it will then exclude all others not selected by turning them light grey (to show they in an unselected state, but can still be interacted with) and only show the one you've selected (by turning green). Then you can continue to select additional filters by turning them green.

Default state (show everything)
![image](https://user-images.githubusercontent.com/101696552/166082621-6df87c02-7327-4bdf-b848-7d570113cb7d.png)

Filtered state (show only green)
![image](https://user-images.githubusercontent.com/101696552/166082635-f385df19-4ce3-4d25-996d-f671bc6bb8dc.png)

Same change could be made for the weapons/characters. With the addition of allowing more than 1 filter for the weapon/element type.

Default state (show everything)
![image](https://user-images.githubusercontent.com/101696552/166082743-f9acb337-3768-4f5a-8049-a25327b5a692.png)

Filtered state (show only green)
![image](https://user-images.githubusercontent.com/101696552/166082793-864fc642-c62b-42b3-811c-bb5ace9493ff.png)

Now that the Character page has been reduced in size - we're asking users to take advantage of the filter options so it would be nice to have more control. Currently I cannot make it show Pyro and Hydro, Sword and Polearm characters in one screen for example.

**Comment by frzyc** [comment]
I agree with the actions of #319. However, a "default" state of blue on togglebuttons is kind of confusing (introduces 3 states when its a on/off button). 

Character filter, imo, doesn't need flexibility of showing multiple elements or weapons. it should be a quick way to get specific element/weapons, allowing multiple would actually increase the time to get to the characters a user would want.

**Comment by frzyc** [comment]
Reopen Issue just incase you have more ideas. I do think some of the filters might not be initutive, but making them more complicated is imo not the solution

**Comment by StainAE86** [comment]
Making the inactive now grey as of 8.2.7 helps significantly.

But personally I don't think they're more complicated introducing a 3rd state. The site already defaults to "all on" (but in green).
My problem with this is green indicates a filter selection. But in the default state the user isn't _actively filtering._

Changing this to blue helps distinguish that you are "showing all" but not actively filtering. Then selecting a single filter turning it green and greying out all others makes it very clear whats going on.

Plus there are inconsistencies with how the logic of the artifact and weapon/character filters work.
This would remove those inconsistencies by making them function the same.

**Comment by nguyentvan7** [comment]
I don't personally think the blue semantic coloring makes things any clearer. All green makes sense imo since all the weapons are selected. I also dont think the user will associate blue with "default" and green with "my active filters". And that distinction doesn't particularly matter either

**Comment by StainAE86** [comment]
We still have this issue:

Default all on:
![image](https://user-images.githubusercontent.com/101696552/167220885-ce088807-c687-49d6-9972-88048968cd3e.png)

Default all on:
![image](https://user-images.githubusercontent.com/101696552/167221020-25c8b97d-d2d2-48f5-a13f-9b249140d2db.png)

Default all on:
![image](https://user-images.githubusercontent.com/101696552/167220822-47a26ee2-6474-46ec-9964-734cab23ee9c.png)

I think we should change all these behaviors to;

Default all on = blue
On first click of a filter:
Clicked turns Active = green (or elemental colour)
All others Inactive = grey
Can then continue to click additional filters turning them green / elemental colour one by one

**Comment by StainAE86** [comment]
More inconsistences:


> Default all on: ![image](https://user-images.githubusercontent.com/101696552/167220885-ce088807-c687-49d6-9972-88048968cd3e.png)

Clicked single filter:
![image](https://user-images.githubusercontent.com/101696552/167221336-ee685e0f-c6ce-4ed7-8504-e20857022035.png)


 
> Default all on:
![image](https://user-images.githubusercontent.com/101696552/167221020-25c8b97d-d2d2-48f5-a13f-9b249140d2db.png)

Clicked single filter:
![image](https://user-images.githubusercontent.com/101696552/167221388-61fa9a0f-b77c-494a-b54e-ff0a27aeee91.png)
