### ISSUE TITLE
Suggestion: Rename "Equipment" and "Build" tabs

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#333]
For new users these words can be confusing since within the context of the game a character's "Build" implies the combination of Weapon, Artifacts and even Talents to a degree. Also we don't have any direct connection with the word "Equipment". Lastly there is nothing in the description of the Build tab that signifies it is actually the Calculator/Generator/Optimizer.

My suggestion:

Rename "Equipment" to "Currently Equipped"
Rename "Build" to "Build Calculator/Generator/Optimizer"

**Comment by frzyc** [comment]
I think equipment is fine. The "build" button might be confusing, worth rename to `Optimize`?
