### ISSUE TITLE
Inconsistent 2-Set/4-Set artifact set effect layout

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#336]
Some have a title for the 4-Set effect:
![image](https://user-images.githubusercontent.com/101696552/166133832-a4be864c-8ccf-4566-894d-d340716cea96.png)

Others put the 2-Set bonus in:
![image](https://user-images.githubusercontent.com/101696552/166133827-a9a2d3de-1c98-4edc-8f1a-7ff52d193da7.png)

**Comment by nguyentvan7** [comment]
I'm redoing this part with my refactor of the sheet utilities #324 
Default conditional popup:
![image](https://user-images.githubusercontent.com/36019388/166133917-48fb8087-93a5-40b0-931f-4e47422baa0d.png)

Equipment tab (I'll try to fix the blank card #256 as well):
![image](https://user-images.githubusercontent.com/36019388/166133935-4894f41e-a7e6-4c53-be74-4080095b5535.png)
