### ISSUE TITLE
Suggestion: Change forced artifact 2-set/4-set drop down to a check box

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#339]
Reduces the amount of clicks required to toggle the 2-set/4-set selection.
Should help the awkward word wrap issue by removing the drop down "v" element.

Also the current selection doesn't capitalize the s in Set. But the titles below do.

![image](https://user-images.githubusercontent.com/101696552/166162576-4b348a72-4e02-42ec-8d7d-bd2c4340c7d0.png)

**Comment by frzyc** [comment]
I think at least for the future, the selection/exclusion of sets will be folded into the "Default Set Effects Conditionals" popup.(Rename to "Artifact Set Effect Config?"), so I'm not really sure if we need to devote dev time on this.
