### ISSUE TITLE
Build page UI elements missing padding and/or card

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#341]
I'm not sure if this was intentional, but this is what it looked like as of 8.2.7:

![image](https://user-images.githubusercontent.com/101696552/166408051-855bd89b-abdd-4f87-ba9d-07d6ab59222a.png)

Now the buttons/text boxes and drop downs for Build Constraints, Excluded/Equipped/Level Filter/Default Effects and Forced Set buttons are full size without padding like the Main stat filter has:

![image](https://user-images.githubusercontent.com/101696552/166408274-9462bca8-18ef-49ba-acf2-2664e2eb8a1a.png)

If it was intentional - the Force Artifact Set drop down shoulud be made to go the full width available at all times.

**Comment by frzyc** [comment]
The removal of the paddings are intentional, however, the artifact set dropdown should be full width.
