### ISSUE TITLE
Suggestion: Add ability to sort characters by priority

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#342]
On both the character index page and character popup.
Would also be good to have some kind of indication that they are on the priority list (like the fav/heart)
Could allow clicking this indication icon to bring up the priority list popup to make adjustments outside of the build page.

![image](https://user-images.githubusercontent.com/101696552/166411197-e4d75f0e-5a57-4293-91c2-3f740d505ef8.png)

**Comment by frzyc** [comment]
I think this confuses the actual definition of a somewhat niche feature. This would also conflict with existing sorting metrics like favorites, and complicate all the sorting algorithm.

**Comment by StainAE86** [comment]
Can we at least have an indication characters are on the priority list? (like the heart indicates they are on the fav list)

**Comment by nguyentvan7** [comment]
What's the purpose of the icon here? If you need to validate or check your priolist, I assume you would check from the Optimize tab, with the UI to edit and such there

**Comment by StainAE86** [comment]
> What's the purpose of the icon here? If you need to validate or check your priolist, I assume you would check from the Optimize tab, with the UI to edit and such there

I can't always remember who I put on the priority list. So having a quick visual reminder on menus like these that a character is on the priority list lets me make my choice faster. (who to move a weapon/artifact to, who to optimize next, etc)

![image](https://user-images.githubusercontent.com/101696552/167220422-e35a18ee-ec02-4ba2-a94c-93e8d4724936.png)
![image](https://user-images.githubusercontent.com/101696552/167220471-7677d9f4-910d-4be9-8182-b0e927b2747f.png)

**Comment by frzyc** [comment]
Adding an icon doesnt make sense, since whether a character is on the priority list is only applicable when you have the optimize/priority list open, which just adds confusion to other UI. Unless we somehow introduce a concept that would apply to the rest of the site, spreading priority list stuff to other UI will only confuse user and clutter up UI.

**Comment by StainAE86** [comment]
> Adding an icon doesnt make sense, since whether a character is on the priority list is only applicable when you have the optimize/priority list open, which just adds confusion to other UI. Unless we somehow introduce a concept that would apply to the rest of the site, spreading priority list stuff to other UI will only confuse user and clutter up UI.

I don't agree with this. The priolist has a strong overlap with what order you want to optimize characters in (to prevent giving the chance a lower priority character will take a new artifact - only to be taken by a higher priority character after).

Replacing, or agumenting the favorite system to allow sorting by priority across the entire site in all lists and menus would be ideal.

It's a QoL feature as characters on your priolist, and in that particular order are **by definition** _your priority_.
So you want them at the top of your lists to quickly select. Regardless which screen you're on.
The favorite system is nice. And you can favorite all your characters who are on the priolist - but they arent in order.

![image](https://user-images.githubusercontent.com/101696552/170783540-ab683fd0-bbb4-4ad5-8674-b75fa06029de.png)
![image](https://user-images.githubusercontent.com/101696552/170784944-e677b0c1-1cbc-4e7a-94e2-c57af787dad6.png)
(The ability to hide "new" / unowned characters on this screen would also be nice...)
![image](https://user-images.githubusercontent.com/101696552/170784493-908ba281-95df-4ab1-a8c3-2e4d1baba4ee.png)
