### ISSUE TITLE
Suggestion: Allow users to set how many cards to show per page

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#343]
Dropping the amount of Artifacts/Characters/Weapons that are shown per page has been great for load times.
While the filter options are fine to sort/find what you're after - some users would just like to have more on one page regardless of how long it takes to load.

Maybe have a drop down to the left of the page number links to set how many cards/tiles are shown per page in mutiples of 8 up to 48?

**Comment by frzyc** [comment]
Each breakpoint(page width) has different number of cards. This would be too complicated to implement and use.
