### ISSUE TITLE
Build page tweaks

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#349]
- The (i) info icon has a different font for Build Constraints vs 2-Set/4-Set.
- "Use Excluded" and "Use Equipped" have inconsistent unchecked colour states.
- Minimum Artifact level text box is not centre justified.

![image](https://user-images.githubusercontent.com/101696552/166627439-0964a425-3a00-4641-ab1e-46978ff09024.png)

- When checked, the checkbox for "Use Excluded" and "Use Equipped" justifies to the left unlike the Artifact 4-Set conditional.

![image](https://user-images.githubusercontent.com/101696552/166627676-c6aaf09a-7985-42a6-9fdc-5105063cfab6.png)

- It would be a good idea to add a title and (i) info icon above the "Default Artifact Set Effects" button to make the 4th column consistent with the others and allow for a deeper explation of the function. I suggest:
"Artifact Conditionals and Constraints (i)"
"Enable 4-Set Conditionals that you want the Optimizer to take into account when generating builds or force the Optimizer to use certain 2-Set or 4-Sets."

- The info tooltip for Build Constraints is poor english. Suggest  changing to:
"Set certain requirements that generated builds must confirm to.
eg: Generated builds must have at least 140% Energy Recharge."

![image](https://user-images.githubusercontent.com/101696552/166627881-bdf77101-46bf-49e1-8231-c71355c88a0e.png)

**Comment by nguyentvan7** [comment]
> The (i) info icon has a different font for Build Constraints vs 2-Set/4-Set.
Fixed in #348 
The rest remains untouched
