### ISSUE TITLE
Export and import functionality, or some other way of backup

### ISSUE THREAD

**Issue by diogovk** [frzyc/genshin-optimizer#35]
I'd like to contribute to your project, and the first functionality I'd like to work on, would be a export to json, and an import from json feature.

If I understand correctly you're currently using localStorage to store "the database", so it would be a matter of transforming localStorage into a json and downloading it.
And for importing, it would be a matter of parsing a json file, and setting localStorage to it.

Do you have any suggestions on how you'd like this to look from an interface perspective?

**Comment by brunnobb** [comment]
Totally agreed! We can also use Google account for automatic sync, same as genshin map.. This would make a great new feature

**Comment by LrkDev** [comment]
Hello all
As seen in Trello it's already a work in progress
There is as datadump branch with :
- copy/paste json
- download/upload json file

No planned Google sync I think

**Comment by frzyc** [comment]
@LrkDev is right. there is a dataDump branch with the feature complete. 
I do all the coordination for the development of GO on my discord, [https://discord.gg/CXUbQXyfUs](url)
If you dont mind, join up, get the "Adepti of Code" role from the #roles channel, and we can collaborate there.

**Comment by diogovk** [comment]
I see. I didn't realize there was a branch for that already.
Thank you for the discord link.
