### ISSUE TITLE
Suggestion: Change elemental filter/button colours to improve readability

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#350]
The current element main stat filters on the build page are quite hard to read in either the grey or the green state.

However we already have a case on the site that does this differently, the elemental filter on the character index page.
![image](https://user-images.githubusercontent.com/101696552/166630467-4506209f-aeb1-4d65-8005-2a45c309152d.png)

I suggest we make the element icons white and use these colours inplace of the green "on" state for the main stat filters:
![image](https://user-images.githubusercontent.com/101696552/166630440-4e44ae2a-50ec-42ee-bcaf-222c019ac19f.png)

This method would also help significantly for the Swirl conditionals on Anemo characters and the VV set.
![image](https://user-images.githubusercontent.com/101696552/166631184-f2d2ea83-4bc2-462b-a527-67fb1a263598.png)

**Comment by frzyc** [comment]
Might need to update `IConditional`, to instead of only `name`, change to 
```
label:{
  name: Displayable,
  variant: string
}
```
To allow further customization

**Comment by frzyc** [comment]
You might have noticed, that pysical dmg button will be grey, even when activated. It might be a case where it goes "green" on active.
