### ISSUE TITLE
Unable to scroll Swap Artifact popup

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#378]
Maximum of 12 on the popup and unable to scroll the selection.

**Also would be nice if filter selections saved its last used state:**
So if you select Level: 16+, Location: Inventory , Set: Emblem when looking for a Flower, those settings would still be there when you look close the popup and then look for a Feather.

**Comment by frzyc** [comment]
Probably won't be able to save state coherently, not only its a messy database change, but generally filters might not carry over from one artifact search to another
