### ISSUE TITLE
Export data with mona-uranai format

### ISSUE THREAD

**Issue by Pozolo** [frzyc/genshin-optimizer#386]
I mainly use that website for the artifact potential feature, I like the user input they have there.
But it's terrible to update the results, so I wanted to update them in your page with the scanner and then export the .json there to check if I should keep upgrading an artifact based on those calculations. 
Thank you.

**Comment by frzyc** [comment]
Why don't you request them to accept GOOD format? so you can upload the scanner data directly to their site without having to use Optimizer as middleman?

**Comment by Pocq** [comment]
They don't have a build in scanner, I guess I could also ask there. But I have not seen any English request there so i though trying here first. Also yours checks and replaces copies or highly possible upgrades, something that I think is not there so you end up with copies.

**Comment by Pozolo** [comment]
They don't have a build in scanner, I guess I could also ask there. But I have not seen any English request there so i though trying here first. Also yours checks and replaces copies or highly possible upgrades, something that I think is not there so you end up with copies.

**Comment by frzyc** [comment]
I would say get them to use GOOD. I don't think we will support mona-uranai format.
https://github.com/wormtql/genshin_artifact/issues
