### ISSUE TITLE
GO webpage not showing anything

### ISSUE THREAD

**Issue by lnfel** [frzyc/genshin-optimizer#387]
I might be wrong here but I used GO in the past on PC and it worked really well. I am on a mobile device atm and I tried accessing the GO website but nothing shows up, just a complete blank white page.

**Comment by StainAE86** [comment]
@lnfel sounds like your mobile device still has an old GO database in its browser cache which is no longer supported. Try clearing cache and the site should become accessible.

**Comment by lnfel** [comment]
You are right, it works now thank you!
