### ISSUE TITLE
<undefined>Electro

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#392]
Error in Kazuha's talent descriptions 

![image](https://user-images.githubusercontent.com/101696552/169248992-56183f06-28ef-4842-99aa-81408ac1035d.png)
![image](https://user-images.githubusercontent.com/101696552/169249054-136de20b-6376-4696-b019-4770e700981d.png)

**Comment by Cupcak3** [comment]
![image](https://user-images.githubusercontent.com/8845977/169669991-215790b0-aefc-483a-9276-8fa4f406891c.png)
present in all descriptions that mention electro dmg

**Comment by nguyentvan7** [comment]
I thought it was my fault when making the sheets, turns out I can blame Frzyc :)
