### ISSUE TITLE
Build Loadouts

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#401]
![image](https://user-images.githubusercontent.com/101696552/169744758-54c190e7-6184-47a3-b0d9-3ba48d6bb1b0.png)

Adding my thoughts to this:

I would expect when you generate builds there would be a second button to "add to loadout" rather than equipping.

![image](https://user-images.githubusercontent.com/101696552/169745818-4772a5c2-beb8-43d7-893c-9bbcbdfd5118.png)

And then the "Loadout" tab would operate much like the build preview when you generate multiple builds.
So you would have hitmode and comparison toggles across the top, see the nano artifact cards with the current location of the artifacts and then the build stats below.

The biggest difference would be the addition of the abililty to rename the loadouts and then delete them.

![image](https://user-images.githubusercontent.com/101696552/169747177-ab4cebe4-ae95-4642-80b8-ef3a28a5b116.png)

This could tie into - or at the very least use a similar system to the TC mode tab suggested in #311 
With the ability to hold different "builds" (theoretical or not) and compare them to equipped and eachother.

**Comment by frzyc** [comment]
So a loadout is defined as an entirely separate character, with its own conditionals, weapons, artifacts, teambuffs.
Im gonna drop a few thoughts I've had.

1. The UI for editing a loadout is exactly the same as that of the "main" character(need to edit overview, talents, teambuff), so you need to make the UI more distinct to the user that they are editing a loadout. loadout needs to be named, so maybe make the input box very distinct.
2. A loadout can be a TC build? then the overview page can be replaced with the theorycraft tab UI. Theorycraft tab can be removed.
3. comparing UI changes from current (new stats | against equipped) to a dropdown of all loadouts.
4. New UI to select between the main/loadlout/tc character. a dropdown for small selection, a button popout that shows artifact/teams for big selection.

**Comment by StainAE86** [comment]
Okay so there's been some talk on what the minimum viable product is for this and how far down the rabbit hole we can go.

I think at very least what people want is the ability to "hold" a previously generated build, but not actually have those artifacts (and weapon) equipped.

So the character level, cons, talents, conditionals, team state and optimization settings used to achieve that build are not saved within the loadout. There are no damage numbers, no stats. Just the Weapon+Artifacts, the name you gave it, the ability to copy it to the TC tab, equip it (and delete it)

![image](https://user-images.githubusercontent.com/101696552/193789132-be6438be-2956-487e-b9bf-3b93c0b18925.png)

That way you can leverage the TC tab to compare two builds. Your currently equipped one vs one of the loadouts you're holding.

**Comment by StainAE86** [comment]
The other idea would be to have a several copies of the same character. Each with their own unique character level, cons, talents, conditionals, teams and optimization settings. So when you enter the character overview page there will be the option to "swap" to different versions/loadouts of that character (like how we can currently "swap" between 4 different databases)

The question then becomes how do you control the equipped state of the artifacts? My thought would be that when you configure a character and generate a build instead of "equipping" the build - you would "generate loadout" so that entire character/optimization state is saved as the loadout. But none of the artifacts actually equipped/moved from their current position.

But since we're in a "loadout" state now the overview page etc will show these new artifacts _as if_ they were equipped. But still not actually equip them. That way can then swap between the different versions of the same character but the artifact status doesn't get updated until you actually click "equip" as you do now. IE; even if you "swapped" if you closed that character page and re-entered it, it would revert to the loadout that is _actually_  equipped.

The next question is how do you handle team mates? The simple option would be to just take the team-mate "as-is" with their current build just like the system currently does.

The rabbit hole goes much deeper if you want to have different "versions" of the team mate depending on the loadout youre creating. You _could_ setup a loadout for that team mate before hand and then you would have multiple versions of that character to pick from as a team mate - but how do you control artifact locations? You would have to implement some kind of conflicting artifact warning.

For example if your current Bennett is equipped with 4pc CW, but when adding him as a team-mate you want to select his 4pc NO loadout to use - but you already have another character in that team who is equipped with one of those NO pieces Bennett's loadout includes. This would have to trigger a conflict warning.

One potential way around this is allow a TC build to be "saved as a loadout". Instead of creating a loadout from your actual artifacts you could setup a character level/cons/talents/conditionals etc and then make a TC build for a "Standard NO Bennett" for example. That way when you pick Bennett as a team mate you just select his "Standard NO Bennett" you added to his loadouts.

A final question would be - if you edit a loadout, be it a real one or a TC tab one. Be it character levels/cons/talents/conditonals/weapon/artifacts(stats) does that change the resulting damage numbers for any character that is using the edited character's loadout as a team-mate? And yes I think it must.

**Comment by flygon727** [comment]
Would like to add that even if the entire feature ends up being too complicated or annoying to implement, at least having the options to save builds/artifacts as a preset/loadout would be helpful as well.

Like for example I play my Nahida in 2 teams, 1 where she doesn't need 4p DW and one where she does need it. So I would like to just click one or two buttons to swap the builds instead of having to change each part of the build manually.

Ideally these builds would include weapons as well as artifacts in them.

Also one of the issues with implementing each build as a separate character that might pop up is that when the user wants to update say their character or talent levels on a particular character, would they have to change them for every copy of that character? Or would changing it in the character tab for any one of them reflect the corresponding changes in the rest (maybe this could be a toggle as well in case people wanna test out the same character with different talent levels for some reason).

Thanks for the hard work.

**Comment by EffortlessFury** [comment]
I'm not super familiar with the code base, but assuming each artifact and weapon has a generated unique id, a loadout at its simplest could simply be an object, owned by a parent character, that stores the teammates selected, as well as that character and their teammates' conditionals. and the unique ids of weapons and artifacts that are equipped at that time. Ignoring the comparison aspect for a moment and focusing only on the action of swapping between loadouts, would doing so not simply be equipping each character on the loadout with those saved weapons and artifacts, then setting the primary character's Team Buffs page to those other three teammates?

As far as comparison goes, I can see the benefit in making comparisons between different constellations/talent levels to decide whether you should upgrade them; however, from what I understand of the Theorycrafting tab as it exists today, that's not something it takes into account as of now. The way I understand how the TC tab works atm (and correct me if I'm wrong) is that it utilizes the current state of the character and allows you to directly tweak each stat's value, as well as set those values to what they currently are based on your current equipment. Theoretically, another button could be introduced to "copy from loadout," where the stats are set based on the equipment in one of your saved loadouts. I think introducing the aspect of changing the Talents/Cons would be the most significant change to implement as the TC page probably doesn't worry about those being mutable.

Considering the possibility of conflicts where another character has an item equipped that is needed for a loadout you're using, loading that into the TC tab wouldn't be a destructive action, but attempting to equip the loadout would be. Theoretically, a loadout could store only the weapon and artifacts for the parent character as a minimum, and if a conflict arises when equipping a loadout, you can be given the option to create a new minimum loadout for the conflicting characters before making the equipment change?

Just my two cents as an observer, hopefully they're useful thoughts to consider?
