### ISSUE TITLE
Show a list of database errors that have been fixed on import

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#405]
GO already fixes several issues on import, such as:

- Invalid weapons on characters
- Multiple artifacts of the same slot on characters

It would be good if when these situations occur the user is notified that this happened so they can self diagnose possible scanner errors.

Other things that could be added to the warn-list (but not fixed on import) could be:

- Impossible artifacts sets (eg: 5* Gambler)
- Impossible sub stats
- Multiple copies of the same artifact

**Comment by frzyc** [comment]
Already show "invalids" on import, will add additional validation metric as suggested

**Comment by nguyentvan7** [comment]
We already list the artifacts and weapons that errored out, it would probably be too much work/effort to add new strings and logic for this
