### ISSUE TITLE
Bug: An additional blue "X" appears on the autocomplete/typing dropdown

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#406]
It doesnt appear when you're not moused over it.
Also doesnt appear if you mouse over the white "X".

![image](https://user-images.githubusercontent.com/101696552/170859962-7b72fad1-c5d1-4705-a81a-3e9dbf9f194e.png)
![image](https://user-images.githubusercontent.com/101696552/170859970-eb088b87-a0c5-4fd1-891f-33b8a656b545.png)
![image](https://user-images.githubusercontent.com/101696552/170859999-0332b152-04f6-4fa8-9abf-b9f187bcc41c.png)
![image](https://user-images.githubusercontent.com/101696552/170860168-d44341bb-1a2a-427a-b009-ced0a53487a5.png)
![image](https://user-images.githubusercontent.com/101696552/170860118-c3246f30-1d15-4fdc-9f86-00a0dee09452.png)
![image](https://user-images.githubusercontent.com/101696552/170860041-01e75090-44e0-4923-97e3-acf8d41dc140.png)

**Comment by nguyentvan7** [comment]
This is caused when the `renderInput` for `Autocomplete` doesn't have `multiLine` flag specified. And I have 0 clue why since the `TextField` component does not normally have this blue x

**Comment by frzyc** [comment]
Fixed in `8.6.1`
