### ISSUE TITLE
Is it intentional that the artifact dropdown no longer groups by rarity? 

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#407]
![image](https://user-images.githubusercontent.com/101696552/170860906-259088e6-17e2-4aab-97fc-36388f0181d4.png)

**Comment by nguyentvan7** [comment]
Hm, I can probably(TM) add back the grouping and rarity headers

**Comment by frzyc** [comment]
https://mui.com/material-ui/react-autocomplete/#grouped
