### ISSUE TITLE
Bug: Artifact piece name briefly indicates "Unknown Piece Name" on first load/reload

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#410]
![image](https://user-images.githubusercontent.com/101696552/170861576-0db2a836-a3f2-419c-84fc-e2d848314954.png)

**Comment by nguyentvan7** [comment]
How brief?

**Comment by StainAE86** [comment]
> How brief?

About a second

**Comment by frzyc** [comment]
seems about right, the site doesnt load everything at once, so the time between its initial start to loading all the asset will take some time, and its generally a good idea to have placeholders for content(which you see above), instead of showing nothing.

**Comment by nguyentvan7** [comment]
should it be a `Skeleton` instead of a string?
