### ISSUE TITLE
Multiselect filters now close the dropdown after every selection

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#426]
It used to stay open so you could choose several selections without having to re-open each time.

Is this a bug? Or intentional change of it's function?

![CPT2206031828-1540x634](https://user-images.githubusercontent.com/101696552/171818330-53d1dde9-3908-4324-acba-f09e1693a378.gif)

**Comment by nguyentvan7** [comment]
`disableCloseOnSelect`
