### ISSUE TITLE
Suggestion: Add 3rd "Crit" substat filtering option

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#428]
So when setting a substat filter you can find artifacts that have Crit Rate _or_ Crit DMG.
Lets users look at and compare all potential good artifacts in one filtered page rather then swapping between the filters.

![image](https://user-images.githubusercontent.com/101696552/172025794-36d82567-367b-4fc8-8aa2-baf9edbfdab7.png)

Seelie already does something similar when setting your Artifact farm targets:
![image](https://user-images.githubusercontent.com/101696552/172025858-52943a36-af53-4f8f-a3c8-c60260e52fb5.png)

**Comment by frzyc** [comment]
so you want a "OR" feature, that if any art has at least one of the substats in the filter, it gets passed through?
![image](https://user-images.githubusercontent.com/1754901/172067943-fad569bc-53aa-4ad4-9e89-4c84607fa352.png)

**Comment by frzyc** [comment]
could just add a "OR" button to the right, but it be hard to explain

**Comment by StainAE86** [comment]
> so you want a "OR" feature, that if any art has at least one of the substats in the filter, it gets passed through? ![image](https://user-images.githubusercontent.com/1754901/172067943-fad569bc-53aa-4ad4-9e89-4c84607fa352.png)

an OR would be nice but only if you also have an AND.

for example I might want to look for CRate OR CDmg AND ATK% AND ER
so I get any artifact with CRate/Dmg, ATK%, ER - rather than ER, DEF, HP if it was just OR logic.

**Comment by nguyentvan7** [comment]
Could just be a toggle button that swaps between OR/AND

Or we could revamp the entire thing and allow the user to enter in a custom boolean logic formula
CRate AND (CDmg or ATK) AND NOT HP
:)

**Comment by StainAE86** [comment]
> Or we could revamp the entire thing and allow the user to enter in a custom boolean logic formula CRate AND (CDmg or ATK) AND NOT HP :) (joking of course)

DO IT VAN

![gachihyper](https://user-images.githubusercontent.com/101696552/172068654-b206ec58-73cc-4e3d-8fec-ecb5f91028f0.gif)

**Comment by frzyc** [comment]
Wouldn't ranking by RV with these selected for RV be the best workaround?
