### ISSUE TITLE
Suggestion: Generate for all characters at once

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#439]
When you get a new or upgraded artifact often times it can be an upgrade for multiple characters

Currently the process is;
You select your highest priority (favorite character) first and re-run the optimization target to see if they want that artifact
Then you go down your list of importance until you find a character that wants it

I propose a "Generate All" option that is based on your build settings across all characters (or an op-in selection of characters)

It would then provide a list of all characters that can benefit from the new artifact(s) and show a comparison of the damage increase on each optimization target - something like this:
![image](https://user-images.githubusercontent.com/101696552/173314580-0025b6f8-e266-4245-b20b-853d15921b52.png)

You would then select which character you feel benefits the most from the new artifact and re-run the "Generate All" to see if the newly freed up artifact(s) will now be the best option for others

This would then slowly shuffle/filter the artifacts down until everyone has their "new best" option and the list is empty

I understand that "Generate All" could be a taxing process. But a correctly filtered build setting page (main stats, priority list etc) usually only takes half a second to 2 seconds to complete - so even if you opted 20 characters into this list one optimization run would only take 30 seconds to minute

**Comment by StainAE86** [comment]
![image](https://user-images.githubusercontent.com/101696552/173316681-b5249400-65b2-4c17-b5ec-b7fcef00614b.png)

**Comment by frzyc** [comment]
Implementation wise:
- Hard to strip out the build from the build tab,
- very hard to make a new UI that does this, and display coherent information
- Characters are not designed to be able to be optimized in serial, but in isolation.(conditionals locked to context, characters are not detached from the team, assumptions for one build dont necessarily carry over to all future builds)

UX:
- Saves a few clicks, but actually increases overall workflow, while obscuring what its actually doing, and the end-user has less control over the results.
- Interdependencies between characters will make this really difficult to be a predictable feature.

Personally:
- Bloody hell how lazy can you be?
- no
