### ISSUE TITLE
Element damage bonus has poor visibility on ArtifactCard

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#440]
![image](https://user-images.githubusercontent.com/36019388/173659069-7c25304d-0203-4768-87c8-2a0e006ef45f.png)

**Comment by frzyc** [comment]
yeah i was thinking of adding a background to it, like we have above with the artifact name. However, i couldnt find a nice contrasting color

**Comment by frzyc** [comment]
it could be the case that we change the background color itself? for elementals, cryo background + white text

**Comment by nguyentvan7** [comment]
I was thinking we could copy what the artifact card nano does, and have a colored Chip behind the main stat

**Comment by nguyentvan7** [comment]
Yep, I was a bit hesitant to make the change because it would make the artifact card look more different from in-game. But since the piece name has the background, I feel more comfortable making the change

**Comment by nguyentvan7** [comment]
Fixed in 8.14.0
