### ISSUE TITLE
Suggestion: Logic change for multiselect filters

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#447]
Making a new issue so it doesn't get lost within #332

Change the logic of multiselect filters to be as follows:
**CAPS = ON(displayed)
lower = off(hidden)**

Default state is all on
ABCDE
Click "C" to turn off all others
abCde
Click "C" to turn all back on
ABCDE
Click "D" and then "e" to multiselect filters
abcDE
Click "a" and then "E" to turn on "a" and turn off "E"
AbcDe

This would make for more intuitive artifact piece filtering and would allow people to multiselect character element or weapon type filters too. Making the Artifacts, Weapons & Character filters consistent across the site

![image](https://user-images.githubusercontent.com/101696552/173780296-34017d4c-a8dd-4278-932b-e68c0e877bfa.png)

**Comment by frzyc** [comment]
+ when abcde -> ABCDE so that there is no "all off" state
