### ISSUE TITLE
Suggestion: Tweak to "bonus stats" on Overview and Optimize page

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#450]
Bring the "reset" button inline with the rest of the site by making it red when a stat has been edited:
![image](https://user-images.githubusercontent.com/101696552/174004632-a71b9970-dbc3-4c59-a5ae-61212bbc8eb3.png)

As mentioned in #251 make edited stats bold. But also add a single reset button next to the Edit Stats button to quickly reset all:
![image](https://user-images.githubusercontent.com/101696552/174005008-578e0ecd-6ed6-4613-b924-d1a195222046.png)

Then instead of #442. Add the teambuff and bonus stats as the new 4th column:
![image](https://user-images.githubusercontent.com/101696552/174006471-cb9b2d35-392e-4128-94d9-241a26f8e38d.png)

**Comment by frzyc** [comment]
Not relevant due to recent `8.14.0` update.
