### ISSUE TITLE
Replace character page with condensed version

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#459]
While the character cards look nice, there is a lot of unrequired infomation for an index page which slows down navigation.
It prevents more characters from being listed on the index page which requires scrolling/filtering to find the character you are after.

Suggest just replacing it with the existing condensed character select pop-up,
but with the addition of "add new" button and the quick links to jump directly to the individual tabs.
![image](https://user-images.githubusercontent.com/101696552/175766641-7a77b05f-791f-41a5-8b29-7ecbb033bf6e.png)

**Comment by frzyc** [comment]
With a more condensed selector #636 accessible both from the character index page and character-specific page, this is now unnecessary.
