### ISSUE TITLE
Favorite characters are sorted above NEW characters in the add character modal

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#463]
https://discord.com/channels/785153694478893126/787340960173391903/990346881815175268

NEW characters should always be on top

**Comment by StainAE86** [comment]
Tagging onto this

![image](https://user-images.githubusercontent.com/101696552/182014851-4fa2e108-b002-4492-b56d-d9f3cb706c10.png)

**Comment by frzyc** [comment]
> Tagging onto this
> 
> ![image](https://user-images.githubusercontent.com/101696552/182014851-4fa2e108-b002-4492-b56d-d9f3cb706c10.png)

should be a separate issue.

**Comment by frzyc** [comment]
I think we can modify the sorting logic, so that "new" and "favorite" are both sorting, and in this case, it would be "new" with "favorite" tiebreaker. Might be a case for multiple tiebreakers, so tiebreakers should be an array...

**Comment by nguyentvan7** [comment]
I was thinking the same thing in regards to updating tiebreakers to be more comprehensive

**Comment by frzyc** [comment]
looks like you have a way forward, i expect PR at the end of the week.
