### ISSUE TITLE
Weighted Roll Value

### ISSUE THREAD

**Issue by balthanon** [frzyc/genshin-optimizer#472]
This is an enhancement request for the Roll Value options in the Artifacts tab; specifically where you are able to enable and disable them or somewhere in that vicinity.

![image](https://user-images.githubusercontent.com/5367358/177084102-7aa94bb0-427e-41cf-9a53-fbc1880456ae.png)

This tab is good for surfacing artifacts that might be worthwhile to attempt leveling up, however, one of the things that I would really like to do is actually be able to modify the roll value with a bit more granularity than simply including or not including the specified values.  I think it would be beneficial to actually be able to specify a weighting for a given stat when you're sorting and then simply have the roll value multiplied by that for calculating the totals.

As an example, in a standard DPS character, I might weight crit rate and damage at a weight of 2, atk% and energy recharge at 1.5, and elemental mastery at 1 with the others turned off.  In that case, an hp, hp%, 5.8 atk%, def artifact would actually register as 150% roll value rather than the 100% while a similar artifact with 4.1 atk% would register as 105%.

**Comment by StainAE86** [comment]
The issue here is you're asking for a completely different feature.
"Roll Value" is a metric of how high or low a substat has rolled. Not how that roll contributes in comparison with another roll.

So it would have to be designed into a new feature - which opens a new can of worms.
Do you just let the user set their own weight value? But we don't give the users the means to determine how much different stats contribute so how do users know that the weight theyre using is accurate? It would likely turn into an echo chamber of "Crit Value" that the community is already stuck in.

Once you really start looking at how one substat compares to another it becomes quite involved as none of it is linear and it is based on a characters level/basestats/artifact set/rarity/level and how much of other stats they already have in a build.
You can't always say that Stat X = 90% of Stat Y.

Also I have touched on a similar idea in issue #317 where it would display a total RV for the entire build of a character.
This could somewhat be used as a means to gauge how well invested a character is.
Since after Optimization the character is equipped with (I assume) the best build possible for your combination of artifacts.

If then the total Roll Value of that build is 2550%/4500% for example - that would mean you have 30 medium rolled substats out of a possible 45 max rolled substats. Indicating while you have your best combination currently equipped.
You have 15 "wasted" substat rolls and several "low rolled" substats that could be improved.

Also if you're purely after this feature to find artifacts to level up - you may be interested in #430 which is a modification pending review to allow the Optimizer to display the probability of certain artifacts being an upgrade over what you already have.
![image](https://user-images.githubusercontent.com/101696552/177090152-a4d70ecd-ea47-48f7-a7fd-fc578c982c63.png)

**Comment by tooflesswulf** [comment]
Since you're linking to my ticket, I'll drop a link to a demo site you can play with such a feature on.

https://tooflesswulf.github.io/genshin-optimizer/#/UpgradeOpt

**Comment by balthanon** [comment]
I'll check out #430, it sounds a lot like what I'm looking for here-- and yeah, this is primarily me being interested in finding good artifacts to attempt leveling up.  That is by far my biggest headache at the moment, optimizing the artifacts I have assigned is important, but getting new artifacts and choosing which to keep, which to junk, and which to attempt leveling up right now takes far more time than any other "maintenance" activity in the game and means I'm almost always hovering at around 1500 artifacts outstanding.

Roll value, while technically measuring exactly what it says, is a decent arbitrary number to measure how "good" an artifact is if you have a means of tweaking it for a given type of character.  If I could select a character and it provided me with the optimal weighting for the character's substats in a given role instead of me choosing them, then great.  The manual weighting just seemed significantly easier to implement while having a decent opportunity to surface generally good artifacts.  The optimizer portion of the website does a moderately good job of showing some of these if you have it set to max the level to 20, but leveled artifacts that already rolled well are going to have a clear edge in being assigned (which you want honestly.) 

(I do also have a few issues with some of the builds that get suggested for characters that place equal weighting on multiple talents like Klee, but that's another issue and I need to dig into the tool a bit more to make sure I'm not missing something there before delving into that.)

**Comment by frzyc** [comment]
I don't think its a good idea to add weights into RV, since RV depends less on the value of the actual rolls, but rather the maximum roll values. A lot of users have trouble grasping that, and adding another layer of complexity by making the users inject their own numbers would compound the issue.

**Comment by balthanon** [comment]
Yep, makes sense.  (And yeah, maximum RV value is what I use for just sorting like this, not the base roll value-- didn't think to specify that.  I'll be playing around with #430 to see how that works for what I'm aiming for.  It looks like it should do a decent job if I tweak the settings on the artifacts it's trying to surface.)

**Comment by StainAE86** [comment]
I think you've misunderstood what frzyc was saying about maximum roll value. Its not about future rolls, it's about the rolls you currently have compared to what they could have been.

For example a lvl12 4line start artifact with 3 low rolls into critr would have a RV of 210% if you only filtered critr, but it could have been 300%.

That's all RV should be used to determine.

Also I'm curious what settings you think you need to tweak on the tooflesswulf branch? It takes your optimisation target and provides you a ranked list of other artifacts in your inventory that could be an upgrade.

**Comment by balthanon** [comment]
I'm not misunderstanding what the statistic is explicitly displaying.  I just think it's more broadly applicable for comparing artifacts for myself personally.  It basically adds an additional dimension to just writing a program for myself that sorts based on a straight manual weighting because it's taking into account the actual values I already have as well as what it could theoretically roll into, which I probably wouldn't have bothered with.  RV does the job of abstracting the stats into a standard value that is the same across all of the stats, at which point I can say "I don't value these flat scores at all, and I value atk%, hp%, and energy recharge more than the base roll value actually indicates".

I can understand not wanting to try and force it to serve two purposes in this case and expecting it to cause confusion though.  I'm looking at this outside of the context of an individual character in some respects, which honestly doesn't mesh particularly with what the site is trying to accomplish.  I'm basically just trying to identify generally good artifacts that might be useful on a variety of characters.

For the tooflesswulf branch, it's the optimization target that I need to tweak in part.  Basically, it's more playing with the optimizer in general rather than specifically on that branch.   For instance, unless I'm missing something, the optimizer can't choose multiple talents, so I still need to go through and identify the most broadly applicable one for each character.  Artifact set configuration as well probably; even ruling out rainbow sets and turning off all set bonuses other than Husk, Bolide, and Petra for Itto, for instance, it's surfacing a bunch of stuff that isn't any of those sets as his best options.   It's very difficult to believe that any amount of substats is going to offset 54% Def and 24% Geo damage for him given that I have him in a rainbow set right now.   That is probably at least partially because 4 set bonuses allow for 1 offset piece though too, and none of his artifacts are fantastic at the moment, since I can drop the same settings into the general optimizer and it does pull back a Husk set for him.

**Comment by StainAE86** [comment]
>  For instance, unless I'm missing something, the optimizer can't choose multiple talents

It can't (yet). But you can get a pretty good approximation by setting minimum levels of other stats such as EM to maximize a characters vape and non-vape talents together for example.

>It's very difficult to believe that any amount of substats is going to offset 54% Def and 24% Geo damage for him given 

This comes down to your optimization target. If the toofless branch is recommending an artifact that breaks the set - that is infact a better result for that optimization target even if the set is broken. But I see where you're coming from in regards to set effects that don't specifically benefit the optimization target but you still need - VV is such an example.

**Comment by balthanon** [comment]
> This comes down to your optimization target. If the toofless branch is recommending an artifact that breaks the set - that is infact a better result for that optimization target even if the set is broken. 

In this case, Itto isn't actually in the set yet, so that might be an issue here too.  It isn't really "breaking" the set if he doesn't actually have the set bonus currently.  (Quick test reveals that is the case actually.  Swapped him into the first set that the optimizer recommended and now all of my upgrade targets are husk.)  My expected behavior was that it would try and surface the best artifacts to get the set bonus as well.  It probably doesn't help that my Husk artifacts are terrible so far either. :)  I got my Kokomi and QiQi artifacts pretty quickly, so I didn't really build up a decent base.

> It can't (yet). But you can get a pretty good approximation by setting minimum levels of other stats such as EM to maximize a characters vape and non-vape talents together for example.

I've been doing a bit of that with minimum stats, though mainly on ER at this point.  I'll have to experiment with it a bit more here.

That does raise another question I had-- do you have any plans to build in anything around ER at this point?  It seems like you might be able to estimate how much ER you need to burst off of cooldown, for instance.  I've basically been going to build guides to get generally applicable ER targets, but they're not always out there.  Since you actually allow team mates to be set, it seems like you should be able to (roughly) estimate how much ER is needed for keeping a burst up based on average particle generation.

Getting a bit far afield from the original issue here admittedly. :)

**Comment by nguyentvan7** [comment]
> In this case, Itto isn't actually in the set yet, so that might be an issue here too. It isn't really "breaking" the set if he doesn't actually have the set bonus currently. (Quick test reveals that is the case actually. Swapped him into the first set that the optimizer recommended and now all of my upgrade targets are husk.) My expected behavior was that it would try and surface the best artifacts to get the set bonus as well.

Something to somewhat get around this is to equip Itto with a 5p Husk set

Regarding ER stuff: I believe that is typically left to GCsim and the KQM ER spreadsheet
