### ISSUE TITLE
Suggestion: TC Mode and force options

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#482]
While I understand why you wanted to remove the "force" artifact set option, its still a sore point for many users.

Considering the only thing thats currently locked behind the TC Mode is the optimization graph (ignoring roll probability since noone uses it) unless more "TC" centric features are added it feels like a pointless/wasted function to just toggle the graph.

While having TC Mode show the "TC Tab" (#311) would be the ultimate move -
I propose having it re-enable the "force 2pc/4pc" artifact sets feature along with adding a "force single artifact" feature as these are essentially only build constraints that the optimizer has to work around just like setting a minimum ER% or excluded artifacts.

Completely removing the force feature does seem to be in opposition of the "don't tell people how to play" theme of GO.
Regardless if people were using it poorly; the choice should be available to them. Especially in a TC sense.

For example; the removal of force sets has made using the comparison graph (https://peacerekam.github.io/) to see the relative difference between your account's 4pc or 2+2pc artifact sets more complicated.
And with the addition of "force single artifact" you would be able to not just make the builder work around a particular artifact - but also dictate the slot of an off-piece to find how weak/strong certain off pieces or 4pc sets on your account are.

Yes these features arent the core purpose of GO. But its a powerful system and would be a shame not to utilize it in such a way.
I guess you must make the choice to fully embrace the "TC" side of things, or stick to your guns with trying to guide people into a "optimal" build at the expense of users who knew what they were doing.

**Comment by frzyc** [comment]
no
