### ISSUE TITLE
Upgrading an equipped artifact via a pasted screenshot unequips the artifact

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#485]
Steps to recreate:

Have a +16 artifact equipped to a character.
Take a in-game screenshot of the +20 version of the artifact and paste it into the artifacts page.
Select "Upgrade Artifact".
The Artifact will then be unequipped from the character.

This only happens if you paste/upload the image - if you manually create an upgraded version of the artifact it won't be unequipped.

**Comment by nguyentvan7** [comment]
Some example screenshots to replicate with. Upload the +0, equip it to someone, then upload the +20
![image](https://user-images.githubusercontent.com/36019388/209417802-17ae3ab7-869a-41e7-8016-f66943229fe4.png)
![image](https://user-images.githubusercontent.com/36019388/209417804-41b02c5f-a3f0-45c1-af03-fafafcc9735c.png)
