### ISSUE TITLE
Put a checkbox in each char optimization "Build Constraints" to disable it without deleting

### ISSUE THREAD

**Issue by aingerusanchez** [frzyc/genshin-optimizer#497]
Frequently I add a new build constraint as ER or high CR and I have no results for that build.
I would like to disable that constraint until I farm more artifacts of that set and try it again without deleting that specific property point (it could take months).

![image](https://user-images.githubusercontent.com/5485183/179396220-3a8e61fb-300d-4e4d-970d-09637ac0c9aa.png)

**Comment by frzyc** [comment]
Would take significantly more work for devs than for users to just remove it and add it back later.
