### ISSUE TITLE
Character roll value has some floating point shenanigans

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#510]
<img width="266" alt="image" src="https://user-images.githubusercontent.com/36019388/181691276-2fa287c6-4cde-4fa2-9b48-4e0b5210dee7.png">
Should be rounded to the nearest 10

**Comment by frzyc** [comment]
can you print out the actual difference? i think we use a difference of like `0.00001`

**Comment by nguyentvan7** [comment]
3739.449714348325
<img width="249" alt="image" src="https://user-images.githubusercontent.com/36019388/181818943-492ffebf-7174-4b38-8ece-8e8ad215bf1e.png">

Here are the values that were added together
<img width="106" alt="image" src="https://user-images.githubusercontent.com/36019388/181819008-e0917576-e1fa-4029-95ca-3c48e131061d.png">
