### ISSUE TITLE
Artifact set effect cards are merged, rather than 2 separate cards

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#511]
<img width="282" alt="image" src="https://user-images.githubusercontent.com/36019388/181691911-ccdb6629-b7f6-4027-8080-58168ff8a0dd.png">
Before, the 2-set and 4-set blocks were 2 distinct cards. Now they seem to be merged into a single one

**Comment by frzyc** [comment]
Was fixed in `8.14.0`.
