### ISSUE TITLE
Slingshot passive should not work on Childe's stance change

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#522]
![image](https://user-images.githubusercontent.com/101696552/182582554-1a4626b0-cd06-481c-bdd1-ecc81d59ae08.png)
![image](https://user-images.githubusercontent.com/101696552/182584717-2a923f24-3753-47fe-a3a8-b1b81768f7e8.png)

**Comment by nguyentvan7** [comment]
<img width="701" alt="image" src="https://user-images.githubusercontent.com/36019388/213548507-b8d15283-d5e4-4972-b44c-69953d118236.png">
Actually this conditional should be 3-state instead of 2-state. Doing so would also fix this issue for childe

* inactive
* < 0.3s
* > 0.3s
