### ISSUE TITLE
Better distinction between multiple hits that have different multipliers

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#523]
Would be helpful for Multi-target configuration so you can tell which one you've selected.
Childe and Raiden for example:

![image](https://user-images.githubusercontent.com/101696552/182582960-10ecdf35-f0a4-4707-980a-3374ce55b94b.png)

![image](https://user-images.githubusercontent.com/101696552/182583026-302812dd-f32d-49c3-8a8b-b964fe69dada.png)

**Comment by nguyentvan7** [comment]
Frzyc mentioned this in discord, restating here for record keeping

Could have `info.hit.suffix` for these and `info.hit.numHits` for Yoimiya normals (or other multi-hit)  
Then display the `suffix` in the target selecter, and automatically populate the multiplier in the multi-target creator with `numHits`

**Comment by StainAE86** [comment]
This is more of an issue now that we can duplicate and move inidividual targets within multi-target since we don't know which multiplier version we're duplicating or moving.

![image](https://user-images.githubusercontent.com/101696552/183266196-9b794664-e84b-4729-8587-0adf59055590.png)
