### ISSUE TITLE
Add share/export/import to multi-targets

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#524]

**Comment by hazydream** [comment]
I'm not sure if I understand this right, but I hope, by "share", it includes the ability to duplicate some of the existing multi-target of current character to other existing databases/accounts of choice. I use GO for 3 accounts, and it's such a pain to manually add the same multi-target for other accounts.

**Comment by StainAE86** [comment]
> I'm not sure if I understand this right, but I hope, by "share", it includes the ability to duplicate some of the existing multi-target of current character to other existing databases/accounts of choice. I use GO for 3 accounts, and it's such a pain to manually add the same multi-target for other accounts.

It would essentially just generate a mini json file of the multi-target data that you can save or copy to the clipboard and then load/paste into a different database.
