### ISSUE TITLE
Bug: Vape appearing as a option on Cryo characters on multi-target selector

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#528]
![image](https://user-images.githubusercontent.com/101696552/182830463-2eb4afcc-d474-463c-95a2-6ba50b351bd0.png)

**Comment by nguyentvan7** [comment]
Would probably be best to refactor `CustomMultiTarget:ReactionDropdown` with `HitModeEditor:ReactionToggle` somehow. Or make `HitModeEditor:ReactionToggle:allowedReactions` an export

**Comment by frzyc** [comment]
@nguyentvan7 I agree. do you want to do it, or should I?
