### ISSUE TITLE
Characters in a team are not updating under certain conditions

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#539]
## Steps
1. Take Character A, and clear out their Team Buffs tab
2. Take Character B, and clear out their Team Buffs tab
3. Add Character A to Character B's team
4. Go back to Character A
5. Change constellation level or talent level on Character A (there are actually numerous other things that don't seem to work, such as character level, custom stats, etc)
6. Go back to Character B's Team Buffs tab
7. Notice that Character A still has the old constellation/talent level, and is now out of sync

**Comment by frzyc** [comment]
https://user-images.githubusercontent.com/1754901/183263602-9dc1d074-4bf4-4394-acad-1fa301de97ff.mp4

**Comment by nguyentvan7** [comment]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/36019388/186832021-7e3e79fa-26a1-4d29-81f7-acc669a3a7aa.png">
More context/possible direction for the bug
