### ISSUE TITLE
Hide "New" characters on "Swap character" popup

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#544]
![image](https://user-images.githubusercontent.com/101696552/183222101-f8607b0b-43c0-4390-a028-d1b2d1357206.png)

**Comment by nguyentvan7** [comment]
Hm this is honestly the main way I add characters. Not sure about others. I almost never go to the character index page

**Comment by StainAE86** [comment]
> Hm this is honestly the main way I add characters. Not sure about others. I almost never go to the character index page

Maybe just an option to "hide" them like Seelie has?

![image](https://user-images.githubusercontent.com/101696552/183230280-a39bef42-4445-4eae-ac83-18011064bc43.png)

**Comment by StainAE86** [comment]
Unrequired with latest change to character selector popup
