### ISSUE TITLE
Clicking "Genshin Optimizer" to return to the home page does not update the browser tab page title

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#546]
![image](https://user-images.githubusercontent.com/101696552/183225645-1a101013-3e9b-49f5-a3f5-83d76a44974d.png)

**Comment by nguyentvan7** [comment]
Weird. For some reason, the `useEffect` call is not running inside of `useTitle` is not running in this specific case. I don't know enough about React to know why

**Comment by nguyentvan7** [comment]
Seems like this is happening again (or was never fixed idk)

**Comment by StainAE86** [comment]
Just noticed that this only happens on tabbed pages like individual characters
The page title will update if you go from Settings -> Genshin Optimizer for example
But wont if you go from Eula's Team Buffs tab -> Genshion Optimizer
