### ISSUE TITLE
Rename and rearrange top row of buttons to make use clearer

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#556]
There has been a significant increase in people thinking that Enemy Config has been removed and that Multi-Target means against multiple enemies. While this is them fundementally missunderstanding - we haven't made it super clear in the UI.

I suggest renaming "Detailed Stats" to "Additional Stats & Enemy Config" to make it clear that the enemy info has also been moved here.
And renaming "Custom Multi-Target Config" to "Multi-Optimization Target Config" to make it clear that its for multiple optimization targets, not enemy targets.

Also on a personal gripe level it feels weird that "Formulas & Calcs" is the last button. I'd move it to the middle button.

![image](https://user-images.githubusercontent.com/101696552/183757017-4e857d39-a8e9-4ddc-a003-704e003a771f.png)

**Comment by nguyentvan7** [comment]
I agree with the string changes. I'm still not sure if it communicates to the user that is where you can go to add Bonus Stats but I don't have a suggestion to fix that.

Shouldn't the two config buttons stay grouped together? Feels odd to have it go config > formulas/info > config

**Comment by StainAE86** [comment]
Maybe "Bonus Stats & Enemy Level" instead? But "Additional" seems ok in my mind.

My thinking is that "Stats and Enemy" is the foundation you place down to configure the "base" state of the character.
Once you've done that the Forumlas will reflect this state.
Then you chose which target to Optimize.

That's why the flow should be Stats -> Formulas -> Target in my head.

**Comment by nguyentvan7** [comment]
To me it feels less of a "flow" and more a grouping of functionality types

**Comment by nguyentvan7** [comment]
Would also be worth considering adding an indicator to the detailed stats button to indicate that it has been modified
