### ISSUE TITLE
Filter roll value in optimization

### ISSUE THREAD

**Issue by sirius16** [frzyc/genshin-optimizer#559]
I understand why substats are not considered when calculating stats/damage for artifact optimization, but what about for choosing which artifact to use. For example, say I have Kokomi and I've built an optimal build and it calls for a maiden flower but it chooses a maiden flower with Defense, DEF%, ATK, EM substats even though I have another maiden flower, same level, with HP and ER substats but it has a lower RV _unless_… you choose to only filter RV by HP, HP%, and ER%

Does what I'm saying make sense? Sorry if it's not super clear. But I'd like for character RV filters to be taken into account during optimization as well

**Comment by StainAE86** [comment]
RV is completely seperate to the Optimization process.

But substats are 100% taken into consideration during the Optimization process - but it completely depends on your Optimization Target.

If your selected target is a DMG target the Optimizer will select artifacts that provide the most DMG. Regardless of the RV or "value" to the particular character. It will not "balance" the build by including other stats like HP, EM, ER etc that are considered "good" for that character unless you specifically optimize for an ability that REQUIRES those stats.

If you want to have a minimum ammount of a certain stat I suggest you use the "build constraints" feature to force the Optimizer to only return build results that include those constraints.

Remember "Roll Value" is just a metric of how high or low that substat has rolled during the leveling process. It does not represent how valuable it is in a % to a character.

**Comment by sirius16** [comment]
hmm I see your point then yeah.
In that case, I have an alternate feature question/suggestion. Should I ask here or open another issue?

**Comment by StainAE86** [comment]
Best to join the discord to have a discussion about it

**Comment by sirius16** [comment]
didn't expect that but alright will do

**Comment by StainAE86** [comment]
https://discord.com/channels/785153694478893126/785176576110231583/1007205268091846717

**Comment by nguyentvan7** [comment]
Closing as original issue will not be considered
