### ISSUE TITLE
Bug? C2 Kazuha conditionals are seperated

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#567]
![image](https://user-images.githubusercontent.com/101696552/186133833-d74dd936-6104-457f-902e-7ac6df97f029.png)

My assumption is that one of them is for the 200 EM to Kazuha himself, and the other is the 200 EM for team mates within the field.
So they have to be two different checkboxes. But it feels odd to have them seperate from eachother within the teambuff page.

![image](https://user-images.githubusercontent.com/101696552/186133856-bec13c62-e8cf-4fcb-a8a7-3edf8b44cf64.png)

**Comment by nguyentvan7** [comment]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/36019388/186288650-efa0aa98-1ecf-4067-b71d-81496223d2a5.png">
