### ISSUE TITLE
Add ability to merge databases

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#572]
This didn't have a strong use-case before, but now that the new web scanner supports partial scans (and adeptiscanner also supported partial scans, but wasn't commonly used), users may want to merge their current DB with a new partial scan, rather than deleting all artifacts that are not present.

**Comment by StainAE86** [comment]
Some considerations;

If you do a scan that includes the "equipped: character" status and merge it into a database that does not have that character - do you just send that artifact to inventory, or create a new lvl1 character?

And if you import a partial scan that has a different equipped status to the current database - do you update the equipped status as per the partial scan?
