### ISSUE TITLE
GO Export mainStatVal not always used

### ISSUE THREAD

**Issue by srliao** [frzyc/genshin-optimizer#58]
Hi

This is more of a feature request per say than a bug report (since I suspect this behavior is intended). I added the ability to parse GO exports to my [combat sim](https://github.com/srliao/gisim) and I been noticing that GO sometimes will export the `mainStatVal ` and sometimes not. I guess GO probably uses the lvl to recalculate that main stat as opposed to relying on this value?

Would it be possible to consistently export this value instead or alternatively never export this value at all? I find there are some cases where you have a lvl 20 feather for example but only 47 attack.

**Comment by frzyc** [comment]
Hi @srliao,
The `mainStatVal` was added to our database by mistake. Please calculate the appropriate `mainStatVal` using `mainStatKey` and `level`. We are going to add a hotfix soon that remove it from the API and database.

**Comment by frzyc** [comment]
Fixed in 5.7.13 https://github.com/frzyc/genshin-optimizer/commit/529c9c1ec9b0ea7f3e45c62d0b7c53263a0636e5
