### ISSUE TITLE
When lowering a character level via the input box it defaults to the lower ascension level

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#587]
To recreate:
Have a character at 81/90. Select the left text box and change to 80 either by typing or pressing the down arrow.
The character level will then change to 80/80 rather than 80/90.

**Comment by frzyc** [comment]
wouldnt the converse be true? if you go from 79->80, it would change to 80/80 rather than 80/90. for a somewhat stateless element like this retaining the direction the number changed for this is kind of annoying to code/debug

**Comment by frzyc** [comment]
It would take me significantly more code to get this to work than it would take for the user to adjust. I'll say no to this for now...
