### ISSUE TITLE
Remove "Theorycraft Mode" checkbox

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#588]
Now GO is embracing the TC side of things with the addition of the Theorycraft tab that is not hidden behind the "Theorycrafting Mode" checkbox under Settings page. The checkbox should be removed and all features just made default.

This will allow me to re-make both the Database management video (for the multi-profile support) and the "TC mode" video.

**Comment by frzyc** [comment]
Then rolll probability and tc graph is on by default

**Comment by StainAE86** [comment]
> Then rolll probability and tc graph is on by default

I don't mind RV being on by default.
And see the first comment in #586 for an idea to make the tc graph more streamlined with the Optimization tab
