### ISSUE TITLE
Gorou's Burst buff does not appear in teambuffs

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#606]
Gorou's Burst is exactly the same as his skill. With the addition of the Ascension 1 bonus.

Currently the teambuffs tab only shows "Skill" and "Ascension1" so if you didn't fully understand how Gorou works you could turn off his Skill and wonder why when using his Burst he is only providing a 25% DEF increase to team mates.

![image](https://user-images.githubusercontent.com/101696552/188813961-e3a652eb-abd6-4c1c-b05c-dbc452e7e29c.png)

**Comment by nguyentvan7** [comment]
The only way I could see resolving this is having 2 conditionals, one for burst and one for skill, but they would need to be connected and show the same thing. I think leaving it how it is should be fine and less confusing
