### ISSUE TITLE
Avoid downloading gh-pages branch

### ISSUE THREAD

**Issue by eeeqeee** [frzyc/genshin-optimizer#610]
Can the `gh-pages` branch be moved into another repo or at least mention in the readme how to avoid fetching it?
```
git config --add remote.origin.fetch "^refs/heads/gh-pages"
git branch -dr origin/gh-pages
```
https://stackoverflow.com/a/64439191

**Comment by frzyc** [comment]
moving the `gh-pages` branch would change the site URL, which is probably undesirable. I can include instructions in the README.
