### ISSUE TITLE
Translation glitch in artifact page

### ISSUE THREAD

**Issue by littlef0x** [frzyc/genshin-optimizer#611]
In the artifact page, there are some buttons such as 'Unequip Artifacts', 'Delete Artifacts'. The Simplified Chinese translations of two of them are incorrect and may cause misunderstanding. Screenshot as follow:
![图片](https://user-images.githubusercontent.com/32670075/189563508-2311eb3b-0961-4649-bd09-1aa246527639.png)

The upper one is Chinese version and the bottom one is corresponding English version. The 'Exclude Artifacts' is translated as '排除的圣遗物', which means 'excluded artifacts'. Also, the 'Include Artifacts' is translated as '包含的圣遗物', which means 'included artifacts'. The meaning of the English version is an **action**, while that of the Chinese version is a **filter**. This may cause misunderstanding.

The correct translations are: Exclude Artifacts = 排除圣遗物, Include Artifacts = 包含圣遗物, i.e. the ‘的' should be removed. Translations of other buttons are correct.

**Comment by frzyc** [comment]
@littlef0x do you want to help with translations? 
![image](https://user-images.githubusercontent.com/1754901/189764047-1dc9dc23-2f22-43de-b554-e839cd3a1d6c.png)
https://poeditor.com/join/project?hash=Uv6SlyiPWo

We recently restarted our translation process.

**Comment by littlef0x** [comment]
> @littlef0x do you want to help with translations? ![image](https://user-images.githubusercontent.com/1754901/189764047-1dc9dc23-2f22-43de-b554-e839cd3a1d6c.png) https://poeditor.com/join/project?hash=Uv6SlyiPWo
> 
> We recently restarted our translation process.

@frzyc Oh yes, glad to help if I could.

I already joined the project. It's my first time to used POEditor platform. Any requirements?

**Comment by frzyc** [comment]
@littlef0x Not really, all this is volunteer work, the website should handle most of the cases. Just look for the "untranslated" or "fuzzy" translations every once in a while.
The translations are not updated in real time, I will manually update the site every once in a while.

I'll close this issue since translations are handled in an external website.
