### ISSUE TITLE
Incorrect formula for Ganyu with Amos' Bow

### ISSUE THREAD

**Issue by littlef0x** [frzyc/genshin-optimizer#612]
There's a time lag of 0.3s between the hit and bloom of Ganyu's Frostflake Arrow, which means the bloom will have up to 3 more stacks than the first hit. But in the current version of GO, the Total DMG Bonus of Frostflake Arrow DMG and Frostflake Arrow Bloom DMG are the same, which is incorrect.

Here's my test to verify this. The calculated dmg is 14861+25263 with 0 stack and 16703+28395 with 3 stacks.

![图片](https://user-images.githubusercontent.com/32670075/189570192-c97f5ecc-ffca-4a1f-a0d3-af0bf418a5a4.png)

But the real dmg is 14861+28395, which means 0 stack for Frostflake Arrow hit and 3 stacks for Frostflake Arrow bloom.

![图片](https://user-images.githubusercontent.com/32670075/189570396-1bf4fb76-be65-4986-88fa-cab8fc4777ae.png)

I don't know whether Tighnari's CA is the same since I don't have him.

**Comment by nguyentvan7** [comment]
The formula is correct, but GO can only really optimize for a single instance in time. You can use multi opt if you truly want to damage match/calculate with amos passive in mind for both shots at the same time
