### ISSUE TITLE
White box around popups

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#613]
When you click in the Multi-Target NAME field the surrounding modal turns grey and the moment you try to enter text (or even backspace) a single key press will cause the white box to appear and take focus out of the text box.

Entering in the ORDER boxes or MULTIPLIER boxes don't cause this. It's only the NAME box.
Doesn't matter if it's the first multi-target created, or an old one edited.

![image](https://user-images.githubusercontent.com/101696552/189581283-d1868cae-2901-489a-8b35-9739b07850b3.png)
![image](https://user-images.githubusercontent.com/101696552/189581742-e80e9057-7331-41c2-9e3c-0f49cb5885a5.png)

**Comment by StainAE86** [comment]
Updated description and changed status to Fix ASAP since I now know how to re-create it.

**Comment by frzyc** [comment]
Fixed by `8.19.2` https://github.com/frzyc/genshin-optimizer/commit/9d5046fc79e06b5ec0640a6125e0f61d31e318cc
