### ISSUE TITLE
Remove Kuki/Venti/Razor combined dmg formulas

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#618]
Enabling aggravate, vape or melt for these formulas will result in a completely inaccurate calculation, as not each hit of these combined formulas should be able to react. Probably best to remove these with the addition of multi-opt. With sharing multi-opt targets coming back, we can share a multi-target for users to recreate these formulas easily.

Removing these nodes would probably require a DB migration so user multi-targets are not suddenly missing a target or something like that. Probably best to pair with #581, since that also requires a DB migration

**Comment by StainAE86** [comment]
For reference this is Venti's (Non-Hydro) Multi-Target for his combined burst damage:
`{"name":"Multi Enemy Burst","targets":[{"weight":20,"path":["burst","base"],"hitMode":"avgHit","bonusStats":{}},{"weight":15,"path":["burst","absorb"],"hitMode":"avgHit","bonusStats":{}},{"weight":14,"path":["reaction","cryoSwirl"],"hitMode":"avgHit","bonusStats":{}}]}`

Kuki is just 12x "Single Instance DMG"
But for the sake of Aggravate procs this is the Multi-Target for Kuki's burst:
`{"name":"Total Burst + Aggravate","targets":[{"weight":4,"path":["burst","singleDmg"],"hitMode":"avgHit","reaction":"aggravate","bonusStats":{}},{"weight":8,"path":["burst","singleDmg"],"hitMode":"avgHit","bonusStats":{}}]}`
