### ISSUE TITLE
Add word "Optional" to the Graph setting

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#622]
Now the TC Mode checkbox is gone probably worth adding the word "Optional" somewhere so people dont think they have to set something.

![image](https://user-images.githubusercontent.com/101696552/190841465-b491a7b4-570b-482f-9564-14fc53031e9a.png)
![image](https://user-images.githubusercontent.com/101696552/190841483-2e1ecd73-b7cb-42e1-bdca-01447b080271.png)

**Comment by littlef0x** [comment]
I think it's better to use checkbox to show an optional item, like 'Use Equipped Artifacts'. The drop-down list shows only when the checkbox is selected.
