### ISSUE TITLE
Save last position of character popup

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#624]
Now the swap character popup is much longer with the added artifact/weapon/team info is it possible to save the position you had scrolled down to when going back to it?

Often the workflow is; start at the top (where your high level or fav characters are) and work your way down to see where newly added or freed up artifacts can be allocated.

Always starting from the top slows this process down now.

![image](https://user-images.githubusercontent.com/101696552/190847458-f0b03744-c7b8-47b1-b06b-2702c44b960d.png)

**Comment by frzyc** [comment]
Invalid now that the selection screen has been condensed #636.
