### ISSUE TITLE
Add Prev/Next button on character page 

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#626]
To be able to quickly swap to the next character in order (based on your fav, filter and sorting settings)
This would require #625 changed to make the filtering and sorting of characters global

![image](https://user-images.githubusercontent.com/101696552/190878216-447fdc57-4d7b-4815-8d6d-9131bcbe0f12.png)

**Comment by frzyc** [comment]
Spend dev time to add 2 buttons that save you one click from the character selector? Just more UI clutter for minimal usability.
