### ISSUE TITLE
Add ability to hide/filter "NEW" or characters that do not have artifacts equipped

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#630]
Extra filter options to allow user to condense the character page that will persist into the character popup. Ref: #625

**Comment by frzyc** [comment]
Since the character selector has been condensed #636, no need to add extra filters

**Comment by StainAE86** [comment]
https://discord.com/channels/785153694478893126/785176576110231583/1027499578280378368

**Comment by frzyc** [comment]
Would not the solution be that if you sort by name, the NEWs are still in the forefront? My argument is that if you are using name as a sorting metric, then you want this to be ignoring NEW...
