### ISSUE TITLE
Allow artifacts to be edited directly from the optimization result

### ISSUE THREAD

**Issue by lokyst** [frzyc/genshin-optimizer#637]
Say the optimizer suggests an artifact and I choose to  immediately upgrade that artifact in game. I would like to reflect that upgrade without having to rescan all of my artifacts or go the process of finding the artifact in the GO  inventory screen.

![image](https://user-images.githubusercontent.com/6118775/191132203-698f7206-0e4c-4735-9ba2-1bf653ddb27f.png)

**Comment by StainAE86** [comment]
This has become a higher priority now that GO forbids people using multiple instances of the site

As previously these users would have a copy of their artifacts page open at the same time as the optimize page and if a low level artifact was suggested in the optimization results they would swap to the other browser tab and upgrade that artifact - then refresh the optimize page tab and re-optimize

If you could edit directly from the results there would be no need to leave the optimize page and find the artifact to upgrade
