### ISSUE TITLE
Unable to manually add a new artifact via editor

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#638]
When creating a NEW artifact manually after selecting the set all other sets disappear from the drop down and you cant close the drop down. Clickout out of the drop down results in no selection being made.

![image](https://user-images.githubusercontent.com/101696552/191169866-98374cc5-b360-48da-8cd2-deb6cce2e590.png)

**Comment by frzyc** [comment]
fixed in https://github.com/frzyc/genshin-optimizer/releases/tag/8.20.1
