### ISSUE TITLE
[Feature Request] Seperate the whole profile of Traveler of each element

### ISSUE THREAD

**Issue by littlef0x** [frzyc/genshin-optimizer#646]
I'd like to suggest seperating the whole profile of Traveler of different element, i.e., making Traveler of each element an independent character. Here are the reasons.

1. Travelers of different element use different weapons and artifacts. For example, Anemo Traveler uses 4pc Viridescent Venerer and Freedom-Sworn, while Dendro Traveler uses 4pc Deepwood Memories and Favonius Sword. In the current version, you can only save one set for all the travelers.

2. Different teams may need Travelers of different element. And the settings in team build are also different. For example, in Tighnari's team with Dendro Traveler, I want to select the effects of Deepwood Memories and Verdant Overgrowth, as shown below.
![图片](https://user-images.githubusercontent.com/32670075/192031197-fb9645e1-b78e-462b-baae-9d43e8e44315.png)
And in Ningguang's team with Geo Traveler, I want to selects the effect of Noblesse Oblige and Invincible Stonewall, as shown below.
![图片](https://user-images.githubusercontent.com/32670075/192031602-c52e5f53-9cae-4ac7-b442-173ae4ec5dcc.png)
But in the current version, if I want to optimize Ningguang's build, I have to optimize Traveler's first. That's because even if I select Geo Traveler instead of Dendro Traveler as Ningguang's teammate, Geo Traveler is still using Deepwood Memories, and I have to change it to Noblesse Oblige first. And then if I want to Optimize Tighnari's build, I have to repeat the process. That's quite inconvenient.

So please consider seperating the profiles of Traveler of each element. Also, I think there should be a special design that all the Travelers should be able to equip the same artifact at the same time (and this design should not apply to other characters to avoid confusion). Thanks.

**Comment by frzyc** [comment]
I wrote extra code to sync all the elements of traveler for a reason: GO inventory should reflect the **current** state of your Genshin inventory. I understand where you are coming from, each traveler should have a separate build with separate context. I am planning a loadout feature, that will address this, and decoupling the travelers was just one step towards that feature.
