### ISSUE TITLE
Unable to filter artifacts by Inventory or Equipped

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#653]
When you Inventory or Equipped in the dropdown it won't actually select.
It appears to - but the "X" doesn't appear and if you click out of the dropdown the selection reverts to Any"

![image](https://user-images.githubusercontent.com/101696552/192442936-8ca04905-6152-40fe-aa29-7c067faf496c.png)

**Comment by frzyc** [comment]
Fixed in 8.22.2
