### ISSUE TITLE
Add "Allow multiple tabs" option

### ISSUE THREAD

**Issue by lampham7** [frzyc/genshin-optimizer#657]
Can you please consider adding "Allow multiple tabs" option? The single tab limitation have annoyed and restricted me from utilizing this great website so much. In the past, if i want to see the new +20 artifact help my characters to have a better build or not, I just need to switch to the artifact tab then add the new artifact then switch to the optimize tab then refresh the tab then optimize to see if I have a better build or not. Now if i want to do that, i need to go to the artifacts page, add the new artifact, go to the characters page, choose the character, change to the optimize tab, then optimize. It wastes so much time.

And multiple tabs also allowed me to be able to build multiple characters and monitor my artifact inventory at the same time too (I have builded Raiden Xiangling Xingqiu and monitored my artifact inventory at the same time regularly), it was so useful.

**Comment by nguyentvan7** [comment]
> Now if i want to do that, i need to go to the artifacts page, add the new artifact, go to the characters page, choose the character, change to the optimize tab, then optimize. It wastes so much time.

I doubt multi-tab will be added, but I will let Frzyc comment. After adding the new artifact, you can press the back button on your browser to go back to the optimize tab

**Comment by frzyc** [comment]
This is the exact usage pattern that causes database corruption in the 1st place, and the primary reason why the tab restriction is here in the 1st place. Multiple tabs will also conflict with future features.
