### ISSUE TITLE
[Feature Request] Add number of effective sub-stats of artifacts

### ISSUE THREAD

**Issue by littlef0x** [frzyc/genshin-optimizer#679]
AFAIK when talking about the value of artifacts, the number of effective sub-stats is more easy to understand and more commonly used compared with RV%. (Sorry, effective sub-stat is what it's called in Chinese theorycrafting community. I don't know what should it be called in English community. Effective roll? Valid roll?)

The calculation method should be in consistent with RV filter. And if HP, ATK, or DEF (not %) is selected, it should be converted to corresponding % when calculate (because these small items are usually not very useful, and thus it doesn't make sense if they are calculated using the same method as others).

For example, for the following artifact:
![图片](https://user-images.githubusercontent.com/32670075/194378930-a3a68a9a-ba9b-4b53-ae19-e4a52f6e7bd9.png)

If ATK%, Crit Rate, and Crit DMG are selected in RV Fiter, the corresponding number of effective sub-stats should be `31.1%/6.6%+2.7%/3.3%=5.5`, where 6.6% and 3.3% is the average value of one corresponding sub-stat.

And if ATK, ATK%, Crit Rate, and Crit DMG are selected in RV Filter, and the base ATK of this character is 835, the corresponding number of effective sub-stats should be `31.1%/6.6%+2.7%/3.3%+(37/835)/5.0%=6.4`.

I suggest to show the total number of effective sub-stats of all the equipped artifacts in the RV part of character overview page under the 'Current Roll Value' , like this:
![图片](https://user-images.githubusercontent.com/32670075/194377180-c34eedbf-151e-4da2-97d1-4266fa3b925a.png)
and to show the number of effective sub-stats of a single one under 'Current Roll Value' of it, like this:
![图片](https://user-images.githubusercontent.com/32670075/194381532-2cbce098-d805-4077-8091-53a9a9a9bc28.png)

**Comment by frzyc** [comment]
I don't really like the notion of using average as the denominator. For 5*, a max roll would be like 1.176, and a min roll would be 0.8235. Neither of these are intuitive numbers. in RV, min/max is 70%/100%. 

The issue with roll normalization is that you are making the assumption that all substat rolls are of equal value, and following that assumption, you convert one to the other, in the context of a character's base stats. What you are asking for, is kind of like, 10lb oranges + 10kg apples = 20 fruit, which doesnt really make sense. Even if you put numbers together in a way to form a final number, if the units are wrong, your final number is just a number that makes no sense.

For example, lets say we use RV normalization of 1max roll of HP%(100%RV => 5.83%) and 1 max roll of HP(100%RV => 298.75), using a base HP of 10000. Say we have
HP -> HP% => 298.75/(10000*5.83%) + 100%RV = 151.24%NRV
HP% -> HP => (10000*5.83%)/298.75 + 100%RV = 295.14%NRV
Which NRV is the correct one?

**Comment by littlef0x** [comment]
@frzyc Thanks for your reply.

No, there's no **correct** one. It's more of a practice than a standard. Players regard HP/ATK/DEF as almost useless, so HP%/ATK%/DEF% should be used for normalization. The problem of RV% is that the following two artifacts have exactly the same RV%, but of course the second one is almost useless compared with the first one (unless your character and weapon are both lv1). That's why I proposed the calculation method above.
![图片](https://user-images.githubusercontent.com/32670075/194599187-bc18b3be-859b-48d0-a127-350ce89711bb.png)

This method is widely used in Chinese theorycrafting community. For example, 24 Rolls (e.g. 6 ATK%+18 Crit) is the most common assumption for an on-field dps in calculation (HP/ATK/DEF are not taken into consideration). It's true that the average is not intuitive. But when the number of samples is large enough, it should accurately reflect the overall trend.
