### ISSUE TITLE
Theorycraft "Compare vs. equipped" shows incorrect weapon diff

### ISSUE THREAD

**Issue by briankchan** [frzyc/genshin-optimizer#686]
For example:
- Keqing has R4 Lion's Roar equipped
- the theorycraft page is using R1 The Black Sword

When using "Compare vs. equipped," the diff should display a Normal/Charged Attack DMG Bonus of "0 + 20%," but it incorrectly shows "35% - 15%":

![image](https://user-images.githubusercontent.com/2161999/195472940-d7ea4424-035a-46bd-bda9-c5eb0f0e9c10.png)

Presumably, it's comparing against an imaginary R4 The Black Sword instead of the R4 Lion's Roar.
Changing Keqing's current weapon to R5 updates the diff to show "40% - 20%" instead.

The values on the rest of the page don't seem to be affected; it's just a display issue on the weapon section.

**Comment by StainAE86** [comment]
The TC Tab appears to be using the refinement level of the weapon you currently have equipped when 'comparing' a new weapon.

For example; If you have a R1 Dull Blade on and swap to a R5 PJC within the TC Tab - it will compare to a R1 PJC.
And if you have a a R5 Catch on and swap to a R1 Deathmatch - it will compare to a R5 Deathmatch
