### ISSUE TITLE
Candace does not receive Hydro infusion on her normal attacks within multi-target config

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#687]
Same goes for Pyro with C6 Bennett and Cryo with Chongyun.

![image](https://user-images.githubusercontent.com/101696552/195533991-3fe19e11-c555-47dc-bcf9-93c6faea395e.png)

https://discord.com/channels/785153694478893126/787340960173391903/1030022056550612992

**Comment by frzyc** [comment]
Misunderstood the ask. For external infusions, the user is intended to infuse each target, so the infusion from teammates in the context of multi-target is disabled.
