### ISSUE TITLE
Allow to create custom target expression

### ISSUE THREAD

**Issue by 1estis** [frzyc/genshin-optimizer#699]
I think it should be allowed to create custom optimization targets using values from builds.

For exemple:
I have such a multi-target for Nilou:
{"name":"Hibrid","targets":[
{"weight":2,"path":["reaction","bloom"],"hitMode":"avgHit","bonusStats":{}},
{"weight":0.75,"path":["burst","skillDmg"],"hitMode":"avgHit","bonusStats":{"hydro_dmg_":40}},
{"weight":6,"path":["skill","skillDmg"],"hitMode":"avgHit","bonusStats":{"hydro_dmg_":40}}
]}

That gives me the following target expression:
2 * Bloom DMG + 0.75 * Burst DMG + 6 * Skill DMG
![image](https://user-images.githubusercontent.com/98589843/196200602-41216ea5-d7bf-4e13-9c64-7eed9b85ec4e.png)

  
But I want to use this target expression:
2 * Bloom DMG + 0.75 * Energy Recharge% * Burst DMG + 6 * Skill DMG
![image](https://user-images.githubusercontent.com/98589843/196206292-8b27d960-79df-4c90-8931-27b1de2be0fa.png)

Or even such an expression:
2 * Bloom DMG + 0.75 * (Energy Recharge% - 0.5) * Burst DMG + 6 * Skill DMG

It's not just about Nilou. I remember this every time when the question concerns Energy Recharge. Graph helps sometimes, but it's not a solution. It does a poor job of solving this problem for me. The above example doesn't help at all. I need the ability to add Energy Recharge directly to the target expression.

**Comment by 1estis** [comment]
Since I don't like to collect characters for specific rotations and situations, I often collect a character immediately for all teams and situations that I can imagine. In this case, there is no such thing as little or enough ER for me in principle.

In any case, all these points can be solved using the correct expression.
All you need is a handy editor.

**Comment by frzyc** [comment]
The reason we explicitly disallow the ability to mix units in a multi-target is that it doesn't make mathematical sense. In the case of ER, set a min ER constraint when you build.

**Comment by 1estis** [comment]
@frzyc
I'd like to decide by myself what makes mathematical sense in optimization expression when I build.
And min constraints is too weak and inconvenient tool for solving tasks that you assigned to it.

**Comment by frzyc** [comment]
then feel free to host your own version of Optimizer with such limitations removed. I can refer you to the lines you have to edit.
