### ISSUE TITLE
Some of Yanfei's stat names are missing

### ISSUE THREAD

**Issue by gendoh** [frzyc/genshin-optimizer#701]
https://frzyc.github.io/genshin-optimizer/#/characters/Yanfei

![image](https://user-images.githubusercontent.com/2393477/196364796-0d1b1c67-8080-4ec3-84e0-068c54aa98d1.png)

**Comment by StainAE86** [comment]
I believe this was from a change to the translation and will be fixed up with the other similar issues in the next patch
