### ISSUE TITLE
Move "Add New" button to increase the amount of space for artifacts/weapons/characters

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#703]
https://discord.com/channels/785153694478893126/785176576110231583/1031857489299382313

![image](https://user-images.githubusercontent.com/101696552/196410360-293a25d2-3f1a-4b36-8b13-153234b4ef3c.png)

**Comment by frzyc** [comment]
We could make it so that the "Add" buttons are part of the navigation, so user can add artifact/weapon/character anywhere on the site 
<img width="979" alt="image" src="https://user-images.githubusercontent.com/1754901/196490888-07813e7a-d0e4-4392-9717-2bf8ed7f61e8.png">
