### ISSUE TITLE
Allow clicking GO Overview buttons to be taken directly to the corresponding filtered selection

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#715]
EG: Clicking "Electro" Characters:
![image](https://user-images.githubusercontent.com/101696552/197738277-2e66312c-dfaf-4ffb-abeb-a15c6bcb0f10.png)

Would result in this:
![image](https://user-images.githubusercontent.com/101696552/197738358-3939240f-7b68-4822-ad8c-edcf4fb1d1a4.png)

**Comment by frzyc** [comment]
Probably not worth the time, funneling data between pages is a complicated mechanic, especially if it ends up changing the underlying database entry for character page.
