### ISSUE TITLE
RV Filter behavior is inconsistent with other filters

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#718]
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/36019388/197894147-df8c8d88-a17d-4f29-9e31-8483c6f33642.png">
If I were to click the "3 star" filter for artifacts here, then 3-star would be the only one selected. Then I could click "4-star" if I wanted both 3 and 4 stars to appear.

However, if I click Elemental Mastery for the RV filter, then everything bug Elemental Mastery will be selected

I also wonder if this should turn into an autocomplete, similar to substat filter?

**Comment by frzyc** [comment]
probably will cause more problems for end-user than any provide any soothing to your OCD. close yer eyes, take a deep breath, and look at our other glaring issues.

Alternative is to make this element fundamentally not a button group, 

or include `[]` `[x]` toggles before the buttons(remove the text)

**Comment by nguyentvan7** [comment]
Not really OCD, it's just inconsistent behavior that makes it confusing to use (aka is an end user problem)

**Comment by frzyc** [comment]
Then like I said, you either make it not a buttongroup, or denote toggles,
or redesign this element altogether. I am not sure autocomplete is a good idea in this regard, since I would want a UI element that shows both: all the options, and which elements are selected.
