### ISSUE TITLE
[Improvement idea] Scrap character data from Hololabs' "Battle Chronicles"

### ISSUE THREAD

**Issue by GabenRulez** [frzyc/genshin-optimizer#72]
Basically, Mihoyo lets you access parts of your Genshin Impact data from their social media platform.

It's called "Battle Chronicles".

![image](https://user-images.githubusercontent.com/45923220/134256871-b357c79c-6c6f-4c36-b2e3-d1943c5d590b.png)

We can see:
- all the characters that we own, as well as their
  - level
  - constellation
  - (roughly) equipped artifacts (without their stats)
  - weapon, its refinement and level

It could be parsed once (per user request), or you could also make this "Battle Chronicles" public, like shown here:
![image](https://user-images.githubusercontent.com/45923220/134257696-da99fd2c-f659-45b9-a24b-23d5ed6b97eb.png)
If it's public, the user could input a link to their "Battle Chronicles" directly in the UI.

Let me know what you think about that.
Personally it took me quite a lot of time to input all my characters, so a little "speedup" would be a welcome change.

**Comment by frzyc** [comment]
There are already scanners that can scan in your weapons + characters from in-game. It would be kind of pointless to approach crawling data from this interface, where the data is incomplete, when another avenue is already available, that can scan in all the information.
https://frzyc.github.io/genshin-optimizer/#/scanner

**Comment by Efreeto** [comment]
I think the original idea still had merits. Even if the tools are 100% safe, or screen capturing process was very easy, just copy pasting a url is as fast and safe as it can get for users. But yeah, the data there is currently incomplete. Only if Battle Chronicles had Artifact stats...
