### ISSUE TITLE
Make Opt Target and Graph Target more obvious

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#733]
Now that we can graph against any Opt Target it's can be confusing because the eye is drawn to the same UI element as we're been used to using for "Optization Target", but it's now much closer to the "Generate Builds" button.

Yes this is a reading issue - but not all users are native english speakers and many suffer from 'skimming' over text anyway.
![image](https://user-images.githubusercontent.com/101696552/198514200-4bf0bdb8-4775-4181-b97d-208361399094.png)

I suggest grouping the Opt Target and Graph Target together to make it significantly more obvious:
![image](https://user-images.githubusercontent.com/101696552/198514316-c03303d0-17b7-43bf-8d51-2a0465c3ae5d.png)

**Comment by StainAE86** [comment]
Another idea:
![image](https://user-images.githubusercontent.com/101696552/198516980-7b64570a-6a5e-4b0a-925a-aa8df5a88e38.png)

Swap the Opt Target popup button and Generate Builds button so the two popups are together and the generate button is now on the right side. Feels more correct for UI flow having the final button buttom right.

And trolls people's muscle memory.

**Comment by StainAE86** [comment]
Another idea is to grey out the Graph Target button until an Opt Target has been selected

![image](https://user-images.githubusercontent.com/101696552/198851935-88e86b26-c54d-487e-8c00-494737ad45f3.png)

**Comment by nguyentvan7** [comment]
![Screenshot_20221029-142316_Discord](https://user-images.githubusercontent.com/36019388/198852908-93721dc5-74f8-4333-8dff-62b2bf279766.jpg)
Current plan of action
