### ISSUE TITLE
[Feature Request] substat nudging

### ISSUE THREAD

**Issue by brettowe** [frzyc/genshin-optimizer#74]
I think this would be an addition to the "Minimum Final Stat Filter"
but it would be nice if I could choose a substat no minimum amount entered 
and the optimizer just tries to make sure its included.
one example of this I found is I like to optimize for atk on jean but I want to have a bit of energy recharge added in there to make the burst happen a bit more often.

**Comment by brettowe** [comment]
while messing with optimizationing for itto I had a thought for this, the nudging could just be a pre-filter on the artifacts selected for builds. 
so filter out all artifacts that don't have the the stats (sub or main) selected for nudging or selected as main stat for the character

**Comment by frzyc** [comment]
TC graph should fulfill this feature.
