### ISSUE TITLE
add Widsith buffs as multi optimization target

### ISSUE THREAD

**Issue by kebabbozzo** [frzyc/genshin-optimizer#757]
just thinking of optimizing artifacts based on average buff effect. If not in the multi optimization target it would be great to have it in the overview tab

**Comment by nguyentvan7** [comment]
You can manually add the "average" of the Widsith buffs to your characters bonus stats, or to specific multi-target nodes if you want. I won't speak on the actual benefit of optimizing with the average of Widsith buffs

**Comment by StainAE86** [comment]
For example:
![image](https://user-images.githubusercontent.com/101696552/200055238-8567c599-2ffe-498d-8a54-f3f69b49ae50.png)

But it's not ideal to account for Widsith as you have no control over which buff happens at a certain point in your rotation. Plus Widsith buff is inactive more than it's active.

**Comment by kebabbozzo** [comment]
oh ok, never thought about it that way. i know considering the average buff may not be of much help, i only needed to find a good build that had no holes for all three buffs since i still need to farm decent artifacts.

thank you very much for your answer
