### ISSUE TITLE
DB Export will export artifacts with a key of ""

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#764]
Not harmful or anything, but doesn't fit in the GOOD spec
<img width="733" alt="image" src="https://user-images.githubusercontent.com/36019388/200470867-8329de4c-18bc-4589-bed9-d238f13ce3a5.png">

**Comment by frzyc** [comment]
This is a placeholder to ensure there are always 4 substats on an artifact.(and its reinforced within `ArtifactData.parseSubstats`.

Its somewhat benign to keep, but removing can perhaps disrupt a lot of the substat rendering logic on the site. I'd say its not worth "fixing".
