### ISSUE TITLE
GOOD importer detecting Traveler as character

### ISSUE THREAD

**Issue by NoelleTGS** [frzyc/genshin-optimizer#767]
I don't really know is this is a problem with Inventory Kamera or the Optimizer but I'm gonna assume it's the Optimizer. My actual name is Noelle so that's what I have my player name set to, and it seems to be conflicting with the Noelle in the game. It brings up the character in the Optimizer but with the Traveler's sword, obviously being an error (claymore character holding a sword). I can report this to the Kamera repo instead if it's a problem there and not here, just let me know.

**Comment by StainAE86** [comment]
Scanner issue

**Comment by NoelleTGS** [comment]
Alright, thanks
