### ISSUE TITLE
Removing a constellation with a toggleable effect doesn't turn off the effect

### ISSUE THREAD

**Issue by CaspianRoach** [frzyc/genshin-optimizer#773]
Been playing with Eula in the optimizer, wanted to see how much getting C1 would help her burst damage (mine is C0). 

- Changed Eula Constellation from 0 to 1  
- Went to Talents tab, turned on her C1
- Burst damage went up correctly
- Went back to constellations and removed her C1
- Burst damage stayed the same

So using this method we can have 'hidden' constellation buffs on characters that appear C0, as going from C1 to C0 doesn't turn off the toggleable effect from her C1.

**Comment by StainAE86** [comment]
Looks like this is back @nguyentvan7

https://github.com/frzyc/genshin-optimizer/issues/726
