### ISSUE TITLE
Add ability to view teammate stats

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#777]
Maybe a modal or tooltip?

**Comment by frzyc** [comment]
why not just reenable the stats that was removed here
![image](https://user-images.githubusercontent.com/1754901/203134956-97150cf5-21d2-44ce-bb81-9615bbe8bf13.png)

**Comment by nguyentvan7** [comment]
We removed those because most people didn't want to see the stats, and they were taking up too much space. So my thought was to have a little tooltip or modal to show the stats instead of always showing them

**Comment by littlef0x** [comment]
Maybe a switch can be added to the setting page to meet the needs of different users? Now the setting page is mainly a database manager. I think we can make use of it to provide more customizable experience.

**Comment by frzyc** [comment]
Probably just add an accordion with a header, no need to have a additional external toggle.
