### ISSUE TITLE
La pantalla se pone en blanco al intentar añadir un artefacto

### ISSUE THREAD

**Issue by Azrael3112** [frzyc/genshin-optimizer#792]

**Comment by nguyentvan7** [comment]
Google translate tells me the artifact screen is going blank when you add an artifact. Could you follow the steps below please?

1. Upload your DB from the Settings tab, and describe your steps to reproduce it
2. Upload other relevant things, such as screenshots, scanner files or other items used to replicate the bug
3. Is it a white screen crash? If so, open the developer console after the crash occurs by pressing `F12`, going to the "Console" tab and taking a screenshot of the red errors in there

**Comment by nguyentvan7** [comment]
I'll close this for now. feel free to reopen with more details, thanks!
