### ISSUE TITLE
genshin-optimizer-pipeline is not found

### ISSUE THREAD

**Issue by mhcgrq** [frzyc/genshin-optimizer#793]
I was trying to clone this repo and starting it in development mode. I saw the script `clone_pipiline.js` and there is a repo called `genshin-optimizer-pipeline` must to be cloned. But I can't find this repo. Does it intend to be private or something goes wrong?

**Comment by frzyc** [comment]
Due to recent controversy with leaks/datamine, the repo has been changed to private.

**Comment by nguyentvan7** [comment]
Closing, as there isn't anything else to do here sadly
