### ISSUE TITLE
Artifact level slider tooltip is obstructed

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#803]
<img width="149" alt="image" src="https://user-images.githubusercontent.com/36019388/205732087-9fc55445-8199-496a-aae2-dbe2fc1743e4.png">
There is a tooltip here circled in red, covered by the header it looks like

**Comment by frzyc** [comment]
<img width="188" alt="image" src="https://user-images.githubusercontent.com/1754901/213394635-22262eb5-73e8-45a5-a332-157925eff49f.png">
`overflow: visible;` on the parent div. Will need to update in all sliderlocations.
