### ISSUE TITLE
"Divided RV" display for better eyeballing of artifact potential

### ISSUE THREAD

**Issue by Algoinde** [frzyc/genshin-optimizer#827]
I wanted to implement RV for my website, but the concept as-is in Genshin Optimizer is a bit confusing. I'd like to settle on something common first.

The gist is, the percentage display of RV is very steep for someone who's never heard of it. Percentages above 100% immediately throw you off, and it doesn't answer the question "560% of *what?*". So my proposal was to further divide that percentage by the number of rolls, yielding a much more understandable 0.7 ~ 1 fraction (could be further multiplied by 100% for percentage display).

With the current percentage, you have to do an extra mental hop of "ok, how many rolls? 6, that's 600%, I have 550%, and that's...", while the thing could display 0.91 or 91%. This gives a ready metric of "% of max power/luck/potential".

Proposed notation: 
![image](https://user-images.githubusercontent.com/10269970/207136144-e908ef1f-3c8e-437b-859f-b26bc0f9cc86.png)
(roll count, potential)

Don't think renaming it to something like DRV or RQ makes any sense, the RV acronym can be kept, as it's still what it is.

**Comment by nguyentvan7** [comment]
![image](https://user-images.githubusercontent.com/36019388/208345136-a9c1f581-5fbc-40f3-b79f-6d29952a8c3d.png)

start of convo: https://discord.com/channels/785153694478893126/785176576110231583/1051943639611346944

will not be added for now it seems. I'm still down to add this as a tooltip, just not as the main display of RV
