### ISSUE TITLE
Add 4th "hit mode" option within multi-target to "follow global"

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#829]
Use case: There are times you want to optimize for crit hit on a multi-target but currently you have to make a copy of the target and swap every hit within it to crit then select this new target.

Allowing the user to select a 4th hitmode option (and possibly make it default?) that will just follow the global / main setting would be nice:

![image](https://user-images.githubusercontent.com/101696552/208178779-ecb9d7a9-cef2-4957-a989-fab11d51c985.png)

**Comment by frzyc** [comment]
Could implement for hitmode toggle, but not reaction/infusion/conditional toggle

**Comment by nguyentvan7** [comment]
Completed in #1433
