### ISSUE TITLE
Allow user to set different proc chances for Echoes to account for ping differences

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#844]
Mainly useful for the TC tab when checking how well Echoes would perform in comparison.
But currently the only options are Always (questionable use) and Average.
But according to community data gathering it can be as low as 30% chance on high ping.

![image](https://user-images.githubusercontent.com/101696552/209413608-5b7844f9-1695-4bcb-9957-0baf3a787112.png)

Maybe the best way out is to just add a 3rd option for "High Ping (36%)"

**Comment by frzyc** [comment]
I dont like the idea of  using a community-generated number. However, one option here is to allow user to input a number in a conditonal (will need to update conditional format to allow piping in number (and validating that number). probably reevaluation after wr2
