### ISSUE TITLE
Import/Export function for TC tab

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#848]
So you can share your build and import other's builds to compare by copy/pasting the .json data much like how the current multi-target system works.

Similar idea to #632 but might be easier to implement.

**Comment by nguyentvan7** [comment]
Could also have a stretch goal of shareable links for TC tab, since the data is of a fixed length, relatively small, and seems stable afaik

**Comment by frzyc** [comment]
if data format is deemed not to change (might get changed for wr2), we can implement. I think with timing it might be worth evaluation after wr2
