### ISSUE TITLE
Emblem and Engulfing Lightning buff formula is not calculating Jinni's Whisper team buff

### ISSUE THREAD

**Issue by Emah234** [frzyc/genshin-optimizer#850]
Both Emblem and Engulfing Lighning do not include Jinni's Whisper energy recharge team buff from Xiphos' Moonlight weapon in the formula even though it is included in the total Energy Recharge of the character.

**Comment by nguyentvan7** [comment]
<img width="717" alt="image" src="https://user-images.githubusercontent.com/36019388/210022362-17a539f3-854b-4c0d-bcc4-41c8200add13.png">
working as intended https://library.keqingmains.com/evidence/equipment/weapons#xiphos-moonlight

https://library.keqingmains.com/combat-mechanics/damage/damage-formula#additional-notes
