### ISSUE TITLE
Add filtered RV display to build display item

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#852]
![image](https://user-images.githubusercontent.com/36019388/210108957-21466e92-024a-4c1a-ad5b-9741a32b6fe0.png)
See bottom left of image

We should also hide the RV if the user has not set a filter yet, as the total RV value can be misleading to most users. Presumably if they set a filter, they at least understand RV a bit more and how it doesn't directly correlate to build quality

**Comment by StainAE86** [comment]
If filtered RV is to be put on the build page it would be fun to graph against it too

**Comment by nguyentvan7** [comment]
I'd create another issue for that, since that's a different can of worms, both as a concept, and code-wise

**Comment by frzyc** [comment]
I recommend combining this with #870, and use a tooltip with those buttons. 
I want to discourage the UX workflow where a user will have to go to the "overview" tab to change this setting, then come back.

**Comment by nguyentvan7** [comment]
Per-char RV filter will be removed
