### ISSUE TITLE
Deepwood's Set Conditional Not being Respected in Optimization

### ISSUE THREAD

**Issue by andradesavio9073** [frzyc/genshin-optimizer#861]
Deepwoods Set Bonus not being activated even tho its been enabled within set conditionals. First build screenshot is with normal optimization steps with teammate running deepwood but buff turned off. Second Build screenshot is with deepwood enabled on teammate. 

![image](https://user-images.githubusercontent.com/23692454/210282152-27f19ea0-3255-4359-a3a6-4fbb57596da4.png)
![image](https://user-images.githubusercontent.com/23692454/210282112-542dff67-90d5-41ba-98ed-aa40c604a09d.png)
![image](https://user-images.githubusercontent.com/23692454/210282162-804a5338-d697-4577-b0b6-e0c109ce572e.png)
![image](https://user-images.githubusercontent.com/23692454/210282173-e0824814-eb61-430a-9cf3-084be0a85829.png)

**Comment by Sinesthesia** [comment]
Double check the total dendro shred and formulas between the two. It's a known issue that it currently stacks between a teammate having Deepwood on _and_ it being on in the set configuration. You would just need to have one of them off when optimizing since they don't stack in-game.

**Comment by StainAE86** [comment]
The issue is currently the bonus stacks in GO when it shouldn't. So it is actually active in the first screenshot. And when you add Fischl it's just adding another 30% shred on-top where it shouldn't
