### ISSUE TITLE
Party Configuration

### ISSUE THREAD

**Issue by EffortlessFury** [frzyc/genshin-optimizer#87]
Has there been any discussion/interest in scraping the four party configurations and what they have equipped? Or even scanning all characters equips and then just scraping the party arrangements. It'd be nice to be able to share your builds outside of the game more easily.

I might be able to take a swing at implementing the scraping, but I also wanted to know if there was interest in adding that data to the GOOD format as well.

**Comment by StainAE86** [comment]
Just wanted to ask what exactly you mean by this?

Do you want to pull your 8-character showcase from the game into GO?
Or do you want to use GO to create a team and then export that configutation to show it off?

**Comment by EffortlessFury** [comment]
So, firstly, when I wrote this, I don't think I realized that there were fields in the artifacts and weapons that pointed to who had them equipped. Thinking about it, that's the right way to structure it given there is only ever one of any given character.


Note that I'm just referring to the data format, not necessarily how GO would utilize that data. Also, I talked about scraping but that's not GO's job, I just was bringing up that a screen scraper could automate the transcription of the party info.

All I meant was that it would be nice if the GOOD format allowed us to represent our existing party configurations. For example, Enka.network lets you generate character cards (though that gets its data in a completely different manner, I'm only referencing the output product), but those cards could also be generated from a GOOD object, and information on your in-game party presets would allow you to generate a card (or something in the same vein) with your entire party represented.

Even though this isn't possible in game, it might also be nice to be able to have different parties in the same overall GOOD object that utilized shared weapons/artifacts across different characters, but that may be departing from what data GOOD is designed to represent.

Sorry if this is still unclear, please let me know.

**Comment by frzyc** [comment]
but why?
![image](https://user-images.githubusercontent.com/1754901/187567908-a37b9242-9a1e-4290-82c7-4d5f3ea17512.png)
Characters already store their teammates in GOOD, just look for the `team` field, but im not sure what reason to have this data explicitly, unless its from the scanner side, but we probably wouldnt do anything with this data...
