### ISSUE TITLE
Change character Overview tab RV filter from popup to display buttons directly on the page

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#870]
This way you can easily see and change your settings without having to bring up the popup.
Saves a click. And lets you see the change to the artifact current RV as you change the filter without a popup covering them.

![image](https://user-images.githubusercontent.com/101696552/211307336-1581f7eb-13d3-4ffa-bb99-f6819969c023.png)

Reuses current Optimize tab main stat filter style buttons and does not take up much more space.
Makes the RV Filter more obvious too as currently the singular button can get lost in the left hand column.

![image](https://user-images.githubusercontent.com/101696552/211307702-3d8892fd-266d-4fa2-9580-b1b1ad285c04.png)

**Comment by frzyc** [comment]
depends on #852

**Comment by nguyentvan7** [comment]
Per-char RV filter will be removed
