### ISSUE TITLE
Defect Social Media Links on website?

### ISSUE THREAD

**Issue by Hylianer04** [frzyc/genshin-optimizer#881]
All the "social media" links on the site dont work for me at least on mobile. Cant test it on pc right now.
They all just redirect me to the main page.
No matter if its discord, patreon or the youtube guide link all and every other one of those just link to the main site, so youtube com, Discord com patreon com and so on.

I dont think that should be like that?

**Comment by StainAE86** [comment]
Works on Mobile and PC for me.

Try forcing a refresh to the website as there was an update yesterday and today that changed a few things with how the site works behind the scenes.

**Comment by Hylianer04** [comment]
> Works on Mobile and PC for me.
> 
> Try forcing a refresh to the website as there was an update yesterday and today that changed a few things with how the site works behind the scenes.

I did force reload, tried it on two browser and i never was on the site before, but i still have those problems.
The only links that work for me and not just link to the main page of that respective site(yt, Discord, KeqingMains and so on) are Twitter, the link to the automatic scanners and the link to the documentation.
Not even the link to the patchnotes works that sends me to a 404 on github

**Comment by nguyentvan7** [comment]
Fixed it, no patch required
