### ISSUE TITLE
[Request] Toggle to display % difference instead of raw numbers when comparing old vs new build

### ISSUE THREAD

**Issue by kazerniel** [frzyc/genshin-optimizer#888]
Instead of this
![image](https://user-images.githubusercontent.com/5689996/212501812-dff1bfd1-0606-41ad-a650-e5d6a9b94b6e.png)
this would be easier to grasp the magnitude of at a glance:
![image](https://user-images.githubusercontent.com/5689996/212501834-8f4b3a5f-c31f-4c96-bf0f-4179ff056ace.png)

Especially when weighing tradeoffs, it would make it easier to compare the effect of different builds across different stats.

**Comment by StainAE86** [comment]
![image](https://user-images.githubusercontent.com/101696552/212504021-c72f56e3-590a-4b28-b21d-8394c545e2bd.png)

The big problem with showing change as a percentage is that a smaller percentage of a big number is going to be a greater value than a bigger percentage of a small number.

In the example above you specifically _need_ to know the actual numerical value to make the decision if +800 healing is worth the loss of 7500 dmg. Showing a % can cause some very poor conclusions to be drawn.

You also have to consider how to show numbers that are already in percentanges.
For example a current build that has 150% CritD, and new build has 180% CritD.
Do you show that as 150% +30% (as we currently do, and as the game does)
Or 150% +20%? How confusing is that?
