### ISSUE TITLE
Artifact Equipped/Inventory logic

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#899]
Currently the UI logic seems a little strange for the "equipped" button as it seems to be acting more like a toggle to enable/disable the "location" multi-select drop down.

It's a little counter intuitive since you have to turn "off" showing equipped to then be able to define which characters to show equipped for. There might be a better way to communicate that in the UI?

The terminology "Inventory" can also be confusing as artifacts in your in-game inventory do not discriminate between equipped status. It's just all the artifacts in your inventory.

States you want is:
All Artifacts (Equipped and Unequipped)
Exclusively Equipped
Exclusively Unequipped
Exclusively Character Specific (Multi-select)
Character Specific and Unequipped

How about the following:
![image](https://user-images.githubusercontent.com/101696552/213841896-bd02aa8b-da01-4db2-a509-4807da45cfa8.png)

I think this communicates the intention clearer and the UI flows a little more when "toggling" the All Equipped button to enable the Location field below

**Comment by frzyc** [comment]
I liked the look of the inputs being all stacked up, but I think the text can be updated.
