### ISSUE TITLE
Build Generator

### ISSUE THREAD

**Issue by Altered005** [frzyc/genshin-optimizer#90]
When using the build generator, it won't show the generated builds. Only says the number of builds it generated and the time it took.
I'm not sure if I just missed something, but after looking around the site for a while, and reading the info on the page, I couldn't find anything to point towards me just simply missing something. 
I hope this can be fixed.

**Comment by frzyc** [comment]
The 8.0 release of GO changes much of the builder system. Not sure if this is reproduceable. Will need more details like Browser, OS, GO version, and possible error in console.
