### ISSUE TITLE
Suggestion: Artifact inclusion per character

### ISSUE THREAD

**Issue by littlef0x** [frzyc/genshin-optimizer#933]
A case:
I have only one set of 4-PC Pale Flame which was used by Eula. I don't use her very frequently and thus I put her in a relatively low position in Character Priority list. However, the circlet is very good, so it will appear in almost all builds for other characters. But I don't want to give it to others, or otherwise Eula will lose her 4PC. The current solution is to exclude it globally, which is not perfect because if I want to optimize Eula's build, I have to include it first and then optimize and then exclude it again.

I think there are two possible solution. One is to add a feature that can lock an artifact to a certain character. The other is to allow artifact inclusion per character. I think the latter is better, and can be done together with https://github.com/frzyc/genshin-optimizer/issues/901.

My proposal:
Replace the global include/exclude button of artifact with a list just like the Character Priority list in optimization. Here's a scheme (green frame mean button).
![图片](https://user-images.githubusercontent.com/32670075/216275978-4ff6ca2b-f041-4ed9-829d-40ed8258c70a.png)
So for the previous case, I can find the circlet, click 'exclude for all' first, and then click 'include' for Eula. Also, for the case in https://github.com/frzyc/genshin-optimizer/issues/901, I can click 'include for all' first, and then click 'exclude' for the certain character.

**Comment by StainAE86** [comment]
There is a major overhaul to how characters, their "loadout" and how that interacts with equipped, unequipped and excluded artifacts work coming soon(tm) which will include removing the "global" exclusion in favor of per character exclusions

**Comment by frzyc** [comment]
The main intention with removing the "global" exclusion is to remove "exclusion", which is only applicable to builder, from the artifact page, which should be only about artifacts. so adding a more complicated UI there is not something I want. Nor do i want to have to store include/exclude info per artifact, since thats a lot of data, and any flawed logic is hard to diagnose. I think the proposal within #901 should be good enough even for the case you outline above, unless there is a specific case you have to solve with a "include" logic, I am closing this issue.

**Comment by littlef0x** [comment]
> why don't you just move eula up in the priority list?

Thanks for your reply. Same problem if I move her up, i.e., the optimization results of Eula will be filled with artifacts that I want for another character only (because I have Pale Flame for all the 5 positions, so the flexible position could be anyone). There may exist a global optimal order but it's hard to find. So I have to change the order of priority or enable/disable certain artifacts back and forth.
