### ISSUE TITLE
Swapping characters via the charprio popup list no longer closes the popup

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#939]
![image](https://user-images.githubusercontent.com/101696552/216714193-f39b5940-8d57-4b13-a952-fca35bb3a034.png)

Previously when you clicked the side profile icon of a different character it would swap to that characters opt tab and close the popup.

Now it no longer does this. Apparently how it is now was the intended behavior but I feel auto close on swap is a useful feature.
There is no need to keep the charprio popup on screen after swapping to another character.

Initially I was going to raise this issue because "sometimes" it wouldnt close, like 10-20% of the time. However now it does not close at all.

**Comment by StainAE86** [comment]
prio list no longer exists

**Comment by nguyentvan7** [comment]
So long my love (prio list)

![image](https://user-images.githubusercontent.com/36019388/221769444-d82c257a-d9ee-4cc1-8d91-2850979f13fb.png)
https://www.youtube.com/watch?v=wGIKnn-COS4
