### ISSUE TITLE
Xiao Burst infusion in optimizer

### ISSUE THREAD

**Issue by XuaTheGrate** [frzyc/genshin-optimizer#94]
As the title suggests, there is no way (or I cannot find a way) to optimize Xiao for damage during his burst uptime. Closest I can get is either:

- Plunge damage, but this is considered physical (and there's no infusion option for Anemo)
- Elemental Skill damage, obviously this isn't his burst nor plunge so it's not as efficient.

**Comment by Peacerekam** [comment]
> Don't forget the INFO button can answer nearly all questions!
How to ensure Xiao's burst is calculated correctly:
Remember: anything relating to a talent will be handled in the talent section of that character's card.
> 
> 1. Activation
> Go to Xiao's burst in his card and activate
> :ballot_box_with_check: Bane of All Evil
> 
> 2. Rebuild
> Go back to the builder and set the optimization target to
> Whirlwind Thrust: High Plunge DMG
