### ISSUE TITLE
Very slow with lots of artifacts

### ISSUE THREAD

**Issue by maciello** [frzyc/genshin-optimizer#958]
Problem is that the program becomes almost unusable with a high number of artifacts.

I added some artifacts by modifying a database JSON and uploading it (doing it by hand would be crazy).

This image shows having 40794 artifacts. 
![image](https://user-images.githubusercontent.com/9354898/217336010-1f6d1dce-3459-4c9f-8b58-b391ca6ef638.png)

With so many artifacts most operations become very slow (10-300 seconds). 
Especially opening the "Artifacts"-tab and the "Characters/Optimize"-tab.

**Comment by nguyentvan7** [comment]
The site wasn't designed for this fake artifact stuff. Especially 40k artifacts which is almost 30x higher than the amount of actual artifacts you can have in game. Granted there are performance improvements to be made but this is not a valid use case.

If you want to experiment with fake artifacts, you'd be better off using the Theorycraft tab
