### ISSUE TITLE
"Swap artifact" pop-up only shows 12 first artifacts with no indication that this isn't the whole list.

### ISSUE THREAD

**Issue by CaspianRoach** [frzyc/genshin-optimizer#963]
The pop-up window for "Swap artifact" should either have a page control element or it should include a notice that it displays only first 12 artifacts that are valid for current filters, if this behaviour is intentional.

At the moment it is very easy to misunderstand and think that you don't have any more artifacts than the current cap of 12.

Pictured: bottom of the "Swap artifact" window, with no page control or limit reminder.

![image](https://user-images.githubusercontent.com/7204157/218175606-86285d3b-7521-44f1-8227-c831caa02c92.png)

**Comment by CaspianRoach** [comment]
I know that it shows 12/408 and the sort on top of the filters in the top left part of the window, but this is ambiguous as this could also mean "only 12 artifacts are valid for currently selected filters".

Also, while selecting an artifact set in that window, the first part of the artifact count only refers to the currently 12 visible artifacts. Before clicking: 
![image](https://user-images.githubusercontent.com/7204157/218177075-595d95ed-d778-4487-87a8-2bfa443feaab.png)

it says 3 artifacts

After clicking: 
![image](https://user-images.githubusercontent.com/7204157/218177159-193d8248-5036-4ca5-b69e-9cea8a11c811.png)

it says 12, despite the fact that I have 28. (Checked it on the "Artifacts" page, which all works correctly. This miscalculation only happens on the Character -> Overview -> Swap Artifact)

**Comment by StainAE86** [comment]
This is three issues then.

1) Add pagination to the swap artifact popup:
![image](https://user-images.githubusercontent.com/101696552/218178567-4e137a82-10a2-4fe6-950e-c10e70e042fc.png)

2) Add indication that the number is "showing" rather than "filtered":
![image](https://user-images.githubusercontent.com/101696552/218178844-0924cd43-305d-43df-a731-46c83b440e89.png)

3) Change the "total" number for the set/mainstat/etc filters to be per slot, rather than your total artifact inventory

**Comment by CaspianRoach** [comment]
I think all 3 stem from lack of pagination and I'm assuming will automatically fix themselves when page controls will be added.

**Comment by CaspianRoach** [comment]
Except for your suggestion 3, which I didn't even think about, you're right, with only Flowers selected, the dropdown should probably not include options like "Anemo DMG%"

**Comment by StainAE86** [comment]
![image](https://user-images.githubusercontent.com/101696552/221009027-237acd1f-355f-4824-9da2-a205c582d837.png)

**Comment by nguyentvan7** [comment]
Implemented in #1436
