### ISSUE TITLE
Every time I try to add a artifact after entering my stats it goes to a white screen.

### ISSUE THREAD

**Issue by 47jorwil** [frzyc/genshin-optimizer#983]
I am currently trying to add artifacts to my database and for some reason when I finish adding the details to a piece and try to add it it goes to a white screen. I have tried to do this on my phone, laptop, and even my iPad and it still goes to a white screen when I'm done editing my artifact piece. I hope this can be fixed or I can be given details on how to avoid this problem. Thank you.

**Comment by nguyentvan7** [comment]
Can you refresh the page, make sure the version in the bottom right says "9.3.8" and see if it still happens? It might have been fixed in the past few minutes, as I am not able to replicate this behavior

**Comment by nguyentvan7** [comment]
Closing since it's been a week and we released a patch that should have fixed this around the time you reported. Please feel free to reopen/resubmit if you are still encountering this issue
