### ISSUE TITLE
Adding an artifact manually pre-fills the lowest value for each substat as they're added

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#984]
![image](https://user-images.githubusercontent.com/101696552/218653126-00cdb60e-a2b2-4c69-8df2-b7cad5759787.png)

Meaning to change to a different initial roll value you have to now edit the number rather than clicking on the first value you want.

Could use this oppertunity to enhance the Artifact Editor by changing the buttons to a slider with the devisions set to valid substat rolls.

This would be a nice QOL especially for mobile users who have to manually edit the text box if accidently pressed the wrong value box.

**Comment by Mars4it** [comment]
I noticed that it also won't let you change it to 0 either. When you do, it still imagines it as the lowest value.
![Screenshot 2023-02-14 8 29 03 AM](https://user-images.githubusercontent.com/125372615/218752646-f4f7b328-91e6-46a9-a453-a1ba3ea91c68.png)

**Comment by livipup** [comment]
Just noticed this one as well
