### ISSUE TITLE
all claymore characters show the Luxurious Sea Lord passive

### ISSUE THREAD

**Issue by Mars4it** [frzyc/genshin-optimizer#986]
I checked for all the claymore users and all of them have Luxurious Sea Lord's passive despite not having it equipped?
![New Drawing](https://user-images.githubusercontent.com/125372615/218764992-6c3cee7d-6208-4041-8bd8-165c1fb9e367.jpg)

**Comment by Mars4it** [comment]
Screenshots of other characters:

![Screenshot 2023-02-14 9 15 22 AM](https://user-images.githubusercontent.com/125372615/218765150-50b303be-63f9-4e2c-811b-749c444a867d.png)
![Screenshot 2023-02-14 9 15 09 AM](https://user-images.githubusercontent.com/125372615/218765154-dc93e5c4-25e6-4523-868f-1f8dbc1fabbe.png)
![Screenshot 2023-02-14 9 14 57 AM](https://user-images.githubusercontent.com/125372615/218765156-953b55e3-acfc-4136-a7bc-cc9de4af18ec.png)
![Screenshot 2023-02-14 9 14 43 AM](https://user-images.githubusercontent.com/125372615/218765158-8b4cd337-7b60-4464-9bb5-ee377324b79f.png)
![Screenshot 2023-02-14 9 14 31 AM](https://user-images.githubusercontent.com/125372615/218765160-d96349dd-c487-40d2-88cf-e42cdb08229a.png)
![Screenshot 2023-02-14 9 14 18 AM](https://user-images.githubusercontent.com/125372615/218765161-95a75e0d-ca04-4498-9031-a20aa7caa653.png)

**Comment by livipup** [comment]
![image](https://user-images.githubusercontent.com/55419351/218834968-ae8da827-317a-4760-adaf-6d8c66103dbb.png)
I was going to report this as well

**Comment by frzyc** [comment]
assign to @nguyentvan7 , probably introduced in #966
