### ISSUE TITLE
Multiple entries when merging `unique` for key art,plume,id

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#991]
Upload attached DB and navigate to Ayaka's optimize page. On Prod, look at the console. On dev, the page will crash
[Van_2023-02-14_04-56-16 - Copy.txt](https://github.com/frzyc/genshin-optimizer/files/10751907/Van_2023-02-14_04-56-16.-.Copy.txt)

**Comment by frzyc** [comment]
I should have a fix for this in #944 
https://github.com/frzyc/genshin-optimizer/pull/944/files#diff-1caad9d4cc71c56c86b391364dcc9afabd8557e16870a5ec2210e4762b93176dL34
