### ISSUE TITLE
Include Equipped and Include Unequipped should be combined as a button group

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#995]
Currently you can unselect both in the artifact filter, which displays nothing and doesn't really make sense. We should make them connected as a multi select filter

**Comment by ineedanamepls** [comment]
Trying my hardest to get this done 🫡

**Comment by frzyc** [comment]
superseded by https://github.com/frzyc/genshin-optimizer/issues/1569
